Repository arduino/arduino-cli, pull requests merged in 2019-09, with the labels that each got.

#388 [skip changelog] fix codecov job
  .github/workflows/test.yaml
Labels: component/tooling

#390 [skip changelog] Add coverage for legacy tests
  .codecov.yml
  .github/workflows/test.yaml
  Taskfile.yml
Labels: component/testing

#393 Check json logs entries in compile and upload python integration tests
  commands/compile/compile.go
  commands/upload/upload.go
  test/.flake8
  test/__init__.py
  test/common.py
  test/conftest.py
  test/test_board.py
  test/test_compile.py
  test/test_lib.py
  test/test_main.py
Labels: component/testing

#395 Show core name when listing boards
  README.md
  cli/board/list.go
Labels: component/CLI, component/docs

#396 Command `sketch new` do not join sketchbook path to sketch name if only sketchname is provided
  .gitignore
  cli/cli_test.go
  cli/sketch/new.go
  test/conftest.py
  test/requirements.txt
  test/test_compile.py
  test/test_sketch.py
Labels: component/CLI

#408 [skip changelog] Only run job on comments activity
  .github/workflows/stale.yaml
Labels: component/tooling

#410 Do not fail if install folder is not in PATH
  install.sh
Labels: component/tooling

#417 Use the right variable
  .github/workflows/stale.yaml
Labels: component/tooling

#405 List cores with core search
  cli/core/search.go
Labels: component/CLI

#419 Add a test case for `core search`
  go.mod
  test/test_board.py
Labels: component/testing

#411 Add detected port even if the board couldn't be recognized
  commands/board/list.go
Labels: component/CLI

#422 Updated some dependencies
  go.mod
  go.sum
Labels: component/core

#418 Replace ctx.ToolsDirs with ctx.BuiltInToolsDirs
  commands/compile/compile.go
  legacy/builder/grpc/rpc.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/load_vid_pid_specific_properties_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/tools_loader.go
  legacy/builder/types/context.go
Labels: component/core, kind/bug
