Repository arduino/arduino-cli, pull requests merged in 2019-11, with the labels that each got.

#463 Board identification: always check vid.1/pid.1
  arduino/cores/packagemanager/identify.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/cores/packagemanager/testdata/custom_hardware/test/avr/boards.txt
Labels: component/CLI, kind/bug

#471 [skip changelog] Don't run mocked tests on OSX
  .github/workflows/test.yaml
  cli/cli_test.go
  commands/daemon/monitor_test.go
  go.mod
Labels: component/testing

#466 Allow running specific unit tests
  CONTRIBUTING.md
  Taskfile.yml
Labels: component/testing

#468 Added a note to help anyone using an FTDI chip.
  README.md
Labels: component/docs

#473 [skip changelog] unpin OS version on runners
  .github/workflows/test.yaml
Labels: component/tooling

#477 Fixed nil pointer exception on some rare case with multiple libs selection
  arduino/libraries/librarieslist.go
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
  go.mod
Labels: kind/bug

#472 re-allow global user-customizable platform.txt
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/package_manager.go
  legacy/builder/setup_build_properties.go
Labels: component/core, kind/bug

#479 Auto-disable (deep) caching of core builds if needed
  legacy/builder/phases/core_builder.go
Labels: component/core, kind/feature-request

#476 [skip ci] fix stalebot
  .github/workflows/stale.yaml
Labels: component/tooling

#483 Add "--all" option to "core search" to show all available versions
  arduino/cores/cores.go
  cli/core/search.go
  commands/core/core.go
  commands/core/search.go
  commands/daemon/daemon.go
  rpc/commands/core.pb.go
  rpc/commands/core.proto
  test/test_board.py
  test/test_core.py
  test/testdata/test_index.json
Labels: component/CLI, component/core, component/gRPC

#488 Terminate daemon command when parent process exits; added "--daemonize" flag to keep old behaviour
  cli/daemon/daemon.go
Labels: component/gRPC

#492 [ci skip] Show how to use the configuration file
  README.md
Labels: component/docs

#498 [ci skip] Use unzip on Windows in the install script
  install.sh
Labels: component/tooling

#491 Avoid panics when compiling for custom boards
  arduino/cores/cores.go
  arduino/cores/packagemanager/package_manager.go
  arduino/libraries/librariesmanager/install.go
Labels: component/core
