Repository arduino/arduino-cli, pull requests merged in 2019-12, with the labels that each got.

#499 Look for query string into more fields when searching for libs
  commands/lib/search.go
  test/test_lib.py
Labels: component/CLI

#507 GRPC serial monitor: Fix unhandled error (`EINTR`) that leaves serial port open
  arduino/monitors/serial.go
  commands/upload/upload.go
  go.mod
  go.sum
Labels: kind/bug

#443 Fix "lib uninstall" when library name contains spaces
  arduino/libraries/librariesmanager/librariesmanager.go
  test/conftest.py
Labels: component/core

#513 Set the daemon TCP port from config file or command line
  cli/daemon/daemon.go
  configuration/defaults.go
Labels: component/CLI

#511 "lib list" now returns an empty json array when there are no libraries installed
  cli/lib/list.go
  test/test_lib.py
Labels: component/CLI

#515 [skip changelog] Sliglthly optimize searchConfigTree
  cli/cli.go
  cli/cli_test.go
Labels: component/CLI

#517 [skip changelog] bump packages to support Python 3.8
  .github/workflows/test.yaml
  test/requirements.in
  test/requirements.txt
Labels: component/testing, component/tooling

#521 Add gRPC interface to CLI settings
  Taskfile.yml
  arduino/builder/sketch_test.go
  cli/daemon/daemon.go
  commands/daemon/settings.go
  commands/daemon/settings_test.go
  commands/daemon/testdata/arduino-cli.yml
  go.sum
  rpc/commands/board.pb.go
  rpc/commands/commands.pb.go
  rpc/commands/common.pb.go
  rpc/commands/compile.pb.go
  rpc/commands/core.pb.go
  rpc/commands/lib.pb.go
  rpc/commands/upload.pb.go
  rpc/monitor/monitor.pb.go
  rpc/settings/settings.pb.go
  rpc/settings/settings.proto
Labels: component/gRPC

#525 [skip changelog] Improve the README
  README.md
  README.rst
Labels: component/docs

#528 [skip changelog] Do not ship readme with packages
  .goreleaser.yml
Labels: component/packaging

#530 Fix update index on fresh installs
  cli/board/attach.go
  cli/board/details.go
  cli/board/list.go
  cli/board/listall.go
  cli/compile/compile.go
  cli/core/download.go
  cli/core/install.go
  cli/core/list.go
  cli/core/search.go
  cli/core/uninstall.go
  cli/core/update_index.go
  cli/core/upgrade.go
  cli/instance/instance.go
  cli/lib/check_deps.go
  cli/lib/download.go
  cli/lib/install.go
  cli/lib/list.go
  cli/lib/search.go
  cli/lib/uninstall.go
  cli/lib/update_index.go
  cli/lib/upgrade.go
  cli/upload/upload.go
  commands/instances.go
  rpc/commands/commands.proto
Labels: component/CLI

#531 Fix config init on fresh installs
  cli/config/init.go
Labels: component/CLI
