Repository arduino/arduino-cli, pull requests merged in 2019-08, with the labels that each got.

#315 Update single libraries
  cli/instance/instance.go
  cli/lib/upgrade.go
  commands/core/install.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  commands/daemon/daemon.go
  commands/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/list.go
  commands/lib/search.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
Labels: component/CLI, component/core

#317 Make tests independent from each other
  test/.flake8
  test/README.md
  test/__init__.py
  test/common.py
  test/conftest.py
  test/requirements.txt
  test/test_board.py
  test/test_lib.py
  test/test_main.py
Labels: component/testing

#316 Add --additional-urls flag
  cli/cli.go
  cli/globals/globals.go
  cli/instance/instance.go
  test/test_board.py
  test/testdata/core.txt
  test/testdata/test_index.json
Labels: component/CLI

#320 [skip ci] add editorconfig file
  .editorconfig
Labels: component/tooling

#318 [skip changelog] Add Appveyor badge to the readme
  README.md
Labels: component/docs

#322 add nightly pipeline
  .drone.yml
  .goreleaser.yml
Labels: component/packaging

#321 Remove unused auth package
  auth/README.adoc
  auth/auth.go
  auth/auth_test.go
Labels: component/dependencies

#323 Make goreleaser aware of RCs
  .goreleaser.yml
Labels: component/tooling

#324 Add install script and update install instructions
  .editorconfig
  README.md
  install.sh
Labels: component/docs, component/packaging

#332 [skip changelog] ask for the full command line
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: component/tooling

#330 [skip changelog] Fix examples in README
  README.md
Labels: component/docs

#327 Clean up plugglable discovery and refactor serial-discovery usage
  arduino/discovery/discovery.go
  cli/board/list.go
  commands/board/attach.go
  commands/board/details.go
  commands/board/list.go
  commands/board/listall.go
  commands/bundled_tools_serial_discovery.go
  commands/compile/compile.go
  commands/core/download.go
  commands/core/install.go
  commands/core/search.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  commands/daemon/daemon.go
  commands/discoveries.go
  commands/instances.go
  commands/upload/upload.go
Labels: component/core

#335 [skip changelog] Upgrade protobuf on the CI
  Dockerfiles/CI/Dockerfile
Labels: component/tooling

#329 [skip changelog] Remove protobuf workaround on AppVeyor
  .drone.yml
  appveyor.yml
Labels: component/dependencies

#336 Query the backend to get the fqbn when a core is not installed
  arduino/cores/packagemanager/identify.go
  cli/board/list.go
  cli/output/table.go
  cli/output/text.go
  commands/board/list.go
  commands/board/list_test.go
  commands/daemon/daemon.go
Labels: component/core

#331 Fix compile error when --preprocess or --show-properties were passed
  commands/compile/compile.go
  legacy/builder/wipeout_build_path_if_build_options_changed.go
Labels: component/core

#338 Fix install.sh script so it downloads the right package for ARMv7
  install.sh
Labels: component/packaging

#341 Add support for ARM v6
  .goreleaser.yml
  install.sh
Labels: component/packaging

#339 Fix install script for Windows shells
  install.sh
Labels: component/packaging

#347 Do not hit github api to get latest version from install script
  install.sh
Labels: component/packaging

#346 [skip changelog] deprecate latest links
  README.md
Labels: component/docs

#326 Create a compile+upload combo command
  cli/compile/compile.go
  test/test_compile.py
Labels: component/CLI

#360 Output library resolution details only on verbose build
  legacy/builder/resolve_library.go
Labels: component/core

#359 Check if variantFolder exists and is a folder
  legacy/builder/phases/core_builder.go
Labels: component/core, kind/bug

#352 [skip changelog] Migrate tests to GH actions
  .codecov.yml
  .drone.yml
  .github/workflows/test.yaml
  Taskfile.yml
  appveyor.yml
  arduino/builder/sketch_test.go
  arduino/builder/testdata/TestMergeSketchSources_win.txt
  cli/cli_test.go
  configs/navigate_test.go
  go.sum
  test/common.py
Labels: component/testing, component/tooling

#361 [skip changelog] Revert the gRPC client example to a runnable go program
  .gitignore
  README.md
  client_example/go.mod
  client_example/go.sum
  client_example/hello.ino
  client_example/main.go
  commands/daemon/client_test.go
Labels: component/docs

#363 [skip changelog] Use workflow badge on the README
  README.md
Labels: component/docs

#365 Make the serial discovery execution atomic
  commands/board/list.go
  commands/bundled_tools_serial_discovery.go
Labels: component/core

#375 [skip changelog] Upload coverage only on push events
  .github/workflows/test.yaml
Labels: component/tooling

#369 [skip changelog] Add Github workflow to push nightlies
  .github/workflows/nightly.yaml
Labels: component/tooling

#380 [skip changelog] remove drone pipeline
  .drone.yml
Labels: component/tooling

#378 Add an option to format logs with JSON
  cli/cli.go
  test/test_main.py
Labels: component/CLI

#381 [skip changelog] [skip ci] Add latest redirect links for nightly builds
  README.md
Labels: component/docs

#382 Rewrite the serial discovery logic
  commands/board/list.go
  commands/bundled_tools_serial_discovery.go
Labels: component/core

#383 [skip changelog] sync api query
  commands/board/list.go
Labels: component/core

#384 [skip changelog] Fix changelog filters
  .goreleaser.yml
Labels: component/tooling
