Repository arduino/arduino-cli, pull requests merged in 2019-10, with the labels that each got.

#432 Fix panic on missing sketch path
  cli/board/attach.go
Labels: component/CLI

#438 Removed globals.HTTPClientHeader global
  cli/core/download.go
  cli/core/install.go
  cli/core/upgrade.go
  cli/globals/globals.go
  cli/instance/instance.go
  cli/lib/download.go
  cli/lib/install.go
  cli/lib/upgrade.go
  commands/board/list.go
Labels: kind/bug

#391 Make commands output agnostic
  cli/board/details.go
  cli/board/list.go
  cli/board/listall.go
  cli/cli.go
  cli/config/dump.go
  cli/config/init.go
  cli/core/list.go
  cli/core/search.go
  cli/feedback/exported.go
  cli/feedback/feedback.go
  cli/globals/globals.go
  cli/lib/list.go
  cli/lib/search.go
  cli/output/rpc_progress.go
  cli/version/version.go
  test/test_lib.py
Labels: component/CLI

#439 Avoid calling cloud API if vid or pid are invalid
  commands/board/list.go
  commands/board/list_test.go
Labels: component/CLI

#437 install arduino-cli via homebrew
  README.md
Labels: hacktoberfest

#442 [skip ci] [skip changelog] Add contributors reference in README.md
  README.md
Labels: component/docs

#444 [skip-changelog] Reformat install instructions
  README.md
Labels: component/docs

#448 Do not try to identify non-usb ports via vid/pid
  commands/board/list.go
  commands/board/list_test.go
  go.mod
Labels: component/core, kind/bug

#450 [ci skip] fix README badges
  README.md
Labels: component/docs

#449 [skip changelog] better match for skip clauses
  .goreleaser.yml
  go.mod
Labels: component/tooling

#451 Run tests on OSX
  .github/workflows/test.yaml
Labels: component/testing

#453 [skip changelog] Force windows env to use bash as shell instead of powershell
  .github/workflows/test.yaml
Labels: component/tooling

#457 Fixed upload issue on esp32 (partitions artifacts copy)
  cli/cli_test.go
  cli/testdata/Blink/Blink.ino
  commands/compile/compile.go
  go.mod
  go.sum
  test/requirements.txt
Labels: component/CLI

#421 Use a local Walk function
  arduino/builder/sketch.go
Labels: component/CLI

#460 Mention style check in contributing guidelines
  CONTRIBUTING.md
Labels: component/docs
