Repository arduino/arduino-cli, pull requests merged in 2019-07, with the labels that each got.

#274 improve find FQBN FAQ
  README.md
Labels: documentation

#288 Move default include files where protoc can find them
  Dockerfiles/CI/Dockerfile
Labels: component/tooling

#289 Change label name used by dependabot
  .dependabot/config.yml
Labels: component/tooling

#282 Added integration test
  .gitignore
  test/README.md
  test/pytest.ini
  test/requirements.txt
  test/test_main.py
Labels: component/testing

#291 Fix core upgrade
  Taskfile.yml
  arduino/cores/cores.go
  arduino/cores/packageindex/index.go
  arduino/cores/packagemanager/download.go
  arduino/cores/packagemanager/install_uninstall.go
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/status.go
  cli/core/list.go
  cli/core/upgrade.go
  commands/board/listall.go
  commands/bundled_tools_ctags.go
  commands/bundled_tools_serial_discovery.go
  commands/core/core.go
  commands/core/list.go
  commands/core/search.go
  commands/core/upgrade.go
  commands/daemon/daemon.go
  commands/instances.go
  commands/upload/upload.go
  legacy/builder/add_build_board_property_if_missing.go
  legacy/builder/hardware_loader.go
  legacy/builder/rewrite_hardware_keys.go
  legacy/builder/setup_build_properties.go
  legacy/builder/test/hardware_loader_test.go
  legacy/builder/test/rewrite_hardware_keys_test.go
  legacy/builder/types/context.go
Labels: component/CLI, component/core

#295 Add Python3.7 to the CI image
  Dockerfiles/CI/Dockerfile
Labels: component/tooling

#296 Run integration tests on the CI
  .drone.yml
  Taskfile.yml
  cli/cli_test.go
  version/version_test.go
Labels: component/testing, component/tooling

#297 Assert output is empty
  test/test_main.py
Labels: component/testing

#298 Make lib install exit with 0 if library is already present
  arduino/libraries/librariesindex/reference.go
  arduino/libraries/librariesmanager/install.go
  cli/core/args.go
  cli/core/args_test.go
  cli/core/download.go
  cli/core/install.go
  cli/core/uninstall.go
  cli/core/upgrade.go
  cli/globals/args.go
  cli/globals/args_test.go
  cli/globals/configs.go
  cli/globals/globals.go
  cli/lib/download.go
  cli/lib/install.go
  cli/lib/uninstall.go
  commands/lib/install.go
Labels: component/CLI

#300 Remove build date from the version
  cli/daemon/daemon.go
  cli/globals/globals.go
  test/test_main.py
  version/version.go
  version/version_test.go
Labels: component/core

#299 Do not exit with an error if lib is not present
  commands/lib/uninstall.go
  commands/lib/utils.go
Labels: component/CLI, component/core

#301 Remove redundant tests
  cli/cli_test.go
Labels: component/testing

#303 Run tests on Appveyor
  Taskfile.yml
  appveyor.yml
  test/conftest.py
  test/test_main.py
Labels: component/tooling

#309 Skip tests we cannot run on Drone
  .drone.yml
  test/test_main.py
Labels: component/tooling

#310 Use same default data dir as the IDE on OSX
  commands/.test-config.yml
  configs/directories.go
Labels: component/core, os/OSX

#294 Use `BoardsManifest` if `Boards` is not applicable
  commands/core/core.go
Labels: component/core

#286 gRPC interface to monitors
  Taskfile.yml
  appveyor.yml
  arduino/monitors/serial.go
  arduino/monitors/types.go
  cli/daemon/daemon.go
  commands/daemon/monitor.go
  commands/daemon/monitor_test.go
  go.mod
  go.sum
  rpc/monitor/monitor.pb.go
  rpc/monitor/monitor.proto
Labels: component/gRPC

#308 Sync board list to avoid race conditions
  arduino/discovery/discovery.go
Labels: component/core

#293 Changed AdditionalSketchFilesCopier legacy command into new builder API function
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  arduino/builder/testdata/TestCopyAdditionalFiles/TestCopyAdditionalFiles.ino
  arduino/builder/testdata/TestCopyAdditionalFiles/include/foo.h
  legacy/builder/additional_sketch_files_copier.go
  legacy/builder/container_add_prototypes.go
  legacy/builder/container_merge_copy_sketch_files.go
  legacy/builder/container_setup.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/test/additional_sketch_files_copier_test.go
Labels: component/core

#311 Use goreleaser to build the full binary matrix
  .drone.yml
  .gitignore
  .goreleaser.yml
  CONTRIBUTING.md
  Dockerfiles/builder/Dockerfile
  README.md
Labels: component/packaging, component/tooling

#314 Goreleaser S3 upload support
  .drone.yml
  .goreleaser.yml
Labels: component/packaging
