Repository arduino/arduino-cli, pull requests merged in 2020-01, with the labels that each got.

#536 Improve error message on build failure
  cli/compile/compile.go
  commands/compile/compile.go
  legacy/builder/phases/sizer.go
Labels: component/CLI

#545 Fix regression on compile and upload with attached sketches
  cli/cli_test.go
  cli/compile/compile.go
  cli/upload/upload.go
Labels: component/CLI

#547 Use https scheme in the README example
  README.rst
Labels: component/docs

#537 Allow naming sketches like "RCS" and "CVS"
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  legacy/builder/container_setup.go
  test/test_compile.py
Labels: component/CLI, component/core

#548 [skip changelog] [skip ci] Clarify additional-urls option usage
  README.rst
Labels: component/docs

#551 Added more help on log levels
  cli/cli.go
Labels: component/CLI

#554 [skip changelog] Demonstrate the use of the gRPC Settings interface in client_example
  client_example/go.mod
  client_example/go.sum
  client_example/main.go
Labels: component/docs, kind/bug

#552 [skip changelog] Demonstrate gRPC interface's LibraryResolveDependencies method in client_example
  client_example/go.mod
  client_example/main.go
Labels: component/docs

#436 Add --libraries flag to compile command
  cli/compile/compile.go
  commands/compile/compile.go
  rpc/commands/compile.pb.go
  rpc/commands/compile.proto
Labels: component/CLI, component/core

#559 Load contents of source files only when needed
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  arduino/sketch/sketch.go
  arduino/sketch/sketch_test.go
  legacy/builder/container_add_prototypes.go
  legacy/builder/container_merge_copy_sketch_files.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/sketch_loader.go
  legacy/builder/types/types.go
Labels: component/core

#558 Remove ignored Configuration GRPC API
  go.mod
  go.sum
  rpc/commands/commands.pb.go
  rpc/commands/commands.proto
  rpc/monitor/monitor.pb.go
  rpc/settings/settings.pb.go
Labels: component/gRPC

#556 Fix `core search` not showing board name for 3rd party cores
  cli/core/search.go
  commands/core/search.go
  commands/core/search_test.go
  test/test_core.py
  test/testdata/core.txt
  test/testdata/core.zip
  test/testdata/test_index.json
Labels: component/CLI

#564 [skip changelog] Move integration tests to pytest
  CONTRIBUTING.md
  Taskfile.yml
  cli/cli_test.go
  cli/testdata/Blink/Blink.ino
  cli/testdata/Test3rdPartyCoreIntegration/arduino-cli.yaml
  cli/testdata/TestInvalidCoreURLIntegration/arduino-cli.yaml
  test/README.md
  test/common.py
  test/conftest.py
  test/requirements.in
  test/requirements.txt
  test/test_compile.py
  test/test_core.py
  test/test_upload.py
Labels: component/testing

#565 Fix library priority selection
  arduino/libraries/libraries.go
  arduino/libraries/librarieslist.go
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
Labels: component/core, kind/bug

#544 Libraries dependencies: output error if no valid solution found
  commands/lib/resolve_deps.go
  test/test_lib.py
Labels: kind/bug
