Repository arduino/arduino-cli, pull requests merged in 2020-06, with the labels that each got.

#734 [skip changelog] Update latest tag at mike deploy
  Taskfile.yml
Labels: component/docs, component/tooling

#736 I18n fetch language codes from transifex
  Taskfile.yml
  docs/CONTRIBUTING.md
  i18n/README.md
  i18n/cmd/commands/transifex/pull_transifex.go
Labels: component/CLI

#692 [skip changelog] Add documentation for library components of the gRPC interface
  rpc/commands/commands.pb.go
  rpc/commands/commands.proto
  rpc/commands/lib.pb.go
  rpc/commands/lib.proto
Labels: component/docs, component/gRPC

#748 [skip changelog] Document Arduino CLI's configuration methods
  docs/configuration.md
  docs/getting-started.md
  docs/integration-options.md
  mkdocs.yml
Labels: component/docs

#763 Daemon listen to localhost
  cli/daemon/daemon.go
Labels: component/gRPC
