Repository arduino/arduino-cli, pull requests merged in 2020-02, with the labels that each got.

#560 Add cache clean command
  cli/cache/cache.go
  cli/cache/clean.go
  cli/cli.go
  test/test_cache.py
Labels: component/CLI

#574 Fix libraries priority selection (again)
  arduino/libraries/libraries.go
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
Labels: component/core, kind/bug

#512 Improve precompiled libraries handling
  legacy/builder/constants/constants.go
  legacy/builder/phases/libraries_builder.go
Labels: component/core

#577 Fixed wrong escaping on legacy MachineLogger
  legacy/builder/i18n/i18n.go
Labels: component/core

#575 Add option --dest-dir to config init, removed noop --save-as
  cli/config/init.go
  test/test_config.py
Labels: component/CLI

#579 Reduce priority for IDE-bundled platform releases
  arduino/cores/cores.go
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/package_manager.go
Labels: component/core, kind/bug

#578 Integrate Apple notarization process into Github Actions release pipeline
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  gon.config.hcl
Labels: component/packaging

#580 Force notarization process to take place configuring Gon zip output
  .github/workflows/release.yaml
  gon.config.hcl
Labels: component/packaging

#514 fix filter sketch source
  legacy/builder/create_cmake_rule.go
Labels: component/core

#592 Added better error handling for the gRPC server.
  cli/daemon/daemon.go
Labels: component/CLI

#590 Implement debug feature
  Taskfile.yml
  arduino/cores/packagemanager/package_manager.go
  arduino/utils/stream.go
  cli/cli.go
  cli/daemon/daemon.go
  cli/debug/debug.go
  client_example/go.mod
  client_example/go.sum
  client_example/hello/hello.ino
  client_example/main.go
  commands/daemon/daemon.go
  commands/daemon/debug.go
  commands/debug/debug.go
  commands/debug/debug_test.go
  commands/debug/testdata/custom_hardware/arduino-test/samd/boards.txt
  commands/debug/testdata/custom_hardware/arduino-test/samd/platform.txt
  commands/debug/testdata/data_dir/packages/arduino-test/tools/arm-none-eabi-gcc/7-2017q4/bin/arm-none-eabi-gdb
  commands/debug/testdata/data_dir/packages/arduino-test/tools/openocd/0.10.0-arduino7/bin/openocd
  commands/debug/testdata/hello/hello.arduino-test.samd.arduino_zero_edbg.bin
  commands/debug/testdata/hello/hello.arduino-test.samd.mkr1000.bin
  go.sum
  rpc/commands/commands.pb.go
  rpc/debug/debug.pb.go
  rpc/debug/debug.proto
  rpc/monitor/monitor.pb.go
  rpc/settings/settings.pb.go
Labels: component/CLI, component/core, component/gRPC

#593 Add support for compile with debug optimizations
  cli/compile/compile.go
  commands/compile/compile.go
  legacy/builder/builder_utils/utils.go
  legacy/builder/create_build_options_map.go
  legacy/builder/phases/core_builder.go
  legacy/builder/setup_build_properties.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/types/context.go
  rpc/commands/compile.pb.go
  rpc/commands/compile.proto
  rpc/debug/debug.pb.go
Labels: component/core

#597 Fix paths handling for gdb
  commands/debug/debug.go
Labels: component/core

#599 Added 'dependencies', 'license' and 'provides_includes' fields in lib search
  arduino/libraries/librariesindex/index.go
  arduino/libraries/librariesindex/json.go
  cli/lib/search.go
  commands/lib/search.go
  rpc/commands/lib.pb.go
  rpc/commands/lib.proto
Labels: component/gRPC
