Repository arduino/arduino-cli, pull requests merged in 2020-04, with the labels that each got.

#598 Show similar library names in lib search
  cli/lib/search.go
  commands/lib/search.go
  commands/lib/search_test.go
  commands/lib/testdata/library_index.json
  go.mod
  go.sum
  rpc/commands/lib.pb.go
  rpc/commands/lib.proto
Labels: component/core, component/gRPC

#595 Improve output message with config file creation
  cli/config/init.go
Labels: component/CLI

#638 Update FAQ.md
  docs/FAQ.md
Labels: component/docs

#646 [skip changelog] Github Actions bugfixes
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: component/tooling

#628 'arduino-cli lib' command arguments are now case insensitive
  cli/globals/args.go
  cli/globals/args_test.go
  cli/lib/args.go
  cli/lib/args_test.go
  cli/lib/check_deps.go
  cli/lib/download.go
  cli/lib/install.go
  cli/lib/uninstall.go
  test/test_lib.py
Labels: component/core

#653 [skip changelog] Fix typos in command line help text
  cli/board/board.go
  cli/board/list.go
  cli/cli.go
  cli/compile/compile.go
  cli/config/config.go
  cli/core/core.go
  cli/core/download.go
  cli/core/install.go
  cli/core/uninstall.go
  cli/sketch/sketch.go
  cli/version/version.go
Labels: component/CLI, component/docs

#658 Fixed path-relativization error when traversing different partitions
  legacy/builder/utils/utils.go
Labels: component/core, kind/bug

#659 [skip ci] [skip changelog] Fix typos in CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: component/docs

#606 Fixed wrong IDE bundle-detection result caching
  configuration/configuration.go
Labels: component/core

#609 Added configuration option for proxy usage
  arduino/cores/packagemanager/download.go
  arduino/libraries/librariesmanager/download.go
  arduino/resources/helpers.go
  arduino/resources/helpers_test.go
  arduino/resources/resources_test.go
  cli/core/download.go
  cli/core/install.go
  cli/core/upgrade.go
  cli/daemon/daemon.go
  cli/globals/globals.go
  cli/instance/instance.go
  cli/lib/download.go
  cli/lib/install.go
  cli/lib/upgrade.go
  commands/board/list.go
  commands/bundled_tools.go
  commands/core/download.go
  commands/core/install.go
  commands/core/upgrade.go
  commands/daemon/daemon.go
  commands/download.go
  commands/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/upgrade.go
  configuration/defaults.go
  go.mod
  go.sum
Labels: component/CLI, do not merge - WIP

#654 [skip changelog] Add sketch specification to documentation
  docs/sketch-specification.md
  mkdocs.yml
Labels: component/docs

#652 [skip changelog] Fix incorrect software specificity/non-specificity in documentation
  docs/library-specification.md
  docs/package_index_json-specification.md
  docs/platform-specification.md
  docs/sketch-build-process.md
Labels: component/docs

#665 [skip changelog] Gather downloads stats from GitHub releases
  .github/workflows/github-stats.yaml
Labels: component/tooling

#667 [skip changelog] Add alert when nightly build fails
  .github/workflows/nightly.yaml
Labels: component/tooling

#668 [skip changelog] Collect download stats less often
  .github/workflows/github-stats.yaml
Labels: component/tooling
