Repository arduino/arduino-cli, pull requests merged in 2021-08, with the labels that each got.

#1372 [skip changelog] Remove obsolete "Dependabot Preview" configuration file
  .dependabot/config.yml
Labels: topic: dependencies, topic: infrastructure

#1373 [skip changelog] Configure Dependabot to check for outdated actions used in workflows
  .github/dependabot.yml
Labels: topic: infrastructure, type: enhancement

#1379 [skip changelog] Sync certificate check CI workflow with template
  .github/workflows/check-certificates.yml
Labels: type: enhancement, topic: infrastructure

#1381 [skip changelog] Add skip changelog prefix to Dependabot workflow update commits
  .github/dependabot.yml
Labels: type: enhancement, topic: infrastructure

#1386 [skip changelog] Move website versioning information out of CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: type: bug, type: enhancement, topic: documentation

#1388 Sync testing infrastructure with "template" assets
  .github/workflows/check-go-task.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  .github/workflows/test.yaml
  DistTasks.yml
  README.md
  Taskfile.yml
  arduino/discovery/discovery_client/go.sum
  cli/lib/examples.go
  cli/lib/list.go
  commands/daemon/term_example/go.mod
  commands/daemon/term_example/go.sum
  docs/CONTRIBUTING.md
  docsgen/go.sum
  go.mod
  go.sum
Labels: type: enhancement, topic: infrastructure

#1387 Remove duplicate task for protobuf docs generation
  Taskfile.yml
Labels: type: enhancement, topic: gRPC, topic: infrastructure

#1389 [skip changelog] Revert "Add skip changelog prefix to Dependabot workflow update commits (#1381)"
  .github/dependabot.yml
Labels: type: bug, topic: infrastructure

#1390 [skip changelog] Run formatting and linting CI checks on all Go modules
  .github/workflows/check-go-task.yml
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#1393 [skip changelog] Sync "Check Python" CI workflow with template
  .flake8
  .github/workflows/check-python-task.yml
  .github/workflows/python-lint.yaml
  Taskfile.yml
  docs/CONTRIBUTING.md
  poetry.lock
  pyproject.toml
  test/test_core.py
Labels: type: enhancement, topic: infrastructure

#1394 [skip changelog] Sync "Publish Nightly Build" CI workflow with template
  .github/workflows/nightly.yaml
  .github/workflows/publish-go-nightly-task.yml
  README.md
  gon.config.hcl
Labels: type: enhancement, topic: infrastructure

#1395 [skip changelog] Sync "Release" CD workflow with template
  .github/workflows/release-go-task.yml
Labels: type: enhancement, topic: infrastructure

#1396 [skip changelog] Sync install script with template
  .editorconfig
  .github/tools/fetch_athena_stats.sh
  docs/installation.md
  install.sh
Labels: type: enhancement, topic: infrastructure

#1397 [skip changelog] Don't require Codecov upload success for test run in fork
  .github/workflows/test-go-task.yml
Labels: type: bug, topic: infrastructure

#1400 [skip changelog] Run relevant workflows on release branch creation
  .github/workflows/check-go-task.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#1404 [skip changelog] Use major version ref for `actions/github-script` action
  .github/workflows/github-stats.yaml
Labels: type: enhancement, topic: infrastructure

#1405 Fix board attach panic if sketch.json doesn't exist
  arduino/sketch/sketch.go
  i18n/data/en.po
  i18n/rice-box.go
  test/test_board.py
Labels: type: bug, topic: CLI

#1406 Add core ID in outdated command output
  cli/outdated/outdated.go
  i18n/data/en.po
  i18n/rice-box.go
  test/test_outdated.py
  test/test_upgrade.py
Labels: type: enhancement, topic: CLI

#1411 Add test for runtime.os upload property
  test/test_upload_mock.py
Labels: topic: testing

#1410 Fix board search not returning boards if installed core is not latest version
  commands/board/search.go
  test/test_board.py
Labels: type: bug, topic: gRPC, topic: CLI, topic: core

#1409 Fix core list command not returning latest available version
  commands/core/list.go
  i18n/data/en.po
  i18n/rice-box.go
  test/test_core.py
Labels: type: bug, topic: gRPC, topic: CLI, topic: core

#1418 Enhance handling of colored output
  arduino/discovery/discovery_client/go.sum
  cli/cli.go
  cli/config/validate.go
  cli/feedback/exported.go
  cli/feedback/feedback.go
  client_example/go.sum
  commands/daemon/term_example/go.sum
  configuration/configuration.go
  configuration/defaults.go
  docsgen/go.sum
  go.mod
  go.sum
  i18n/data/en.po
  i18n/rice-box.go
Labels: type: enhancement, topic: CLI

#1416 Add ways to let users verify if new CLI released
  cli/cli.go
  cli/config/validate.go
  cli/updater/updater.go
  cli/version/version.go
  configuration/defaults.go
  docs/configuration.md
  docs/installation.md
  i18n/data/en.po
  i18n/rice-box.go
  inventory/inventory.go
  version/version.go
Labels: type: enhancement, topic: CLI

#1422 Fix upload properties not overridden by protocol specific ones
  commands/upload/upload.go
  commands/upload/upload_test.go
  docs/platform-specification.md
Labels: type: bug, topic: documentation, topic: core

#1423 Fix compile --build-path not working with relative paths
  commands/compile/compile.go
  test/test_compile.py
Labels: type: bug, topic: gRPC, topic: CLI
