Repository arduino/arduino-cli, pull requests merged in 2021-07, with the labels that each got.

#1340 [skip changelog] Update JSON output key name in integration test helper
  test/conftest.py
Labels: topic: testing, type: bug

#1342 [skip changelog] Add missing file extensions to Sketch specifications docs
  docs/sketch-specification.md
Labels: topic: documentation

#1341 [skip changelog] Remove obsolete go generate directive
  commands/daemon/daemon.go
Labels: topic: infrastructure, type: bug

#1354 Fix crash when loading boards
  arduino/cores/packagemanager/loader.go
  test/test_core.py
  test/testdata/platform_with_missing_custom_board_options/boards.txt
  test/testdata/platform_with_missing_custom_board_options/platform.txt
Labels: type: bug

#1360 [skip changelog] Make `i18n:generate` task Windows compatible
  Taskfile.yml
Labels: os: windows, topic: infrastructure, type: bug

#1365 [breaking] Pass user locale preference directly to i18n package
  docs/UPGRADING.md
  i18n/i18n.go
  main.go
Labels: topic: code, type: enhancement
