Repository arduino/arduino-cli, pull requests merged in 2021-06, with the labels that each got.

#1304 Implement function to verify index signature with custom key
  arduino/security/signature_test.go
  arduino/security/signatures.go
  arduino/security/testdata/module_firmware_index.json
  arduino/security/testdata/module_firmware_index.json.sig
  arduino/security/testdata/module_firmware_index_public.gpg.key
Labels: topic: code

#1305 [skip changelog] Specify that `includes` field items should be in library
  docs/library-specification.md
Labels: topic: documentation, type: bug

#1319 Fix upload waiting for port without 1200bps touch
  commands/upload/upload.go
Labels: topic: CLI, topic: code, type: bug

#1277 [skip changelog] Update proto files build step
  .github/workflows/link-validation.yaml
  .github/workflows/test.yaml
  .github/workflows/validate-docs.yaml
  DistTasks.yml
  Taskfile.yml
  commands/daemon/daemon.go
  commands/daemon/debug.go
  commands/daemon/monitor.go
  commands/daemon/settings.go
  docsgen/go.sum
  go.mod
  go.sum
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/debug/v1/debug.pb.go
  rpc/cc/arduino/cli/debug/v1/debug_grpc.pb.go
  rpc/cc/arduino/cli/monitor/v1/monitor.pb.go
  rpc/cc/arduino/cli/monitor/v1/monitor_grpc.pb.go
  rpc/cc/arduino/cli/settings/v1/settings.pb.go
  rpc/cc/arduino/cli/settings/v1/settings_grpc.pb.go
Labels: topic: code

#1320 [skip changelog] Fix publish docs workflow
  .github/workflows/publish-docs.yaml
Labels: topic: infrastructure

#1322 Fix empty name on manually installed platforms without platform.txt
  arduino/cores/packagemanager/loader.go
  test/test_core.py
Labels: topic: code, topic: core, type: bug

#1325 [skip changelog] Fix burn-bootloader command example
  cli/burnbootloader/burnbootloader.go
Labels: topic: documentation

#1326 Fix loading platforms with malformed boards.txt
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/package_manager_test.go
  legacy/builder/test/user_hardware/my_avr_platform/avr/boards.txt
  test/test_core.py
  test/testdata/platform_with_wrong_custom_board_options/boards.txt
  test/testdata/platform_with_wrong_custom_board_options/platform.txt
Labels: topic: core, type: enhancement

#1331 [skip changelog] Change discoveries not starting when created
  arduino/discovery/discovery.go
  arduino/discovery/discovery_test.go
  commands/bundled_tools_serial_discovery.go
Labels: type: enhancement
