Repository arduino/arduino-cli, pull requests merged in 2021-01, with the labels that each got.

#1108 [breaking] Rename telemetry to metrics
  cli/config/validate.go
  cli/daemon/daemon.go
  commands/compile/compile.go
  configuration/configuration_test.go
  configuration/defaults.go
  docs/UPGRADING.md
  docs/configuration.md
  docs/getting-started.md
  metrics/metrics.go
  test/test_config.py
  test/test_daemon.py
Labels: component/CLI, component/docs

#1130 Enhance error messages if config paths are not valid
  cli/cli.go
  inventory/inventory.go
Labels: component/CLI

#1143 Fix lib install with git url
  arduino/libraries/librariesmanager/install.go
  cli/lib/install.go
  poetry.lock
  pyproject.toml
  test/test_lib.py
Labels: component/CLI, kind/bug

#1145 Enhance lib install from git url and zip file
  arduino/libraries/librariesmanager/install.go
  test/test_lib.py
Labels: component/CLI

#1144 Add gRPC interface function to write settings to file
  client_example/go.sum
  client_example/main.go
  commands/daemon/settings.go
  commands/daemon/settings_test.go
  rpc/settings/settings.pb.go
  rpc/settings/settings.proto
Labels: component/gRPC

#1146 Add multiple libraries installation when using --git-url or --zip-path flags
  cli/lib/install.go
  test/test_lib.py
Labels: component/CLI

#1148 [skip changelog] Update release process
  .github/workflows/i18n-nightly-push.yaml
  .github/workflows/i18n-weekly-pull.yaml
  .github/workflows/link-validation.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/python-lint.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .github/workflows/validate-docs.yaml
  .github/workflows/verify-formatting.yaml
  .goreleaser.yml
  DistTasks.yml
  Dockerfiles/builder/Dockerfile
  Taskfile.yml
  docs/installation.md
  gon.config.hcl
  poetry.lock
  pyproject.toml
  test/test_main.py
Labels: component/packaging

#1139 Skip dependency detection if library is fully precompiled
  legacy/builder/constants/constants.go
  legacy/builder/container_find_includes.go
  test/test_compile.py
Labels: component/CLI, component/core

#1159 [skip changelog] Upgrade workflow ubuntu env
  .github/workflows/test.yaml
Labels: component/testing

#1158 Fix lib install --zip-path not preserving folders structure
  arduino/libraries/librariesmanager/install.go
  test/test_lib.py
Labels: component/CLI, kind/bug

#1157 Add back support for sketches with .pde extension and deprecate it
  arduino/globals/globals.go
  arduino/libraries/loader.go
  arduino/sketches/sketches.go
  arduino/sketches/sketches_test.go
  arduino/sketches/testdata/SketchMultipleMainFiles/SketchMultipleMainFiles.ino
  arduino/sketches/testdata/SketchMultipleMainFiles/SketchMultipleMainFiles.pde
  arduino/sketches/testdata/SketchPde/SketchPde.pde
  cli/compile/compile.go
  cli/sketch/archive.go
  cli/upload/upload.go
  commands/sketch/archive.go
  commands/upload/upload.go
  docs/sketch-specification.md
  test/test_compile.py
  test/test_debug.py
  test/test_lib.py
  test/test_sketch.py
  test/test_upload.py
  test/testdata/sketch_multiple_main_files/sketch_multiple_main_files.ino
  test/testdata/sketch_multiple_main_files/sketch_multiple_main_files.pde
  test/testdata/sketch_pde_main_file/sketch_pde_main_file.pde
Labels: component/CLI, component/core
