Repository arduino/arduino-cli, pull requests merged in 2021-05, with the labels that each got.

#1278 Enhance alphabetic sorting and place deprecated platform at the bottom
  arduino/cores/cores.go
  arduino/cores/packageindex/index.go
  cli/core/list.go
  cli/core/search.go
  commands/core.go
  commands/core/list.go
  commands/core/search.go
  commands/core/search_test.go
  commands/core/testdata/package_index.json
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.pb.go
  rpc/cc/arduino/cli/debug/v1/debug.pb.go
  rpc/cc/arduino/cli/monitor/v1/monitor.pb.go
  rpc/cc/arduino/cli/settings/v1/settings.pb.go
  test/test_core.py
  test/testdata/test_index.json
Labels: topic: CLI, topic: core, topic: gRPC

#1280 Update integration-options.md
  docs/integration-options.md
Labels: topic: documentation

#1282 Fix sorting of platforms and boards
  commands/board/list.go
  commands/core/list.go
  commands/core/search.go
  test/test_core.py
Labels: topic: CLI, topic: gRPC, type: enhancement

#1118 check whether prevOpts is nil in WipeoutBuildPathIfBuildOptionsChanged's Run
  legacy/builder/constants/constants.go
  legacy/builder/wipeout_build_path_if_build_options_changed.go
  test/test_compile.py
Labels: topic: core, type: enhancement

#1284 [skip changelog] Fix tag regex for release changelog generation
  .github/workflows/release.yaml
Labels: topic: infrastructure, type: bug

#1287 [skip changelog] Document sketch filename requirements
  docs/sketch-specification.md
Labels: topic: documentation, type: bug

#1288 Fix `network` settings uneditable with config command
  cli/config/validate.go
Labels: topic: CLI, type: bug

#1290 Revert "Improved lib detection: check for matching name in library.properties (#1276)"
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
  test/test_compile.py
  test/testdata/sketch_with_conflicting_libraries_include/sketch_with_conflicting_libraries_include.ino
Labels: type: bug

#1293 [skip changelog] Libraries install dir path is now canonical
  arduino/libraries/loader.go
  go.mod
  go.sum
  test/conftest.py
  test/test_compile.py
Labels: os: windows, topic: testing

#1291 [skip changelog] Add integration tests to avoid breaking compilation for esp cores
  test/test_compile.py
  test/testdata/sketch_with_sd_library/sketch_with_sd_library.ino
Labels: topic: CLI, topic: testing

#1294 [skip changelog] Use new arduino/setup-task action name in CI/CD workflows
  .github/workflows/i18n-nightly-push.yaml
  .github/workflows/i18n-weekly-pull.yaml
  .github/workflows/link-validation.yaml
  .github/workflows/nightly.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/python-lint.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .github/workflows/validate-docs.yaml
  .github/workflows/verify-formatting.yaml
Labels: topic: infrastructure, type: enhancement

#1302 [skip changelog] Quote all variables in GitHub Actions workflow shell commands
  .github/workflows/arduino-stats.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: topic: infrastructure, topic: packaging, type: bug

#1303 [skip changelog] Remove redundant artifact upload from test workflow
  .github/workflows/test.yaml
Labels: topic: infrastructure, type: bug
