Repository arduino/arduino-cli, pull requests merged in 2021-02, with the labels that each got.

#1164 Fix gRPC interface function to merge configs
  client_example/main.go
  commands/daemon/settings.go
  commands/daemon/settings_test.go
Labels: component/gRPC

#1167 [skip changelog] Fix failing legacy testing
  legacy/builder/test/hardware_loader_test.go
Labels: component/testing

#1169 [skip changelog] Fix core commands skipping gRPC interface
  cli/core/list.go
  cli/core/search.go
  cli/core/upgrade.go
  commands/core/list.go
  commands/core/search.go
  commands/core/search_test.go
  commands/daemon/daemon.go
Labels: component/CLI, component/core

#1183 [skip changelog] Fix integration tests not deleting folders when test finishes
  test/conftest.py
Labels: component/testing

#1182 Add RootFolderFiles to gRPC LoadSketchResp
  arduino/builder/sketch_test.go
  arduino/sketch/sketch.go
  arduino/sketch/sketch_test.go
  commands/instances.go
  rpc/commands/commands.pb.go
  rpc/commands/commands.proto
  rpc/settings/settings.pb.go
Labels: component/gRPC

#1180 [skip changelog] Fix platform loading legacy tests
  docs/platform-specification.md
  legacy/builder/test/add_build_board_property_if_missing_test.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/ctags_runner_test.go
  legacy/builder/test/custom_local_txts/boards.local.txt
  legacy/builder/test/custom_local_txts/platform.local.txt
  legacy/builder/test/hardware/arduino/avr/boards.txt
  legacy/builder/test/hardware/platform.txt
  legacy/builder/test/hardware_loader_test.go
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/test/load_vid_pid_specific_properties_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/platform_keys_rewrite_loader_test.go
  legacy/builder/test/prototypes_adder_test.go
  legacy/builder/test/setup_build_properties_test.go
  legacy/builder/test/target_board_resolver_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/test/user_hardware/my_avr_platform/platform.txt
Labels: component/core, component/docs

#1166 Add --all flag to core list command and gRPC interface
  arduino/cores/cores.go
  arduino/cores/packagemanager/loader.go
  cli/core/list.go
  commands/core.go
  commands/core/list.go
  commands/core/search.go
  legacy/builder/test/hardware_loader_test.go
  rpc/commands/core.pb.go
  rpc/commands/core.proto
  test/test_compile.py
  test/test_core.py
  test/testdata/boards.local.txt
Labels: component/CLI, component/core, component/gRPC

#1189 Fix some commands crashing when an installed library has invalid version
  arduino/libraries/librariesindex/index.go
  arduino/libraries/librariesindex/index_test.go
  arduino/libraries/librariesmanager/install.go
  test/test_lib.py
  test/test_outdated.py
  test/test_update.py
  test/test_upgrade.py
Labels: component/CLI, component/gRPC, kind/bug

#1195 Add flag to skip libraries dependencies installation to gRPC LibraryInstall function
  cli/lib/install.go
  client_example/main.go
  commands/lib/install.go
  rpc/commands/lib.pb.go
  rpc/commands/lib.proto
  test/test_lib.py
Labels: component/gRPC

#1193 Change core and lib search commands to use fuzzy search
  commands/core/search.go
  commands/core/search_test.go
  commands/lib/search.go
  commands/lib/search_test.go
  go.mod
  go.sum
  test/test_core.py
  test/test_lib.py
Labels: component/CLI, component/core, component/gRPC

#1200 [skip changelog] Improve wording of docs introduction
  README.md
  docs/index.md
Labels: component/docs
