Repository arduino/arduino-cli, pull requests merged in 2021-11, with the labels that each got.

#1537 Remove hardcoded builtin tools
  commands/bundle_tools_test.go
  commands/bundled_tools_ctags.go
  commands/bundled_tools_mdns_discovery.go
  commands/bundled_tools_serial_discovery.go
  commands/bundled_tools_serial_monitor.go
  commands/instances.go
Labels: type: enhancement, topic: code, topic: CLI, topic: gRPC

#1544 [skip changelog] Sync install docs from "template"
  docs/installation.md
Labels: type: enhancement, topic: documentation, type: imperfection

#1545 [skip changelog] Mention interfaces in documentation introduction
  README.md
  docs/index.md
Labels: type: enhancement, topic: documentation

#1542 [breaking] uniform cli commands and flag
  cli/arguments/arguments.go
  cli/arguments/fqbn.go
  cli/arguments/port.go
  cli/arguments/post_install.go
  cli/arguments/programmer.go
  cli/arguments/sketch.go
  cli/board/attach.go
  cli/board/board.go
  cli/board/details.go
  cli/board/list.go
  cli/board/listall.go
  cli/board/search.go
  cli/burnbootloader/burnbootloader.go
  cli/cache/clean.go
  cli/compile/compile.go
  cli/completion/completion.go
  cli/config/add.go
  cli/config/config.go
  cli/config/delete.go
  cli/config/dump.go
  cli/config/init.go
  cli/config/remove.go
  cli/config/set.go
  cli/config/validate.go
  cli/core/download.go
  cli/core/install.go
  cli/core/list.go
  cli/core/search.go
  cli/core/uninstall.go
  cli/core/update_index.go
  cli/core/upgrade.go
  cli/daemon/daemon.go
  cli/debug/debug.go
  cli/generatedocs/generatedocs.go
  cli/instance/instance.go
  cli/lib/check_deps.go
  cli/lib/download.go
  cli/lib/examples.go
  cli/lib/install.go
  cli/lib/list.go
  cli/lib/search.go
  cli/lib/uninstall.go
  cli/lib/update_index.go
  cli/lib/upgrade.go
  cli/monitor/monitor.go
  cli/outdated/outdated.go
  cli/sketch/archive.go
  cli/sketch/new.go
  cli/sketch/sketch.go
  cli/update/update.go
  cli/upgrade/upgrade.go
  cli/upload/upload.go
  cli/version/version.go
  commands/lib/download.go
  docs/UPGRADING.md
  test/test_board.py
  test/test_config.py
Labels: type: enhancement, topic: code, topic: CLI

#1555 Locale is now refreshed on Init
  commands/instances.go
Labels: type: enhancement, topic: gRPC

#1553 remove the alpha suffix
  version/version.go
Labels: type: enhancement, topic: code, topic: CLI

#1557 Update i18n en source file
  i18n/data/en.po
Labels: type: imperfection

#1558 fix a regression introduced in #be5022e. `--input` flags were ignored
  cli/upload/upload.go
  test/test_upload.py
Labels: topic: code, type: imperfection, topic: CLI

#1552 Do not give-up on `compile --only-compilation-database` if prototypes generation fails
  legacy/builder/container_add_prototypes.go
  legacy/builder/container_find_includes.go
  test/test_compile_part_4.py
  test/testdata/sketch_with_missing_include/sketch_with_missing_include.ino
Labels: topic: code

#1571 [skip changelog] Fix link in tests README.md
  test/README.md
Labels: topic: documentation, type: imperfection

#1569 Fix panic when discovery doesn't send an ok message after a command
  arduino/discovery/discovery.go
Labels: topic: code, type: imperfection

#1576 Pin task version to 3.9.0 because of the PATH on win bug
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: os: windows, topic: infrastructure, type: imperfection
