Repository arduino/arduino-cli, pull requests merged in 2021-09, with the labels that each got.

#1426 [skip changelog] Fix integration tests on OS X
  test/conftest.py
  test/test_compile.py
  test/test_core.py
  test/test_upload_mock.py
Labels: topic: testing

#1429 Fix upload command not working as expected when certain flags are used
  arduino/sketch/sketch.go
  arduino/sketch/sketch_test.go
  cli/upload/upload.go
  i18n/data/en.po
  i18n/rice-box.go
  test/test_upload.py
Labels: type: bug, topic: CLI

#1430 [skip changelog] Update cobra to latest version
  arduino/discovery/discovery_client/go.sum
  client_example/go.mod
  client_example/go.sum
  commands/daemon/term_example/go.mod
  commands/daemon/term_example/go.sum
  docsgen/go.mod
  docsgen/go.sum
  go.mod
  go.sum
  test/test_completion.py
Labels: topic: dependencies

#1432 [skip changelog] Fix Windows integration tests
  test/conftest.py
  test/test_board.py
  test/test_cache.py
  test/test_compile.py
  test/test_completion.py
  test/test_config.py
  test/test_core.py
  test/test_debug.py
  test/test_lib.py
  test/test_main.py
  test/test_outdated.py
  test/test_sketch.py
  test/test_update.py
  test/test_upgrade.py
  test/test_upload.py
  test/test_upload_mock.py
Labels: type: enhancement, topic: testing

#1442 [skip changelog] Temporarily full pin Python in integration test CI workflow
  .github/workflows/test-go-integration-task.yml
Labels: type: bug, topic: infrastructure

#1448 Correct typo in mdns-discovery archive checksum
  commands/bundled_tools_mdns_discovery.go
Labels: type: bug, architecture: armv6, architecture: arm, topic: code

#1431 POC Dynamic shell completion for fqbn flag
  cli/compile/compile.go
  cli/completion/completion.go
  i18n/data/en.po
  i18n/rice-box.go
  test/test_completion.py
Labels: type: enhancement, topic: CLI, topic: code

#1458 [skip changelog] Fully document library layouts in specification
  docs/img/library-layout.dot
  docs/img/library-layout.svg
  docs/library-specification.md
Labels: type: enhancement, topic: documentation

#1460 Fix gRPC BoardListWatch crashing when installing/uninstalling a core/lib
  arduino/discovery/discovery.go
  arduino/discovery/discoverymanager/discoverymanager.go
  commands/board/list.go
  commands/daemon/daemon.go
  i18n/data/en.po
  i18n/rice-box.go
Labels: type: imperfection

#1463 [skip changelog] Add workflow and repo dispatch triggers to stats collection workflows
  .github/workflows/arduino-stats.yaml
  .github/workflows/github-stats.yaml
Labels: type: enhancement, topic: infrastructure

#1462 Fix an issue with arduino-cli lib install stripping too many characters from library names in git URLs
  arduino/libraries/librariesmanager/install.go
Labels: topic: code, type: bug

#1464 [skip changelog] Add unit test for lib install from git url
  arduino/libraries/librariesmanager/install.go
  arduino/libraries/librariesmanager/install_test.go
  i18n/data/en.po
  i18n/rice-box.go
Labels: topic: testing

#1466 Fix library verification when installing from git repo or zip file
  arduino/globals/globals.go
  arduino/libraries/libraries.go
  arduino/libraries/librariesmanager/install.go
  arduino/libraries/librariesmanager/install_test.go
  i18n/data/en.po
  i18n/rice-box.go
  test/test_lib.py
Labels: type: bug, topic: CLI, topic: gRPC

#1470 [skip changelog] Fix integration tests by setting a maximum python version
  poetry.lock
  pyproject.toml
Labels: topic: infrastructure

#1476 [skip changelog] Update workflow and script to fetch Arduino CDN download data
  .github/tools/fetch_athena_stats.py
  .github/tools/fetch_athena_stats.sh
  .github/workflows/arduino-stats.yaml
Labels: topic: infrastructure

#1477 [skip changelog] Add missing partitioning query in Athena script
  .github/tools/fetch_athena_stats.py
Labels: topic: infrastructure

#1478 [skip changelog] Temporarily full pin Python in all GitHub Actions workflows
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
Labels: topic: infrastructure, type: imperfection

#1479 [skip changelog] Fix lib install crash on nightlies
  cli/lib/install.go
  i18n/data/en.po
  i18n/rice-box.go
Labels: topic: CLI, type: bug
