Repository arduino/arduino-cli, pull requests merged in 2021-03, with the labels that each got.

#1202 Redirect pre-versioning docs website URLs to latest
  CONTRIBUTING/index.html
  FAQ/index.html
  commands/arduino-cli/index.html
  commands/arduino-cli_board/index.html
  commands/arduino-cli_board_attach/index.html
  commands/arduino-cli_board_details/index.html
  commands/arduino-cli_board_list/index.html
  commands/arduino-cli_board_listall/index.html
  commands/arduino-cli_cache/index.html
  commands/arduino-cli_cache_clean/index.html
  commands/arduino-cli_compile/index.html
  commands/arduino-cli_config/index.html
  commands/arduino-cli_config_dump/index.html
  commands/arduino-cli_config_init/index.html
  commands/arduino-cli_core/index.html
  commands/arduino-cli_core_download/index.html
  commands/arduino-cli_core_install/index.html
  commands/arduino-cli_core_list/index.html
  commands/arduino-cli_core_search/index.html
  commands/arduino-cli_core_uninstall/index.html
  commands/arduino-cli_core_update-index/index.html
  commands/arduino-cli_core_upgrade/index.html
  commands/arduino-cli_daemon/index.html
  commands/arduino-cli_debug/index.html
  commands/arduino-cli_lib/index.html
  commands/arduino-cli_lib_deps/index.html
  commands/arduino-cli_lib_download/index.html
  commands/arduino-cli_lib_install/index.html
  commands/arduino-cli_lib_list/index.html
  commands/arduino-cli_lib_search/index.html
  commands/arduino-cli_lib_uninstall/index.html
  commands/arduino-cli_lib_update-index/index.html
  commands/arduino-cli_lib_upgrade/index.html
  commands/arduino-cli_sketch/index.html
  commands/arduino-cli_sketch_new/index.html
  commands/arduino-cli_upload/index.html
  commands/arduino-cli_version/index.html
  getting-started/index.html
  installation/index.html
  library-specification/index.html
  package_index_json-specification/index.html
  platform-specification/index.html
  rpc/commands/index.html
  rpc/debug/index.html
  rpc/monitor/index.html
  rpc/settings/index.html
  sketch-build-process/index.html
  sketch-specification/index.html
Labels: component/docs

#1205 Add fuzzy search to board listall and more information in its json output
  commands/board/listall.go
  rpc/commands/board.pb.go
  rpc/commands/board.proto
  rpc/commands/common.pb.go
  rpc/commands/common.proto
  rpc/commands/core.pb.go
  rpc/commands/core.proto
  test/test_board.py
Labels: component/CLI, component/gRPC, component/testing

#1209 [skip changelog] Fix core integration tests
  test/test_core.py
Labels: component/testing

#1210 Add board search command and gRPC interface function
  arduino/utils/search.go
  cli/board/board.go
  cli/board/search.go
  client_example/go.sum
  client_example/main.go
  commands/board/search.go
  commands/daemon/daemon.go
  rpc/commands/board.pb.go
  rpc/commands/board.proto
  rpc/commands/commands.pb.go
  rpc/commands/commands.proto
  test/test_board.py
Labels: topic: CLI, topic: gRPC

#1216 Add serial number of connected board to board details command
  cli/board/list.go
  commands/board/list.go
  go.sum
  rpc/commands/board.pb.go
  rpc/commands/board.proto
Labels: topic: CLI, topic: gRPC

#1214 Add overwrite option to zip and git lib install for gRPC interface
  arduino/libraries/librariesmanager/install.go
  cli/lib/install.go
  commands/lib/install.go
  rpc/commands/lib.pb.go
  rpc/commands/lib.proto
Labels: topic: gRPC

#1222 Enhanced search logic of board listall, core search and lib search
  commands/board/listall.go
  commands/core/search.go
  commands/lib/search.go
  commands/lib/search_test.go
  go.mod
  go.sum
  test/test_board.py
  test/test_core.py
  test/test_lib.py
Labels: topic: CLI, topic: gRPC

#1219 Fix core upgrading not uninstalling unused tools
  commands/core/install.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  commands/instances.go
  test/test_core.py
  test/test_upgrade.py
Labels: topic: CLI, topic: core, topic: gRPC, type: bug

#1226 [skip changelog] Update "stale bot" GHA workflow to use new enabling label
  .github/workflows/stale.yaml
Labels: priority: low, topic: infrastructure, type: bug

#1228 Fix OS X metadata folder not ignored when installing lib from zip
  arduino/libraries/librariesmanager/install.go
  test/test_lib.py
  test/testdata/fake-lib.zip
Labels: topic: CLI, topic: gRPC, type: bug

#1230 Fix core name not showing if installed.json is not found
  arduino/cores/packagemanager/loader.go
  test/test_core.py
Labels: topic: CLI, topic: core, topic: gRPC, type: bug

#1231 Fix casing of assembly sketch files
  arduino/builder/sketch.go
  arduino/globals/globals.go
  arduino/sketch/sketch.go
  legacy/builder/builder.go
  legacy/builder/create_cmake_rule.go
Labels: topic: CLI, type: bug

#1235 Add support for json, adoc and md sketch files extensions
  arduino/builder/sketch_test.go
  arduino/builder/testdata/TestSketchWithMarkdownAsciidocJson/TestSketchWithMarkdownAsciidocJson.ino
  arduino/builder/testdata/TestSketchWithMarkdownAsciidocJson/foo.adoc
  arduino/builder/testdata/TestSketchWithMarkdownAsciidocJson/foo.json
  arduino/builder/testdata/TestSketchWithMarkdownAsciidocJson/foo.md
  arduino/globals/globals.go
  arduino/sketch/sketch_test.go
  arduino/sketch/testdata/SketchWithMarkdownAsciidocJson/SketchWithMarkdownAsciidocJson.ino
  arduino/sketch/testdata/SketchWithMarkdownAsciidocJson/foo.adoc
  arduino/sketch/testdata/SketchWithMarkdownAsciidocJson/foo.json
  arduino/sketch/testdata/SketchWithMarkdownAsciidocJson/foo.md
Labels: topic: gRPC, type: enhancement

#1234 Add library validation step when installing from zip or git
  arduino/libraries/librariesmanager/install.go
  test/conftest.py
  test/test_lib.py
  test/testdata/fake-lib.zip
  test/testdata/lib-without-header.zip
  test/testdata/lib-without-properties.zip
Labels: topic: CLI, topic: gRPC, type: enhancement

#1237 Change `core search` to update indexes only after 24h from last edit
  cli/core/search.go
  test/test_core.py
Labels: topic: CLI
