Repository arduino/arduino-cli, pull requests merged in 2021-12, with the labels that each got.

#1578 Enhance `i18n:check` task
  .github/workflows/check-i18n-task.yml
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure, type: imperfection

#1579 Update Python version in integration tests
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-python-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  poetry.lock
  pyproject.toml
Labels: topic: infrastructure, type: imperfection

#1582 [skip-changelog] Revert "Pin task version to 3.9.0 because of the PATH on win bug (#1576)"
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, os: windows, topic: infrastructure

#1580 Fix `lib upgrade` trying to upgrade core bundled libraries
  commands/lib/upgrade.go
  test/test_lib.py
  test/testdata/platform_with_bundled_library/boards.txt
  test/testdata/platform_with_bundled_library/libraries/USBHost/library.properties
  test/testdata/platform_with_bundled_library/platform.txt
Labels: topic: code, type: imperfection

#1581 Add board autodetection on upload
  arduino/errors.go
  cli/compile/compile.go
  cli/upload/upload.go
  commands/upload/upload.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.proto
  test/test_compile_part_4.py
  test/test_upload.py
Labels: type: enhancement, topic: code, topic: CLI, topic: gRPC

#1585 Add json output to daemon command
  cli/daemon/daemon.go
Labels: type: enhancement, topic: code, topic: CLI

#1602 [skip changelog] Use major version ref of `carlosperate/download-file-action`
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure

#1603 Fix install script's check for previous installation
  install.sh
Labels: topic: infrastructure, type: imperfection

#1604 Bugfix: apply monitor settings on monitor opening
  commands/monitor/monitor.go
Labels: topic: code, type: imperfection

#1574 Optimize `core` operations, improving on the user input
  arduino/errors.go
  cli/arguments/reference.go
  cli/arguments/reference_test.go
  cli/core/download.go
  cli/core/install.go
  cli/core/uninstall.go
  cli/core/upgrade.go
  docs/UPGRADING.md
  test/test_core.py
Labels: type: enhancement, topic: code, criticality: low
