Repository arduino/arduino-cli, pull requests merged in 2022-10, with the labels that each got.

#1901 [skip changelog] Fix pull request template markup
  .github/PULL_REQUEST_TEMPLATE.md
Labels: topic: infrastructure, type: imperfection

#1903 Let `board listall` return boards sorted with the same order as in the original `boards.txt`
  arduino/cores/cores.go
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/package_manager_test.go
  commands/board/listall.go
  internal/integrationtest/board/board_list_test.go
Labels: type: enhancement, priority: medium, topic: code, criticality: medium

#1900 [skip changelog] Use appropriate name for field that stores library folder name
  arduino/libraries/libraries.go
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
  arduino/libraries/loader.go
  docs/UPGRADING.md
  internal/integrationtest/lib/lib_test.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/phases/libraries_builder.go
  legacy/builder/types/types.go
Labels: topic: code, type: imperfection

#1904 Made `core search` results more similar to Arduino IDE 1.8.x search dialog
  arduino/utils/search.go
  commands/core/search.go
  commands/lib/search.go
Labels: type: enhancement, priority: medium, topic: code, criticality: medium

#1890 [breaking] Removed `real_name` field from gRPC Library message
  arduino/libraries/libraries.go
  cli/lib/list.go
  docs/UPGRADING.md
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: type: enhancement, topic: code, topic: CLI, topic: gRPC

#1875 [breaking] Refactor `DownloadProgress` gRPC message: more clear field meaning.
  arduino/cores/packagemanager/download.go
  arduino/httpclient/httpclient.go
  arduino/resources/download.go
  cli/core/search.go
  cli/core/update_index.go
  cli/instance/instance.go
  cli/output/rpc_progress.go
  cli/update/update.go
  commands/daemon/daemon.go
  commands/instances.go
  docs/UPGRADING.md
  internal/integrationtest/daemon/daemon_core_test.go
  internal/integrationtest/daemon/download_progress_test.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/common.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  test/test_core.py
  test/test_update.py
Labels: type: enhancement, priority: medium, topic: gRPC, criticality: low

#1898 [skip-changelog] Migrate tests from `test_config.py` to `config_test.go`
  internal/integrationtest/config/config_test.go
  test/test_config.py
Labels: type: enhancement, topic: infrastructure

#1911 [skip-changelog] Some integration test refactorings
  Taskfile.yml
  arduino/discovery/discovery_client/go.sum
  client_example/go.sum
  docsgen/go.sum
  go.mod
  go.sum
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/cache/cache_test.go
  internal/integrationtest/config/config_test.go
  internal/integrationtest/daemon/daemon_test.go
  internal/integrationtest/environment.go
  internal/integrationtest/http_server.go
  internal/integrationtest/main/main_test.go
  internal/integrationtest/shared_directory.go
Labels: type: enhancement, priority: low, topic: infrastructure, criticality: low

#1913 [skip-changelog] Reuse already installed platforms to speed up integration tests
  internal/integrationtest/compile/compile_part_1_test.go
  internal/integrationtest/compile/compile_part_2_test.go
  internal/integrationtest/debug/debug_test.go
  internal/integrationtest/subtests.go
Labels: type: enhancement, priority: high, topic: infrastructure, criticality: low

#1847 [skip-changelog] Migrate tests from `test_board.py` to `board_test.go`
  internal/integrationtest/board/board_test.go
  test/test_board.py
Labels: type: enhancement, topic: infrastructure

#1915 [skip changelog] Move upload of coverage data to dedicated job in test workflow
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#1916 [skip-changelog] Added missing docs for 'recipe.hooks.prebuild.NUMBER.pattern'
  docs/platform-specification.md
Labels: type: enhancement, topic: documentation, priority: low, criticality: low

#1918 [skip-changelog] Fix copySketch testsuite function
  internal/integrationtest/arduino-cli.go
Labels: topic: infrastructure, type: imperfection

#1899 Add windows `.msi` installer to the CI
  .github/workflows/check-certificates.yml
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
  .prettierignore
  Taskfile.yml
  docs/installation.md
  installer/cli.wixproj
  installer/cli.wxs
  installer/ui.wxs
Labels: type: enhancement, os: windows, topic: packaging

#1927 [skip-changelog] fix `check-certificates.yml` failing
  .github/workflows/check-certificates.yml
Labels: topic: infrastructure

#1929 [skip-changelog] Update labels.yml
  .github/label-configuration-files/labels.yml
Labels: type: enhancement, topic: infrastructure

#1936 [skip-changelog] Add function to spawn a server that responds with error code
  internal/integrationtest/http_server.go
Labels: type: enhancement, topic: infrastructure

#1937 [skip-changelog] Add ARMv6 download links to install docs
  docs/installation.md
Labels: type: enhancement, topic: documentation

#1891 [breaking] Removed redundant and useless commands from gRPC API
  cli/core/install.go
  cli/core/list.go
  cli/core/search.go
  cli/core/update_index.go
  cli/core/upgrade.go
  cli/instance/instance.go
  cli/lib/list.go
  cli/lib/search.go
  cli/lib/update_index.go
  cli/lib/upgrade.go
  cli/outdated/outdated.go
  cli/update/update.go
  cli/upgrade/upgrade.go
  commands/daemon/daemon.go
  commands/instances.go
  commands/outdated/outdated.go
  commands/upgrade/upgrade.go
  docs/UPGRADING.md
  internal/integrationtest/outdated/outdated_test.go
  internal/integrationtest/update/update_test.go
  internal/integrationtest/upgrade/upgrade_test.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  test/test_lib.py
Labels: type: enhancement, priority: high, topic: gRPC, criticality: low

#1940 [skip changelog] Migrate workflows from deprecated `set-output` commands
  .github/workflows/check-certificates.yml
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release-go-task.yml
  .github/workflows/sync-labels.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: topic: infrastructure, type: imperfection

#1931 Add task to collect proto files and add steps to release them with tester, nightly and stable builds
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release-go-task.yml
  Taskfile.yml
Labels: type: enhancement, priority: medium, topic: infrastructure, criticality: low

#1954 Update search.go
  cli/lib/search.go
Labels: topic: code, type: imperfection

#1952 Allow `locale` key to be used in `config ...` commands.
  cli/config/validate.go
  docs/configuration.md
Labels: topic: code, type: imperfection

#1958 [skip changelog] Document filter setting capability of Library/Boards Manager links
  docs/sketch-specification.md
Labels: type: enhancement, topic: documentation
