Repository arduino/arduino-cli, pull requests merged in 2022-02, with the labels that each got.

#1211 Added support for advanced sketch "size" command
  docs/platform-specification.md
  legacy/builder/constants/constants.go
  legacy/builder/merge_sketch_with_bootloader.go
  legacy/builder/phases/sizer.go
  legacy/builder/types/context.go
Labels: type: enhancement, topic: code, criticality: medium

#1648 Added deprecation warning for gRPC MonitorService
  rpc/cc/arduino/cli/monitor/v1/monitor.pb.go
  rpc/cc/arduino/cli/monitor/v1/monitor.proto
  rpc/cc/arduino/cli/monitor/v1/monitor_grpc.pb.go
Labels: type: enhancement, topic: documentation, topic: gRPC

#1647 Sample command to solve compile or upload issue is now shown to CLI users
  cli/compile/compile.go
  cli/upload/upload.go
  commands/upload/upload.go
  test/test_compile_part_4.py
Labels: type: enhancement, topic: CLI

#1651 Add ip flag to daemon command
  cli/daemon/daemon.go
Labels: type: enhancement

#1655 [skip changelog] Update UPGRADING.md for 0.21.0
  docs/UPGRADING.md
Labels: topic: documentation

#1668 board list now returns partial results in case of errors
  cli/board/list.go
  commands/board/list.go
Labels: type: enhancement, topic: code

#1667 Discoveries are now closed and unregistered after failure
  arduino/discovery/discovery.go
  arduino/discovery/discovery_client/main.go
  arduino/discovery/discoverymanager/discoverymanager.go
  commands/board/list.go
Labels: type: enhancement, topic: code

#1670 Fix a couple memory leaks caused by unclosed file handles
  arduino/security/signatures.go
  i18n/cmd/po/parser.go
Labels: topic: code, type: imperfection

#1672 Fix error being printed in index parsing during first start
  cli/instance/instance.go
Labels: topic: code, type: imperfection
