Repository arduino/arduino-cli, pull requests merged in 2022-11, with the labels that each got.

#1962 Added libraries `.development` flag detection
  arduino/libraries/libraries.go
  arduino/libraries/libraries_test.go
  arduino/libraries/loader.go
  arduino/libraries/testdata/TestLib/library.properties
  arduino/libraries/testdata/TestLib/src/TestLib.h
  arduino/libraries/testdata/TestLibInDev/.development
  arduino/libraries/testdata/TestLibInDev/library.properties
  arduino/libraries/testdata/TestLibInDev/src/TestLib.h
  docs/library-specification.md
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: type: enhancement, topic: code

#1953 [skip-changelog] Run integration tests concurrently
  .github/workflows/test-go-task.yml
  Taskfile.yml
  internal/integrationtest/board/board_list_test.go
  internal/integrationtest/board/board_test.go
  internal/integrationtest/compile/compile_part_2_test.go
  internal/integrationtest/compile/compile_part_3_test.go
  internal/integrationtest/compile/compile_test.go
  internal/integrationtest/core/core_list_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/daemon/daemon_board_watch_test.go
  internal/integrationtest/daemon/daemon_compile_test.go
  internal/integrationtest/daemon/daemon_core_test.go
  internal/integrationtest/daemon/daemon_lib_install_test.go
  internal/integrationtest/daemon/daemon_test.go
Labels: type: enhancement, topic: infrastructure

#1921 [skip-changelog] Migrate tests from `test_sketch.py` to `sketch_test.go`
  internal/integrationtest/sketch/sketch_test.go
  internal/integrationtest/testdata/sketch_multiple_main_files/sketch_multiple_main_files.ino
  internal/integrationtest/testdata/sketch_multiple_main_files/sketch_multiple_main_files.pde
  internal/integrationtest/testdata/sketch_pde_main_file/sketch_pde_main_file.pde
  internal/integrationtest/testdata/sketch_simple/build/adafruit.samd.adafruit_feather_m0/sketch_simple.ino.hex
  internal/integrationtest/testdata/sketch_simple/build/adafruit.samd.adafruit_feather_m0/sketch_simple.ino.map
  internal/integrationtest/testdata/sketch_simple/build/arduino.avr.uno/sketch_simple.ino.eep
  internal/integrationtest/testdata/sketch_simple/build/arduino.avr.uno/sketch_simple.ino.hex
  internal/integrationtest/testdata/sketch_simple/build/arduino.avr.uno/sketch_simple.ino.with_bootloader.hex
  internal/integrationtest/testdata/sketch_simple/doc.txt
  internal/integrationtest/testdata/sketch_simple/header.h
  internal/integrationtest/testdata/sketch_simple/merged_sketch.txt
  internal/integrationtest/testdata/sketch_simple/old.pde
  internal/integrationtest/testdata/sketch_simple/other.ino
  internal/integrationtest/testdata/sketch_simple/s_file.S
  internal/integrationtest/testdata/sketch_simple/sketch_simple.ino
  internal/integrationtest/testdata/sketch_simple/src/helper.h
  test/test_sketch.py
Labels: type: enhancement, topic: infrastructure

#1966 [skip changelog] Update all mentions of Arduino Pro IDE
  docs/integration-options.md
  docs/library-specification.md
  docs/package_index_json-specification.md
  docs/platform-specification.md
Labels: topic: documentation, type: imperfection

#1967 Fixed integration test `TestLibInstallMultipleSameLibrary`
  internal/integrationtest/lib/lib_test.go
Labels: priority: high, topic: infrastructure, type: imperfection, criticality: highest

#1969 Allow ISO8859-1 (non UTF-8) `.properties` files.
  .licenses/go/github.com/arduino/go-properties-orderedmap.dep.yml
  arduino/discovery/discovery_client/go.mod
  arduino/discovery/discovery_client/go.sum
  arduino/libraries/libraries_test.go
  arduino/libraries/testdata/LibWithNonUTF8Properties/library.properties
  arduino/libraries/testdata/LibWithNonUTF8Properties/src/LibWithNonUTF8Properties.h
  client_example/go.sum
  docsgen/go.mod
  docsgen/go.sum
  go.mod
  go.sum
Labels: priority: low, topic: code, type: imperfection, criticality: low

#1972 Fix concurrency problem in `Board.buildConfigOptionsStructures`
  arduino/cores/board.go
Labels: priority: high, topic: code, type: imperfection, criticality: high

#1975 `lib search` returns exact match as the first result.
  cli/lib/search.go
  commands/lib/search.go
  commands/lib/search_test.go
Labels: type: enhancement, priority: low, topic: code, criticality: medium

#1924 [skip-changelog] Migrate tests from `test_compile_part_4.py` to `compile_part_4_test.go`
  internal/integrationtest/compile/compile_test.go
  internal/integrationtest/testdata/platform_with_secure_boot/boards.local.txt
  internal/integrationtest/testdata/platform_with_secure_boot/platform.local.txt
  internal/integrationtest/testdata/sketch_with_conflicting_libraries_include/sketch_with_conflicting_libraries_include.ino
  internal/integrationtest/testdata/sketch_with_ipp_file_include/sketch_with_ipp_file_include.ino
  internal/integrationtest/testdata/sketch_with_ipp_file_include/template.ipp
  internal/integrationtest/testdata/sketch_with_missing_include/sketch_with_missing_include.ino
  internal/integrationtest/testdata/sketch_with_sd_library/sketch_with_sd_library.ino
  internal/integrationtest/testdata/sketch_with_tpp_file_include/sketch_with_tpp_file_include.ino
  internal/integrationtest/testdata/sketch_with_tpp_file_include/template.tpp
  test/test_compile_part_4.py
Labels: type: enhancement, topic: infrastructure

#1949 [skip-changelog] Migrate tests from `test_core.py` to `core_test.go`
  internal/integrationtest/core/core_test.go
  internal/integrationtest/testdata/installed.json
  internal/integrationtest/testdata/platform_with_missing_custom_board_options/boards.txt
  internal/integrationtest/testdata/platform_with_missing_custom_board_options/platform.txt
  test/test_core.py
  test/testdata/installed.json
Labels: type: enhancement, topic: infrastructure

#1979 Split `compile` integration tests in two parts
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/compile_2/compile_test.go
Labels: type: enhancement, priority: high, topic: infrastructure, criticality: low

#1978 Set `runtime.hardware.path` property during upload
  arduino/cores/cores.go
  internal/integrationtest/compile_2/compile_propeties_test.go
  internal/integrationtest/testdata/bare_minimum/bare_minimum.ino
  internal/integrationtest/testdata/foo/avr/boards.txt
  internal/integrationtest/testdata/foo/avr/platform.txt
Labels: priority: medium, topic: code, type: imperfection, criticality: medium

#1980 Fix download progress bar (not always displayed)
  cli/output/rpc_progress.go
Labels: priority: low, type: imperfection, topic: CLI, criticality: low

#1982 Improve `board list` detection via cloud API
  commands/board/list.go
  commands/board/list_test.go
  inventory/inventory.go
Labels: type: enhancement, priority: high, topic: code, criticality: high

#1976 [skip-changelog] Migrate tests from `test_upload_mock.py` to `upload_mock_test.go`
  internal/integrationtest/upload_mock/upload_mock_test.go
  test/test_upload_mock.py
Labels: type: enhancement, topic: infrastructure

#1991 Small change in upload message
  commands/upload/upload.go
  internal/integrationtest/upload_mock/upload_mock_test.go
Labels: type: enhancement, priority: high, topic: code, criticality: low

#1983 [breaking] Fixed detection of double-install using `lib install` with `--git-url` or `--zip-path`
  arduino/libraries/librariesmanager/install.go
  arduino/libraries/librariesmanager/librariesmanager.go
  commands/lib/install.go
  docs/UPGRADING.md
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/lib/lib_test.go
Labels: priority: high, topic: code, type: imperfection, criticality: medium

#1993 Fix `sketch new` default overwriting behavior
  cli/sketch/new.go
  commands/sketch/new.go
  internal/integrationtest/sketch/sketch_test.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/debug/v1/debug.pb.go
Labels: topic: code, type: imperfection

#1994 Enable `sketch archive` overrides using `overwrite` flag
  cli/sketch/archive.go
  commands/sketch/archive.go
  internal/integrationtest/sketch/sketch_test.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
Labels: topic: code, type: imperfection
