Repository arduino/arduino-cli, pull requests merged in 2022-09, with the labels that each got.

#1844 [skip-changelog] Migrate tests from `test_completion.py` to `completion_test.go`
  internal/integrationtest/completion/completion_test.go
  test/test_completion.py
Labels: type: enhancement, topic: infrastructure

#1817 [breaking] Remove auto detection of Arduino IDE built-in libraries and tools / Allow gRPC install of built-in libraries
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/libraries/libraries_location.go
  arduino/libraries/librariesmanager/install.go
  arduino/libraries/librariesmanager/librariesmanager.go
  cli/cache/clean.go
  cli/cli.go
  cli/config/validate.go
  cli/core/search.go
  cli/daemon/daemon.go
  cli/instance/instance.go
  commands/compile/compile.go
  commands/instances.go
  commands/lib/install.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
  configuration/configuration.go
  configuration/directories.go
  docs/UPGRADING.md
  docs/configuration.md
  docs/sketch-build-process.md
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_lib_install_test.go
  legacy/builder/libraries_loader.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/ctags_runner_test.go
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/prototypes_adder_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/types/context.go
  legacy/builder/types/context_test.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: type: enhancement, priority: medium, topic: CLI, criticality: low

#1857 [breaking] Simplified gRPC streams helpers
  commands/daemon/daemon.go
  commands/daemon/debug.go
  commands/daemon/stream.go
  docs/UPGRADING.md
Labels: type: enhancement, topic: code, topic: gRPC

#1840 [skip-changelog] Migrate tests from `test_debug.py` to `debug_test.go`
  internal/integrationtest/debug/debug_test.go
  test/test_debug.py
Labels: type: enhancement, topic: infrastructure

#1855 Extended Pluggable Monitor specification to allow board-specific settings to be applied
  arduino/cores/board.go
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/loader_test.go
  commands/monitor/monitor.go
  commands/monitor/settings.go
  docs/platform-specification.md
Labels: topic: code

#1841 [skip-changelog] Migrate tests from `test_outdated.py` to `outdated_test.go`
  internal/integrationtest/outdated/outdated_test.go
  test/test_outdated.py
Labels: type: enhancement, topic: infrastructure

#1859 [skip-changelog] Migrate tests from `test_upgrade.py` to `upgrade_test.go`
  internal/integrationtest/upgrade/upgrade_test.go
  test/test_upgrade.py
Labels: type: enhancement, topic: infrastructure

#1862 [skip-changelog] Proper handling of stdout/stderr copy in subprocess
  executils/process.go
  internal/integrationtest/arduino-cli.go
Labels: topic: infrastructure, type: imperfection

#1867 Fixed `compile` regression
  legacy/builder/hardware_loader.go
  legacy/builder/test/tools_loader_test.go
Labels: priority: high, topic: code, type: imperfection, criticality: highest

#1866 [breaking] `core update-index` do not stop at the first download error
  arduino/httpclient/httpclient.go
  cli/core/search.go
  cli/core/update_index.go
  cli/instance/instance.go
  cli/output/rpc_progress.go
  cli/update/update.go
  commands/daemon/daemon.go
  commands/instances.go
  docs/UPGRADING.md
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_core_test.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/common.go
  test/test_update.py
Labels: type: enhancement, priority: high, topic: CLI, topic: gRPC

#1873 testsuite: arduino-cli should never panic during tests
  internal/integrationtest/arduino-cli.go
Labels: priority: high, topic: infrastructure, type: imperfection, criticality: low

#1874 Fixed NPE on `lib upgrade` command
  arduino/discovery/discovery_client/go.sum
  client_example/go.sum
  commands/lib/upgrade.go
  docsgen/go.sum
  go.mod
  go.sum
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/lib/lib_test.go
Labels: priority: high, topic: code, type: imperfection, criticality: medium

#1879 [skip-changelog] Add CopySketch to the testsuite library
  internal/integrationtest/arduino-cli.go
Labels: type: enhancement, topic: infrastructure

#1858 [skip-changelog] Migrate tests from `test_profiles.py` to `profiles_test.go`
  internal/integrationtest/profiles/profiles_test.go
  internal/integrationtest/testdata/sketch_with_error_including_wire/sketch_with_error_including_wire.ino
  internal/integrationtest/testdata/sketch_with_profile/sketch.yaml
  internal/integrationtest/testdata/sketch_with_profile/sketch_with_profile.ino
  test/test_profiles.py
Labels: type: enhancement, topic: infrastructure

#1878 [breaking] Fix behaviour of `lib` commands when a library is installed multiple times
  arduino/errors.go
  arduino/libraries/libraries.go
  arduino/libraries/librariesindex/index.go
  arduino/libraries/librariesindex/index_test.go
  arduino/libraries/librarieslist.go
  arduino/libraries/librariesmanager/install.go
  arduino/libraries/librariesmanager/librariesmanager.go
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
  arduino/libraries/loader.go
  commands/lib/install.go
  commands/lib/list.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
  docs/UPGRADING.md
  internal/integrationtest/lib/lib_test.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/phases/libraries_builder.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/types/types.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: priority: high, topic: code, type: imperfection, criticality: medium

#1882 Do not treat custom menu options without label as 'malformed'
  arduino/cores/packagemanager/loader.go
  test/test_core.py
  test/testdata/platform_with_wrong_custom_board_options/boards.txt
  test/testdata/platform_with_wrong_custom_board_options/platform.txt
Labels: type: enhancement, priority: high, topic: code, criticality: high

#1861 [skip-changelog] Migrate tests from `test_compile_part_1.py` to `compile_part_1_test.go`
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/compile/compile_part_1_test.go
  internal/integrationtest/testdata/sketch_with_multiple_defines/sketch_with_multiple_defines.ino
  internal/integrationtest/testdata/sketch_with_multiple_int_defines/sketch_with_multiple_int_defines.ino
  internal/integrationtest/testdata/sketch_with_single_int_define/sketch_with_single_int_define.ino
  internal/integrationtest/testdata/sketch_with_single_string_define/sketch_with_single_string_define.ino
  test/test_compile_part_1.py
Labels: type: enhancement, topic: infrastructure

#1886 [skip-changelog] Set test environment directory as CLI WorkingDir
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/compile/compile_part_1_test.go
  internal/integrationtest/daemon/daemon_test.go
Labels: type: enhancement, topic: infrastructure

#1896 Improved library search
  commands/lib/search.go
  commands/lib/search_test.go
  commands/lib/testdata/library_index.json
  commands/lib/testdata/test1/library_index.json
Labels: priority: high, topic: code, type: imperfection, criticality: high

#1883 [skip-changelog] Use a matrix to create parallel builds for each OS
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release-go-task.yml
  DistTasks.yml
Labels: type: enhancement, topic: infrastructure
