Repository arduino/arduino-cli, pull requests merged in 2022-01, with the labels that each got.

#1622 Split daemon mode configs from core configs
  cli/cli.go
  cli/config/validate.go
  cli/daemon/daemon.go
  cli/daemon/settings.go
  cli/daemon/settings_test.go
  cli/daemon/testdata/daemon-config.yaml
  cli/globals/globals.go
  configuration/configuration_test.go
  configuration/defaults.go
  docs/UPGRADING.md
  docs/configuration.md
  docs/getting-started.md
  logging/logging.go
  output/output.go
  test/test_config.py
  test/test_daemon.py
Labels: type: enhancement, topic: documentation, topic: code, topic: CLI, topic: gRPC

#1398 Better detection of required serial port during upload.
  commands/upload/upload.go
Labels: topic: code

#1633 Allow case-insensitive `ok` or `OK` replies from pluggable discoveries and monitors
  arduino/discovery/discovery.go
  arduino/monitor/monitor.go
Labels: type: enhancement, topic: code

#1637 bugfix: Install pluggable monitor dependencies together with a platform
  arduino/cores/packagemanager/download.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/cores/packagemanager/testdata/package_tooltest_index.json
Labels: topic: code, type: imperfection, topic: CLI, criticality: high

#1641 Update i18n scripts to use Transifex REST API v3
  i18n/cmd/commands/transifex/pull_transifex.go
  i18n/cmd/commands/transifex/push_transifex.go
  i18n/cmd/commands/transifex/transifex.go
Labels: type: enhancement, topic: infrastructure

#1642 Add missing env var to i18n workflows
  .github/workflows/check-i18n-task.yml
  .github/workflows/i18n-nightly-push.yaml
  .github/workflows/i18n-weekly-pull.yaml
Labels: topic: infrastructure, type: imperfection

#1643 Update Go version in i18n workflows
  .github/workflows/check-i18n-task.yml
  .github/workflows/i18n-nightly-push.yaml
  .github/workflows/i18n-weekly-pull.yaml
Labels: topic: infrastructure, type: imperfection

#1645 Fix panic calling compile with wrong FQBN
  commands/compile/compile.go
  test/test_compile_part_4.py
Labels: topic: code, type: imperfection, topic: CLI

#1640 [breaking] Add env variable to let tools know the cli version and the gRPC client version
  arduino/cores/packagemanager/install_uninstall.go
  arduino/cores/packagemanager/loader_test.go
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/discovery/discovery.go
  arduino/discovery/discovery_test.go
  arduino/monitor/monitor.go
  arduino/monitor/monitor_test.go
  commands/board/list_test.go
  commands/daemon/daemon.go
  commands/debug/debug.go
  commands/debug/debug_test.go
  commands/instances.go
  commands/upload/upload.go
  commands/upload/upload_test.go
  docs/UPGRADING.md
  docs/platform-specification.md
  executils/process.go
  executils/process_test.go
  legacy/builder/builder_utils/utils.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/ctags_runner.go
  legacy/builder/gcc_preproc_runner.go
  legacy/builder/hardware_loader.go
  legacy/builder/phases/libraries_builder.go
  legacy/builder/phases/linker.go
  legacy/builder/phases/sizer.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/recipe_runner.go
Labels: type: enhancement, priority: medium, topic: CLI
