Repository arduino/arduino-cli, pull requests merged in 2022-07, with the labels that each got.

#1796 [skip-changelog] Try to whitelist CI for Cloudflare spam-check filters
  .github/workflows/test-go-integration-task.yml
  configuration/network.go
Labels: type: enhancement, topic: infrastructure, topic: code

#1793 Added `no_overwrite` flag in LibraryInstall
  cli/lib/install.go
  commands/lib/install.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
  rpc/cc/arduino/cli/commands/v1/monitor.pb.go
  test/test_lib.py
Labels: type: enhancement, topic: code

#1794 Add `--no-overwrite` flag in `core install`
  cli/core/install.go
  commands/core/install.go
  commands/core/upgrade.go
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/core.proto
  test/test_core.py
Labels: type: enhancement, topic: code

#1805 Fix path in error messages on sketch loading
  arduino/sketch/sketch.go
  arduino/sketch/sketch_test.go
  legacy/builder/container_setup.go
  test/test_compile_part_1.py
  test/test_compile_part_3.py
  test/test_sketch.py
  test/test_upload.py
Labels: topic: code, type: imperfection

#1810 Fix bogus "wrong file size" error in some rare cases
  arduino/resources/checksums.go
  commands/instances.go
Labels: type: imperfection, topic: CLI, criticality: high, criticality: highest

#1776 Allow using specific revisions in `lib install --git-url` (#1113)
  arduino/libraries/librariesmanager/install.go
  arduino/libraries/librariesmanager/install_test.go
  cli/lib/install.go
  test/test_lib.py
Labels: type: enhancement, topic: code

#1814 Fix regression: do not crash on `board list` if a discovery is not properly installed
  arduino/discovery/discovery.go
  test/test_board.py
Labels: type: imperfection, topic: CLI, criticality: high
