Repository arduino/arduino-cli, pull requests merged in 2022-03, with the labels that each got.

#1680 [docs] Make use of 'avr' as example platform more consistent
  docs/sketch-build-process.md
Labels: type: enhancement, topic: documentation

#1688 add flag to allow board options to be specified seperately from fqbn
  cli/arguments/fqbn.go
Labels: type: enhancement, topic: code, topic: CLI

#1567 Bump go version to go 1.17.8
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  DistTasks.yml
  arduino/discovery/discovery_client/go.mod
  arduino/discovery/discovery_client/go.sum
  client_example/go.mod
  docs/CONTRIBUTING.md
  docsgen/go.mod
  go.mod
Labels: type: enhancement, topic: infrastructure

#1686 Add secure boot support for compile command.
  cli/arguments/arguments.go
  cli/compile/compile.go
  commands/compile/compile.go
  docs/guides/secure-boot.md
  docs/platform-specification.md
  legacy/builder/setup_build_properties.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
  test/test_compile_part_4.py
  test/testdata/platform_with_secure_boot/boards.local.txt
  test/testdata/platform_with_secure_boot/platform.local.txt
Labels: type: enhancement, topic: code, topic: CLI, topic: gRPC

#1700 Some static-check fixes
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  arduino/cores/board.go
  arduino/cores/packageindex/index.go
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/status.go
  arduino/cores/tools.go
  arduino/libraries/librariesindex/json.go
  arduino/monitors/null.go
  arduino/resources/checksums.go
  arduino/resources/helpers.go
  arduino/resources/helpers_test.go
  arduino/sketch/sketch.go
  cli/feedback/feedback.go
  cli/globals/globals.go
  cli/lib/args.go
  cli/lib/search.go
  commands/core/search_test.go
  commands/daemon/monitor.go
  i18n/cmd/po/parser.go
Labels: topic: code, type: imperfection
