Repository arduino/arduino-cli, pull requests merged in 2022-06, with the labels that each got.

#1745 [breaking] Improved compile report / temporary support for profile creation
  arduino/cores/cores.go
  arduino/cores/packagemanager/profiles.go
  arduino/globals/globals.go
  cli/compile/compile.go
  cli/core/search.go
  cli/globals/globals.go
  commands/compile/compile.go
  commands/instances.go
  docs/UPGRADING.md
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
Labels: type: enhancement, topic: CLI, criticality: high

#1742 `Monitor` gRPC call now sends a 'success' message to notify open port
  commands/daemon/daemon.go
  rpc/cc/arduino/cli/commands/v1/monitor.pb.go
  rpc/cc/arduino/cli/commands/v1/monitor.proto
Labels: topic: code, type: imperfection, topic: gRPC, criticality: high

#1746 fix `arduino-cli outdated --format json` output
  cli/outdated/outdated.go
  test/test_upgrade.py
Labels: type: enhancement, topic: code, type: imperfection, topic: CLI

#1749 Fixed error in pluggable discovery spec
  docs/pluggable-discovery-specification.md
Labels: topic: documentation, topic: CLI, criticality: highest

#1748 Fixed pluggable monitor specification to match the de-facto implementation
  docs/pluggable-monitor-specification.md
Labels: topic: documentation, type: imperfection, topic: CLI, criticality: highest

#1757 Fixed LibraryLocation and LibraryLayout JSON encoder/decoders
  arduino/libraries/libraries_layout.go
  arduino/libraries/libraries_location.go
  arduino/libraries/libraries_test.go
Labels: type: imperfection, topic: CLI, criticality: high

#1758 Do library rescan on compile (if no profies are used)
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/profiles.go
  commands/compile/compile.go
Labels: priority: high, type: imperfection, topic: CLI, criticality: highest

#1751 disable CGO on every OS except macOS
  DistTasks.yml
Labels: type: enhancement, os: windows, os: linux, topic: packaging

#1764 Relax markdown link-check timeouts
  .markdown-link-check.json
Labels: topic: infrastructure

#1771 Clear gRPC Monitor request only after monitor successfully closes
  commands/daemon/daemon.go
Labels: topic: code, type: imperfection, topic: gRPC, criticality: highest

#1759 Rate limit the number of outgoing gRPC messages
  arduino/utils/stream.go
Labels: type: enhancement, topic: code, topic: gRPC

#1504 [breaking] Remove old gRPC Monitor service, in favor of new gRPC API based on pluggable monitor
  .licenses/go/google.golang.org/protobuf/encoding/protojson.dep.yml
  .licenses/go/google.golang.org/protobuf/internal/encoding/json.dep.yml
  .licenses/go/google.golang.org/protobuf/types/known/structpb.dep.yml
  Taskfile.yml
  arduino/monitors/null.go
  arduino/monitors/serial.go
  arduino/monitors/types.go
  cli/daemon/daemon.go
  commands/daemon/monitor.go
  docs/FAQ.md
  docs/UPGRADING.md
  mkdocs.yml
  rpc/cc/arduino/cli/monitor/v1/monitor.pb.go
  rpc/cc/arduino/cli/monitor/v1/monitor.proto
  rpc/cc/arduino/cli/monitor/v1/monitor_grpc.pb.go
Labels: type: enhancement, topic: code, topic: gRPC

#1781 [skip changelog] Restore globbing of nightly build artifact filename
  .github/workflows/publish-go-nightly-task.yml
Labels: os: macos, topic: infrastructure, type: imperfection

#1783 [skip changelog] Enable Codecov reports on pull requests
  .codecov.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure
