Repository arduino/arduino-cli, pull requests merged in 2022-04, with the labels that each got.

#1701 [skip changelog] Remove broken download stats workflow
  .github/tools/fetch_athena_stats.py
  .github/workflows/arduino-stats.yaml
Labels: topic: infrastructure, type: imperfection

#1702 [skip changelog] Remove unused GitHub release download stats workflow
  .github/workflows/github-stats.yaml
Labels: type: enhancement, topic: infrastructure

#1706 Fixed some weird behaviour in gRPC Monitor command
  arduino/monitor/monitor.go
  commands/daemon/daemon.go
  commands/daemon/term_example/main.go
  commands/monitor/monitor.go
Labels: priority: high, type: imperfection, topic: gRPC, criticality: high

#1697 [breaking] Refactoring of download subroutines
  arduino/cores/packagemanager/download.go
  arduino/httpclient/httpclient.go
  arduino/httpclient/httpclient_test.go
  arduino/resources/download.go
  arduino/resources/helpers.go
  arduino/resources/helpers_test.go
  arduino/resources/index.go
  arduino/resources/resources_test.go
  cli/output/rpc_progress.go
  cli/updater/updater.go
  commands/board/attach.go
  commands/board/list.go
  commands/bundled_tools.go
  commands/compile/compile.go
  commands/core/download.go
  commands/core/install.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  commands/download.go
  commands/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
  commands/progress.go
  configuration/network.go
  docs/UPGRADING.md
  httpclient/httpclient.go
  legacy/builder/types/context.go
  rpc/cc/arduino/cli/commands/v1/common.go
  test/test_core.py
  test/test_lib.py
  test/test_update.py
Labels: type: enhancement, topic: code

#1710 [skip-changelog] fix nav being left out form #1686
  mkdocs.yml
Labels: topic: documentation, type: imperfection

#1712 [skip changelog] Detect unused dependency license metadata files
  .github/workflows/check-go-dependencies-task.yml
Labels: topic: infrastructure, type: imperfection

#1711 Some small refactorings
  .licenses/go/go.bug.st/relaxed-semver.dep.yml
  arduino/cores/packagemanager/install_uninstall.go
  arduino/cores/packagemanager/loader.go
  arduino/discovery/discovery_client/go.sum
  arduino/resources/install.go
  client_example/go.sum
  docsgen/go.mod
  docsgen/go.sum
  go.mod
  go.sum
  legacy/builder/libraries_loader.go
Labels: type: enhancement, topic: code
