Repository arduino/arduino-cli, pull requests merged in 2022-12, with the labels that each got.

#1997 [skip-changelog] Eliminate empty lines produced by `board details -b`
  cli/board/details.go
  internal/integrationtest/board/board_test.go
Labels: type: imperfection, topic: CLI

#1998 [skip-changelog]Update `installed.json` with newer entries
  internal/integrationtest/testdata/installed.json
Labels: topic: code, type: imperfection

#1989 [skip-changelog] Migrate twelve tests from `test_lib.py` to `lib_test.go`
  internal/integrationtest/lib/lib_test.go
  test/test_lib.py
Labels: type: enhancement, topic: infrastructure

#1984 [skip-changelog] Avoid running publish-go-tester-task if tag is set
  .github/workflows/publish-go-tester-task.yml
Labels: topic: infrastructure, type: imperfection

#2002 [skip changelog] Restore certificate check compatibility w/ RC2-40-CBC encrypted PKS #12
  .github/workflows/check-certificates.yml
Labels: topic: infrastructure, type: imperfection

#2007 Let the integration-test workflows to choose the latest minor version of python
  .github/workflows/test-go-integration-task.yml
Labels: type: enhancement, priority: high, topic: infrastructure, criticality: highest

#2006 Some minor adjustments in the codebase
  .licenses/go/github.com/arduino/go-paths-helper.dep.yml
  .licenses/go/golang.org/x/crypto/ssh/terminal.dep.yml
  arduino/discovery/discovery_client/go.mod
  arduino/discovery/discovery_client/go.sum
  arduino/errors.go
  cli/arguments/user_fields.go
  cli/output/rpc_progress.go
  client_example/go.sum
  commands/upload/upload.go
  docsgen/go.mod
  docsgen/go.sum
  go.mod
  go.sum
Labels: type: enhancement, priority: low, topic: code, criticality: low

#1964 [skip-changelog] Migrate Lib tests for `test_lib.py` to `lib_test.go`
  internal/integrationtest/lib/lib_test.go
  internal/integrationtest/testdata/fake-lib.zip
  internal/integrationtest/testdata/lib-without-header.zip
  internal/integrationtest/testdata/lib-without-properties.zip
  internal/integrationtest/testdata/platform_with_bundled_library/boards.txt
  internal/integrationtest/testdata/platform_with_bundled_library/libraries/USBHost/library.properties
  internal/integrationtest/testdata/platform_with_bundled_library/platform.txt
  test/test_lib.py
Labels: type: enhancement, topic: infrastructure

#2001 [skip-changelog]Migrate tests from `upload_test.py` to `test_upload.go`
  internal/integrationtest/upload/upload_test.go
  test/test_upload.py
Labels: type: enhancement, topic: infrastructure

#2013 [skip-changelog] Update urls to prevent tests from failing
  arduino/resources/resources_test.go
  internal/integrationtest/core/core_test.go
Labels: topic: code, type: imperfection

#2014 Disable "fail fast" feature in "Test Go" workflow
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#2009 Add `Online Help` link to gRPC interface's `Platform`
  commands/core.go
  commands/core/search_test.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
Labels: type: enhancement, topic: code

#2000 Include platform bundled libs when `-b` flag is used
  commands/lib/list.go
  internal/integrationtest/lib/lib_test.go
Labels: type: enhancement, topic: code, criticality: medium
