Repository arduino/arduino-cli, pull requests merged in 2023-08, with the labels that each got.

#2256 Fixed integration test
  internal/integrationtest/testdata/installed.json
Labels: topic: infrastructure, type: imperfection

#2257 Fixed some error messages/warnings during index download
  arduino/cores/packagemanager/package_manager.go
  arduino/resources/index.go
  commands/instances.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
Labels: type: imperfection, topic: CLI, topic: gRPC

#2258 Add `--log` global flag as alias for `--verbose/-v`
  internal/cli/cli.go
Labels: type: enhancement, topic: CLI

#2260 docs: clarified how tools flavours are selected
  docs/package_index_json-specification.md
Labels: type: enhancement, topic: documentation

#2265 Fixed loading of Library given a non-absolute path
  arduino/libraries/libraries_test.go
  arduino/libraries/loader.go
Labels: topic: code, type: imperfection

#2268 regression: Fix property expansion of "recipe.preproc.macros"
  arduino/builder/preprocessor/gcc.go
Labels: priority: high, topic: code, type: imperfection, criticality: highest, topic: build-process

#2267 regression: hide include-not-found errors during library discovery
  internal/integrationtest/compile_3/compile_test.go
  internal/integrationtest/compile_3/testdata/using_Wire/using_Wire.ino
  legacy/builder/container_find_includes.go
Labels: priority: high, topic: code, type: imperfection, criticality: highest

#2253 feature: Detect board port change after upload
  arduino/discovery/discovery.go
  arduino/discovery/discovery_client/main.go
  commands/board/list.go
  commands/board/list_test.go
  commands/daemon/daemon.go
  commands/upload/burnbootloader.go
  commands/upload/upload.go
  commands/upload/upload_test.go
  docs/UPGRADING.md
  internal/algorithms/channels.go
  internal/cli/compile/compile.go
  internal/cli/upload/upload.go
  rpc/cc/arduino/cli/commands/v1/upload.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.proto
Labels: type: enhancement, priority: high, topic: code, topic: gRPC, criticality: highest

#2264 [skip-changelog] Add profiles to `LoadSketchResponse`
  commands/sketch/load.go
  commands/sketch/load_test.go
  commands/sketch/testdata/sketch_with_profile/sketch.yml
  commands/sketch/testdata/sketch_with_profile/sketch_with_profile.ino
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
Labels: type: enhancement, topic: code, topic: gRPC

#2273 Allow `.cxx` and `.cc` extension in compile
  arduino/globals/globals.go
  docs/platform-specification.md
  internal/integrationtest/compile_3/compile_cxx_cc_test.go
  internal/integrationtest/compile_3/testdata/sketch_with_cxx_cc/sketch_with_cxx_cc.ino
  internal/integrationtest/compile_3/testdata/sketch_with_cxx_cc/test.cc
  internal/integrationtest/compile_3/testdata/sketch_with_cxx_cc/test.cxx
  legacy/builder/builder_utils/utils.go
Labels: type: enhancement, topic: build-process

#2203 Add support for default build profile
  commands/compile/compile.go
  commands/upload/upload.go
  docs/sketch-project-file.md
  internal/cli/compile/compile.go
  internal/cli/upload/upload.go
  internal/integrationtest/profiles/profiles_test.go
  internal/integrationtest/testdata/sketch_with_default_profile/sketch.yaml
  internal/integrationtest/testdata/sketch_with_default_profile/sketch_with_default_profile.ino
  internal/integrationtest/testdata/sketch_without_default_profile/sketch.yaml
  internal/integrationtest/testdata/sketch_without_default_profile/sketch_without_default_profile.ino
Labels: type: enhancement, topic: code

#1766 Some refactorings on library resolution code
  legacy/builder/constants/constants.go
  legacy/builder/container_find_includes.go
  legacy/builder/fail_if_imported_library_is_wrong.go
  legacy/builder/types/types.go
Labels: type: enhancement, topic: code

#2282 legacy: removing a lot of duplicated/dead code
  legacy/builder/builder_utils/utils.go
  legacy/builder/container_find_includes.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/gohasissues/go_has_issues.go
  legacy/builder/phases/core_builder.go
  legacy/builder/test/helper_tools_downloader.go
  legacy/builder/test/wipeout_build_path_if_build_options_changed_test.go
  legacy/builder/utils/utils.go
  legacy/builder/wipeout_build_path_if_build_options_changed.go
Labels: type: enhancement, topic: code

#2288 Upload port detector improvements
  commands/upload/upload.go
Labels: topic: code, type: imperfection
