Repository arduino/arduino-cli, pull requests merged in 2023-03, with the labels that each got.

#2084 [skip-changelog] Handle repeated builds of a sketch when `--build-path` target is in the sketch directory
  commands/compile/compile.go
  internal/integrationtest/compile_3/compile_test.go
Labels: topic: code, type: imperfection

#2082 Refactored build-properties creation (and removed some legacy code)
  arduino/cores/board.go
  arduino/cores/board_test.go
  arduino/cores/cores.go
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/package_manager_test.go
  commands/compile/compile.go
  commands/upload/upload.go
  legacy/builder/builder.go
  legacy/builder/setup_build_properties.go
  legacy/builder/target_board_resolver.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/ctags_runner_test.go
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/load_vid_pid_specific_properties_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/prototypes_adder_test.go
  legacy/builder/test/setup_build_properties_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/target_board_resolver_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/types/context.go
  legacy/builder/types/context_test.go
Labels: topic: code, type: imperfection

#2091 [skip-changelog] Add hooks `hooks.savehex.presavehex` and `hooks.savehex.postsavehex`
  commands/compile/compile.go
Labels: type: enhancement, topic: code

#2092 [skip-changelog] Add remediation path when tool is not available for an OS
  arduino/cores/packagemanager/download.go
  arduino/cores/packagemanager/install_uninstall.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/testdata/test_index.json
Labels: type: enhancement, topic: code

#2099 [skip-changelog] Fix string indexing in `tool not available for the current os` error message
  arduino/cores/packagemanager/install_uninstall.go
Labels: topic: code, type: imperfection

#2101 Added machine-readable `IP:PORT` in text-mode daemon
  internal/cli/daemon/daemon.go
Labels: type: enhancement, topic: CLI

#2078 Fixed compiler output capture in JSON mode
  internal/integrationtest/compile_3/compile_test.go
  internal/integrationtest/compile_3/testdata/blink_with_wrong_cpp/blink_with_wrong_cpp.ino
  internal/integrationtest/compile_3/testdata/blink_with_wrong_cpp/wrong.cpp
  legacy/builder/builder.go
  legacy/builder/builder_utils/utils.go
  legacy/builder/container_find_includes.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/types/context.go
  legacy/builder/utils/utils.go
Labels: topic: code, type: imperfection

#2102 Added `--omit-releases-details` flag in `lib search`
  commands/lib/search.go
  internal/cli/lib/search.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: type: enhancement, topic: code, topic: CLI, topic: gRPC

#2105 Allow leading underscore in sketch filenames
  commands/sketch/new.go
  commands/sketch/new_test.go
  docs/sketch-specification.md
Labels: type: enhancement, topic: documentation, topic: code

#2100 Remove useless go.mod files in repo / Fix dependabot alerts
  .licenses/go/github.com/gizak/termui/v3.dep.yml
  .licenses/go/github.com/gizak/termui/v3/drawille.dep.yml
  .licenses/go/github.com/gizak/termui/v3/widgets.dep.yml
  .licenses/go/github.com/mitchellh/go-wordwrap.dep.yml
  .licenses/go/github.com/nsf/termbox-go.dep.yml
  .licenses/go/golang.org/x/crypto/blowfish.dep.yml
  .licenses/go/golang.org/x/crypto/cast5.dep.yml
  .licenses/go/golang.org/x/crypto/ed25519.dep.yml
  .licenses/go/golang.org/x/crypto/internal/alias.dep.yml
  .licenses/go/golang.org/x/crypto/openpgp.dep.yml
  .licenses/go/golang.org/x/crypto/openpgp/armor.dep.yml
  .licenses/go/golang.org/x/crypto/openpgp/elgamal.dep.yml
  .licenses/go/golang.org/x/crypto/openpgp/errors.dep.yml
  .licenses/go/golang.org/x/crypto/openpgp/packet.dep.yml
  .licenses/go/golang.org/x/crypto/openpgp/s2k.dep.yml
  .licenses/go/golang.org/x/crypto/ssh.dep.yml
  .licenses/go/golang.org/x/crypto/ssh/agent.dep.yml
  .licenses/go/golang.org/x/crypto/ssh/internal/bcrypt_pbkdf.dep.yml
  .licenses/go/golang.org/x/crypto/ssh/knownhosts.dep.yml
  .licenses/go/golang.org/x/net/context.dep.yml
  .licenses/go/golang.org/x/net/http2.dep.yml
  .licenses/go/golang.org/x/net/internal/socks.dep.yml
  .licenses/go/golang.org/x/net/internal/timeseries.dep.yml
  .licenses/go/golang.org/x/net/proxy.dep.yml
  .licenses/go/golang.org/x/net/trace.dep.yml
  .licenses/go/golang.org/x/sys/unix.dep.yml
  .licenses/go/golang.org/x/term.dep.yml
  .licenses/go/golang.org/x/text/runes.dep.yml
  arduino/discovery/discovery_client/go.mod
  arduino/discovery/discovery_client/go.sum
  arduino/discovery/discovery_client/main.go
  client_example/go.mod
  client_example/go.sum
  docsgen/go.mod
  docsgen/go.sum
  go.mod
  go.sum
Labels: type: enhancement, topic: infrastructure

#2062 fix: discovery cleanup and watchers continuity upon core install
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/discovery/discovery.go
  arduino/discovery/discoverymanager/discoverymanager.go
Labels: topic: code, type: imperfection

#2109 Removed no more needed checks to go sub-programs
  .github/workflows/check-go-task.yml
  .licensed.yml
Labels: type: enhancement, topic: infrastructure

#2112 Fixed a couple of (very rare) race conditions
  arduino/monitor/monitor_test.go
  executils/process.go
Labels: topic: code, type: imperfection

#2111 Fix invalid JSON and YAML outputs for `outdated` command
  docs/UPGRADING.md
  internal/cli/core/list.go
  internal/cli/lib/list.go
  internal/cli/outdated/outdated.go
  internal/integrationtest/outdated/outdated_test.go
  internal/integrationtest/update/update_test.go
  internal/integrationtest/upgrade/upgrade_test.go
Labels: type: imperfection, topic: CLI

#2118 [skip-changelog] Sync `check-markdown-task` with upstream version of the workflow
  .github/workflows/check-markdown-task.yml
  .gitignore
  .markdownlintignore
  Taskfile.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#2107 [skip-changelog] Recover from interrupted builtin tool installation
  arduino/cores/packagemanager/loader_test.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/cores/tools.go
  internal/integrationtest/board/board_test.go
Labels: topic: code, type: imperfection

#2113 [breaking] Fix: `lib list --fqbn` and `lib examples --fqbn` do not show platform bundled lib when lib of same name is installed globally
  arduino/libraries/libraries.go
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
  commands/lib/list.go
  docs/UPGRADING.md
  internal/cli/lib/list.go
  internal/integrationtest/lib/lib_test.go
Labels: topic: code, type: imperfection

#2116 Compile on freebsd
  executils/executils_freebsd.go
  i18n/detect_freebsd.go
Labels: type: enhancement, topic: code

#2121 [breaking] Remove legacy vid-pid build properties selector
  commands/compile/compile.go
  docs/UPGRADING.md
  internal/cli/compile/compile.go
  legacy/builder/constants/constants.go
  legacy/builder/container_setup.go
  legacy/builder/load_vid_pid_specific_properties.go
  legacy/builder/test/load_vid_pid_specific_properties_test.go
  legacy/builder/types/context.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
Labels: type: enhancement, topic: code

#2125 Made an integration test more reliable
  internal/integrationtest/core/core_test.go
Labels: topic: infrastructure, type: imperfection

#2123 Skip useless operations in legacy test
  legacy/builder/test/prototypes_adder_test.go
Labels: type: enhancement, topic: infrastructure

#2124 Removed legacy 'codecomplete' implementation.
  legacy/builder/preprocess_sketch.go
  legacy/builder/types/context.go
Labels: type: enhancement, topic: code

#2083 [skip-changelog] Exclude libraries with a missing `.h` file from `lib list`
  arduino/libraries/libraries_test.go
  arduino/libraries/loader.go
  arduino/libraries/testdata/LegacyLib/LegacyLib.h
  docs/library-specification.md
  internal/integrationtest/lib/lib_test.go
Labels: topic: code, type: imperfection

#2126 Use the correct library when a relative path is passed as `--library` value
  internal/cli/compile/compile.go
  internal/integrationtest/compile_3/compile_test.go
  internal/integrationtest/testdata/FooLib.zip
  internal/integrationtest/testdata/FooLib/ArduinoIoTCloud.cpp
  internal/integrationtest/testdata/FooLib/ArduinoIoTCloud.h
  internal/integrationtest/testdata/FooLib/FooLib.cpp
  internal/integrationtest/testdata/FooLib/FooLib.h
  internal/integrationtest/testdata/FooLib/examples/FooSketch/FooSketch.ino
Labels: topic: code, type: imperfection, topic: CLI

#2132 Remove legacy "rewrite-rules" feature
  arduino/cores/packagemanager/package_manager.go
  legacy/builder/add_additional_entries_to_context.go
  legacy/builder/add_missing_build_properties_from_parent_platform_txt_files.go
  legacy/builder/builder.go
  legacy/builder/constants/constants.go
  legacy/builder/container_setup.go
  legacy/builder/ctags/ctags_properties.go
  legacy/builder/ctags_runner.go
  legacy/builder/gcc_preproc_runner.go
  legacy/builder/hardware/platform.keys.rewrite.txt
  legacy/builder/platform_keys_rewrite_loader.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/rewrite_hardware_keys.go
  legacy/builder/test/hardware_loader_test.go
  legacy/builder/test/platform_keys_rewrite_loader_test.go
  legacy/builder/test/rewrite_hardware_keys_test.go
  legacy/builder/types/context.go
  legacy/builder/warn_about_platform_rewrites.go
Labels: type: enhancement, topic: code
