Repository arduino/arduino-cli, pull requests merged in 2023-01, with the labels that each got.

#2020 chore: prevent empty codecov report
  .github/workflows/test-go-task.yml
Labels: topic: infrastructure, type: imperfection

#2022 [skip-changelog] chore: fix codecov badge url
  README.md
Labels: type: imperfection

#2031 Store all temporary files under a single folder
  arduino/sketch/sketch.go
  arduino/sketch/sketch_test.go
  commands/compile/compile.go
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/compile_2/compile_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/upload_mock/upload_mock_test.go
Labels: type: enhancement, topic: code

#2012 Add support for `.xz` and `.zst` archive format
  .licenses/go/github.com/codeclysm/extract/v3.dep.yml
  .licenses/go/github.com/h2non/filetype.dep.yml
  .licenses/go/github.com/h2non/filetype/matchers.dep.yml
  .licenses/go/github.com/h2non/filetype/matchers/isobmff.dep.yml
  .licenses/go/github.com/h2non/filetype/types.dep.yml
  .licenses/go/github.com/klauspost/compress.dep.yml
  .licenses/go/github.com/klauspost/compress/fse.dep.yml
  .licenses/go/github.com/klauspost/compress/huff0.dep.yml
  .licenses/go/github.com/klauspost/compress/internal/cpuinfo.dep.yml
  .licenses/go/github.com/klauspost/compress/internal/snapref.dep.yml
  .licenses/go/github.com/klauspost/compress/zstd.dep.yml
  .licenses/go/github.com/klauspost/compress/zstd/internal/xxhash.dep.yml
  .licenses/go/github.com/ulikunitz/xz.dep.yml
  .licenses/go/github.com/ulikunitz/xz/internal/hash.dep.yml
  .licenses/go/github.com/ulikunitz/xz/internal/xlog.dep.yml
  .licenses/go/github.com/ulikunitz/xz/lzma.dep.yml
  docs/package_index_json-specification.md
  docsgen/go.mod
  docsgen/go.sum
  go.mod
  go.sum
Labels: type: enhancement, priority: low, topic: code, criticality: low

#2034 [skip-changelog] Add query parameters to urls generated by lib commands
  arduino/cores/packagemanager/download.go
  arduino/cores/packagemanager/profiles.go
  arduino/httpclient/httpclient.go
  arduino/resources/download.go
  arduino/resources/helpers_test.go
  arduino/resources/index.go
  arduino/resources/resources_test.go
  commands/daemon/daemon.go
  commands/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/upgrade.go
  internal/cli/lib/download.go
  internal/cli/lib/install.go
  internal/integrationtest/lib/lib_test.go
Labels: type: enhancement, topic: code

#2035 `compile --show-properties` now correctly output the result in text and JSON format
  commands/compile/compile.go
  internal/cli/compile/compile.go
  internal/cli/feedback/stdio.go
  internal/integrationtest/compile_3/compile_show_properties_test.go
  legacy/builder/builder.go
  legacy/builder/dump_build_properties.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
Labels: priority: high, type: imperfection, topic: CLI, topic: gRPC, criticality: low

#2036 [skip-changelog] Remove `queryParameter` where it is not needed
  commands/daemon/daemon.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/upgrade.go
  internal/cli/lib/download.go
  internal/cli/lib/install.go
  internal/integrationtest/lib/lib_test.go
Labels: topic: code, type: imperfection

#2037 fix: scan libraries on install
  arduino/libraries/librariesmanager/install.go
  arduino/libraries/librariesmanager/librariesmanager.go
  arduino/libraries/librariesmanager/librariesmanager_test.go
  internal/integrationtest/daemon/daemon_test.go
Labels: type: enhancement, topic: code, topic: gRPC

#2045 [breaking] Remove `ip` flag from daemon command
  docs/UPGRADING.md
  internal/cli/daemon/daemon.go
Labels: topic: security, topic: code

#2038 refactoring: Fixing legacy pathnames
  arduino/sketch/sketch.go
  arduino/sketch/sketch_test.go
  commands/compile/compile.go
  commands/debug/debug_info.go
  commands/upload/upload.go
  commands/upload/upload_test.go
  legacy/builder/add_additional_entries_to_context.go
  legacy/builder/builder.go
  legacy/builder/container_setup.go
  legacy/builder/fail_if_buildpath_equals_sketchpath.go
  legacy/builder/setup_build_properties.go
  legacy/builder/sketch_loader.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/builder_utils_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/ctags_runner_test.go
  legacy/builder/test/fail_if_buildpath_equals_sketchpath_test.go
  legacy/builder/test/helper.go
  legacy/builder/test/helper_tools_downloader.go
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/load_vid_pid_specific_properties_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/prototypes_adder_test.go
  legacy/builder/test/read_file_and_store_in_context_test.go
  legacy/builder/test/setup_build_properties_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/types/context.go
  legacy/builder/types/context_test.go
Labels: type: enhancement, topic: code

#2052 feat: filter boards by fqbn in connected list
  arduino/cores/fqbn.go
  arduino/cores/fqbn_test.go
  commands/board/list.go
  internal/cli/board/list.go
  internal/integrationtest/board/board_test.go
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/monitor.pb.go
  rpc/cc/arduino/cli/commands/v1/port.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.pb.go
  rpc/cc/arduino/cli/debug/v1/debug.pb.go
  rpc/cc/arduino/cli/debug/v1/debug_grpc.pb.go
  rpc/cc/arduino/cli/settings/v1/settings.pb.go
  rpc/cc/arduino/cli/settings/v1/settings_grpc.pb.go
Labels: type: enhancement, topic: code

#2051 [breaking] fix: validate sketch name
  commands/sketch/new.go
  commands/sketch/new_test.go
  docs/UPGRADING.md
  internal/cli/sketch/new.go
  internal/integrationtest/sketch/sketch_test.go
Labels: topic: code, type: imperfection

#1887 Add prioritization to tool selection in absence of explicit dependencies
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/cores/packagemanager/testdata/data_dir_1/package_test_index.json
  arduino/cores/packagemanager/testdata/data_dir_1/packages/test/hardware/avr/1.1.0/boards.txt
  arduino/cores/packagemanager/testdata/data_dir_1/packages/test/tools/bossac/1.7.5/.keep
  commands/debug/debug_info.go
  commands/upload/upload.go
  docs/UPGRADING.md
  docs/package_index_json-specification.md
  docs/platform-specification.md
  internal/integrationtest/compile_3/compile_test.go
  internal/integrationtest/compile_3/testdata/bare_minimum/bare_minimum.ino
  internal/integrationtest/compile_3/testdata/platforms_with_conflicting_tools/alice/hardware/avr/1.0.0/boards.txt
  internal/integrationtest/compile_3/testdata/platforms_with_conflicting_tools/alice/tools/avr-gcc/50.0.0/.keep
  internal/integrationtest/compile_3/testdata/platforms_with_conflicting_tools/alice/tools/avrdude/1.0.0/.keep
  internal/integrationtest/compile_3/testdata/platforms_with_conflicting_tools/bob/hardware/avr/1.0.0/boards.txt
  legacy/builder/target_board_resolver.go
Labels: priority: high, topic: code, type: imperfection, criticality: low

#2017 Show ctags errors when verbose
  legacy/builder/ctags_runner.go
Labels: type: enhancement, topic: code
