Repository arduino/arduino-cli, pull requests merged in 2023-06, with the labels that each got.

#2195 [skip-changelog] legacy: Arduino preprocess subroutine refactorization (part 5)
  arduino/builder/cpp/cpp.go
  arduino/builder/cpp/cpp_test.go
  arduino/builder/cpp_test.go
  arduino/builder/preprocessor/ctags.go
  arduino/builder/preprocessor/internal/ctags/ctags_has_issues.go
  arduino/builder/preprocessor/internal/ctags/ctags_parser.go
  arduino/builder/preprocessor/internal/ctags/ctags_parser_test.go
  arduino/builder/preprocessor/internal/ctags/ctags_to_prototypes.go
  arduino/builder/preprocessor/internal/ctags/ctags_to_prototypes_test.go
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserClassMembersAreFilteredOut.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserDefaultArguments.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserFunctionPointer.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserFunctionPointers.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserFunctionPointersNoIndirect.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserNamespace.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserShouldDealFunctionWithDifferentSignatures.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserShouldDealWithClasses.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserShouldDealWithMacros.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserShouldDealWithStructs.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserShouldListPrototypes.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserShouldListTemplates.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserShouldListTemplates2.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserStatic.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsParserStructWithFunctions.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsRunnerSketchWithClassFunction.txt
  arduino/builder/preprocessor/internal/ctags/testdata/TestCTagsRunnerSketchWithMultifile.txt
  arduino/builder/sketch.go
  internal/integrationtest/compile_1/compile_test.go
  legacy/builder/add_additional_entries_to_context.go
  legacy/builder/builder.go
  legacy/builder/constants/constants.go
  legacy/builder/container_add_prototypes.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/prototypes_adder.go
  legacy/builder/test/add_additional_entries_to_context_test.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/ctags_runner_test.go
  legacy/builder/test/helper.go
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/prototypes_adder_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/test/utils_test.go
  legacy/builder/types/context.go
  legacy/builder/utils/utils.go
Labels: type: enhancement, topic: code

#2206 [skip-changelog] legacy: some simple refactorings
  arduino/libraries/librarieslist.go
  legacy/builder/container_find_includes.go
  legacy/builder/resolve_library.go
  legacy/builder/types/accessories.go
  legacy/builder/types/types.go
Labels: type: enhancement, topic: code

#2211 Fix crash in upload if the upload tool platform is missing
  commands/upload/upload.go
  internal/integrationtest/upload/upload_test.go
Labels: topic: code, type: imperfection

#2214 Use the same property name for the query term in search requests
  client_example/main.go
  commands/lib/search.go
  commands/lib/search_test.go
  internal/cli/arguments/completion.go
  internal/cli/lib/args.go
  internal/cli/lib/search.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: type: enhancement, topic: gRPC

#2215 Remove not needed `instance` field in `LoadSketch` and `NewSketch` gRPC API
  internal/cli/sketch/new.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
Labels: type: enhancement, topic: gRPC

#2207 Return exit code 0 when a core is already up to date
  internal/cli/core/upgrade.go
  internal/integrationtest/core/core_test.go
Labels: topic: code, type: imperfection, topic: CLI

#2119 Automatically download indexes, if missing, in gRPC `Init` call
  arduino/resources/index.go
  commands/core/list.go
  commands/daemon/daemon.go
  commands/instances.go
  docs/UPGRADING.md
  internal/cli/arguments/completion.go
  internal/cli/arguments/reference.go
  internal/cli/core/list.go
  internal/cli/core/search.go
  internal/cli/core/update_index.go
  internal/cli/core/upgrade.go
  internal/cli/instance/instance.go
  internal/cli/lib/search.go
  internal/cli/lib/update_index.go
  internal/cli/update/update.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_test.go
Labels: type: enhancement, topic: gRPC

#2216 [breaking] Check cross-platform compatibility of sketch names
  commands/sketch/new.go
  commands/sketch/new_test.go
  docs/UPGRADING.md
  docs/sketch-specification.md
Labels: type: enhancement, topic: documentation, topic: code

#2218 [skip-changelog] Update expected `installed.json` after index changes
  internal/integrationtest/testdata/installed.json
Labels: topic: infrastructure, type: imperfection

#2222 [skip-changelog] Fix failing board tests
  internal/integrationtest/board/board_test.go
Labels: topic: code, type: imperfection

#2219 [breaking] Align `board list --watch` and `board list` json output
  docs/UPGRADING.md
  internal/cli/board/list.go
Labels: topic: code, type: imperfection

#2224 Report `is_hidden` field in board identification
  commands/board/list.go
Labels: type: enhancement, topic: code, topic: gRPC

#2232 [breaking] Do not prevent CLI startup if `inventory.yaml` is corrupted
  commands/board/list.go
  commands/compile/compile.go
  docs/UPGRADING.md
  internal/cli/cli.go
  internal/cli/updater/updater.go
  internal/integrationtest/board/board_test.go
  internal/inventory/inventory.go
Labels: type: enhancement, topic: code

#2234 Fix 1200-bps touch DTR handling (Windows)
  arduino/serialutils/serialutils.go
Labels: priority: high, topic: code, type: imperfection, criticality: highest
