Repository arduino/arduino-cli, pull requests merged in 2023-10, with the labels that each got.

#2346 fix wrong IndexFile truncate
  arduino/resources/index.go
  arduino/resources/resources_test.go
Labels: type: imperfection

#2349 [breaking] Removed gRPC 'debug' service in favor of 'commands' service
  Taskfile.yml
  client_example/main.go
  commands/daemon/debug.go
  commands/debug/debug.go
  commands/debug/debug_info.go
  commands/debug/debug_test.go
  docs/UPGRADING.md
  internal/cli/daemon/daemon.go
  internal/cli/debug/debug.go
  mkdocs.yml
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
  rpc/cc/arduino/cli/debug/v1/debug.pb.go
  rpc/cc/arduino/cli/debug/v1/debug_grpc.pb.go
Labels: type: enhancement, topic: gRPC

#2364 debugger: some improvements in configuration handling
  .licenses/go/github.com/arduino/go-properties-orderedmap.dep.yml
  commands/debug/debug_info.go
  docs/platform-specification.md
  go.mod
  go.sum
  internal/integrationtest/debug/debug_test.go
  internal/integrationtest/debug/testdata/hardware/my/samd/boards.txt
Labels: type: enhancement, topic: code

#2348 Added `upload --upload-field key=value` flag to set upload fields value
  internal/cli/arguments/key_value.go
  internal/cli/upload/upload.go
Labels: type: enhancement, topic: CLI

#2372 Added `{sketch_path}` to build properties
  arduino/builder/builder.go
  internal/integrationtest/compile_3/compile_show_properties_test.go
Labels: type: imperfection, topic: build-process

#2335 refactor: Made `command` functions to access PackageManager unavailable from public API
  commands/board/details.go
  commands/board/list.go
  commands/board/listall.go
  commands/board/search.go
  commands/compile/compile.go
  commands/core/download.go
  commands/core/install.go
  commands/core/list.go
  commands/core/search.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  commands/debug/debug.go
  commands/debug/debug_info.go
  commands/instances.go
  commands/internal/instances/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/list.go
  commands/lib/resolve_deps.go
  commands/lib/search.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
  commands/monitor/monitor.go
  commands/monitor/settings.go
  commands/upload/burnbootloader.go
  commands/upload/programmers_list.go
  commands/upload/upload.go
  internal/cli/arguments/completion.go
  internal/cli/arguments/port.go
  internal/integrationtest/completion/completion_test.go
  rpc/cc/arduino/cli/commands/v1/common.go
Labels: type: enhancement, topic: code

#2374 Introduce new "v" version format
  .github/workflows/release-go-task.yml
  Taskfile.yml
  docs/UPGRADING.md
  install.sh
Labels: type: enhancement, topic: infrastructure

#2376 testsuite: added mocked serial discovery for integration tests
  go.mod
  go.sum
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/board/board_test.go
  internal/integrationtest/mock_serial_discovery/.gitignore
  internal/integrationtest/mock_serial_discovery/main.go
Labels: type: enhancement, topic: infrastructure

#2379 testsuite: added mocked serial monitor for integration tests
  go.mod
  go.sum
  internal/cli/feedback/terminal.go
  internal/cli/monitor/monitor.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/monitor/monitor_test.go
  internal/mock_serial_discovery/.gitignore
  internal/mock_serial_discovery/main.go
  internal/mock_serial_monitor/.gitignore
  internal/mock_serial_monitor/main.go
Labels: type: enhancement, topic: infrastructure

#2357 [breaking] Updated gRPC Platform API
  .golangci.yml
  arduino/cores/cores.go
  arduino/cores/packageindex/index.go
  arduino/cores/packageindex/index_test.go
  arduino/cores/packagemanager/loader.go
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/profiles.go
  client_example/main.go
  commands/board/details.go
  commands/board/list.go
  commands/board/listall.go
  commands/board/search.go
  commands/core.go
  commands/core/list.go
  commands/core/search.go
  commands/core/search_test.go
  commands/core/upgrade.go
  commands/daemon/daemon.go
  docs/UPGRADING.md
  internal/cli/arguments/completion.go
  internal/cli/arguments/reference.go
  internal/cli/board/search.go
  internal/cli/core/list.go
  internal/cli/core/search.go
  internal/cli/core/upgrade.go
  internal/cli/feedback/result/rpc.go
  internal/cli/outdated/outdated.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/board/hardware_loading_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/daemon/daemon_test.go
  internal/orderedmap/orderedmap.go
  internal/orderedmap/orderedmap_test.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/commands/v1/common.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/core.proto
Labels: status: on hold, topic: code, topic: gRPC

#2373 Added search using qualifier[:=]value syntax
  commands/lib/search.go
  commands/lib/search_matcher.go
  commands/lib/search_test.go
  commands/lib/testdata/qualified_search/library_index.json
  internal/cli/lib/search.go
  internal/integrationtest/lib/lib_test.go
Labels: type: enhancement, topic: code

#2329 Get default port address and protocol from sketch profile using `monitor -s <sketchPath>`
  internal/cli/arguments/port.go
  internal/cli/arguments/sketch.go
  internal/cli/board/attach.go
  internal/cli/compile/compile.go
  internal/cli/debug/debug.go
  internal/cli/monitor/monitor.go
  internal/cli/upload/upload.go
  internal/integrationtest/monitor/monitor_test.go
  internal/integrationtest/monitor/testdata/SketchWithDefaultFQBN/SketchWithDefaultFQBN.ino
  internal/integrationtest/monitor/testdata/SketchWithDefaultFQBN/sketch.yaml
  internal/integrationtest/monitor/testdata/SketchWithDefaultPort/SketchWithDefaultPort.ino
  internal/integrationtest/monitor/testdata/SketchWithDefaultPort/sketch.yaml
  internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndFQBN/SketchWithDefaultPortAndFQBN.ino
  internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndFQBN/sketch.yaml
  internal/integrationtest/monitor/testdata/SketchWithNoProfiles/SketchWithNoProfiles.ino
Labels: type: enhancement, topic: code

#2388 [BREAKING]: gRPC drop query field from LibrarySearchRequest
  commands/lib/search.go
  docs/UPGRADING.md
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: topic: code

#2391 Added `programmer` field in debug info output
  commands/debug/debug_info.go
  internal/cli/debug/debug.go
  internal/integrationtest/debug/debug_test.go
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
Labels: type: enhancement, topic: CLI

#2394 debug: Enforce programmer selection
  commands/debug/debug_info.go
  commands/debug/debug_test.go
  commands/debug/testdata/custom_hardware/arduino-test/samd/programmers.txt
Labels: topic: code, type: imperfection

#2396 debug: Slightly refactored custom_configs section of `GetDebugConfigResponse`
  commands/debug/debug_info.go
  internal/cli/debug/debug.go
  internal/integrationtest/debug/debug_test.go
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
Labels: type: enhancement, topic: code, topic: gRPC
