Repository arduino/arduino-cli, pull requests merged in 2023-04, with the labels that each got.

#2139 fix: library loading errors genereates unneeded compile failures
  commands/instances.go
  internal/integrationtest/compile_3/compile_test.go
  legacy/builder/libraries_loader.go
Labels: topic: code, type: imperfection

#2140 Speed-up lib dependency resolution in some particular cases
  .licenses/go/go.bug.st/relaxed-semver.dep.yml
  go.mod
  go.sum
Labels: type: enhancement, topic: code

#2138 [skip-changelog] Issue a warning when the signature verification fails
  arduino/cores/packageindex/index.go
Labels: topic: code, type: imperfection

#2145 [breaking] Fix regression in core caching
  arduino/cores/board.go
  arduino/cores/board_test.go
  arduino/cores/packagemanager/package_manager.go
  docs/UPGRADING.md
  go.mod
  go.sum
  internal/integrationtest/compile_3/core_caching_test.go
  legacy/builder/constants/constants.go
  legacy/builder/phases/core_builder.go
Labels: topic: code, type: imperfection

#2136 [Skip-changelog] Improve documentation regarding `ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS`
  docs/configuration.md
  internal/cli/config/init.go
Labels: type: enhancement, topic: documentation

#2151 Implemented `--show-properties` in `board details` command
  arduino/builder/sketch.go
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/cores/packagemanager/testdata/custom_hardware/arduino/sam/boards.txt
  arduino/cores/packagemanager/testdata/custom_hardware/arduino/sam/platform.txt
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/boards.txt
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/bootloaders/stk500v2/stk500boot_v2_mega2560.hex
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/libraries/SPI/SPI.cpp
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/libraries/SPI/SPI.h
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/libraries/SPI/examples/BarometricPressureSensor/BarometricPressureSensor.ino
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/libraries/SPI/examples/DigitalPotControl/DigitalPotControl.ino
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/libraries/SPI/keywords.txt
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/libraries/SPI/library.properties
  arduino/cores/packagemanager/testdata/custom_hardware/my_avr_platform/avr/platform.txt
  arduino/cores/packagemanager/testdata/custom_hardware/watterott/avr/boards.txt
  arduino/cores/packagemanager/testdata/custom_hardware/watterott/avr/platform.txt
  arduino/cores/packagemanager/testdata/custom_hardware/watterott/avr/programmers.txt
  commands/board/details.go
  commands/compile/compile.go
  internal/cli/arguments/show_properties.go
  internal/cli/board/attach.go
  internal/cli/board/details.go
  internal/cli/board/list.go
  internal/cli/compile/compile.go
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/compile_2/compile_test.go
  legacy/builder/container_setup.go
  legacy/builder/hardware_loader.go
  legacy/builder/set_custom_build_properties.go
  legacy/builder/setup_build_properties.go
  legacy/builder/target_board_resolver.go
  legacy/builder/test/add_build_board_property_if_missing_test.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/ctags_runner_test.go
  legacy/builder/test/hardware_loader_test.go
  legacy/builder/test/helper.go
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/prototypes_adder_test.go
  legacy/builder/test/setup_build_properties_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/target_board_resolver_test.go
  legacy/builder/test/tools_loader_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/types/context.go
  legacy/builder/types/context_test.go
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
Labels: type: enhancement, topic: CLI

#2152 Fix preprocess output (do not print stats after the preprocessed source)
  internal/cli/compile/compile.go
  internal/integrationtest/compile_1/compile_test.go
Labels: topic: code, type: imperfection

#2153 [skip-changelog] Override default pluggable monitor for `serial` protocol
  arduino/cores/packagemanager/loader.go
Labels: topic: code, type: imperfection

#2160 [skip-changelog] Cleaned-up some legacy code
  .licenses/go/golang.org/x/exp/constraints.dep.yml
  .licenses/go/golang.org/x/exp/slices.dep.yml
  legacy/builder/create_cmake_rule.go
  legacy/builder/test/helper_tools_downloader.go
  legacy/builder/test/unique_string_queue_test.go
  legacy/builder/types/accessories.go
  legacy/builder/types/types.go
  legacy/builder/types/utils.go
  legacy/builder/unused_compiled_libraries_remover.go
  legacy/builder/utils/utils.go
Labels: type: enhancement, topic: code

#2159 Respect the order of menu, when computing the config options
  arduino/cores/board.go
  arduino/cores/board_test.go
Labels: type: enhancement
