Repository arduino/arduino-cli, pull requests merged in 2023-11, with the labels that each got.

#2398 Renamed gRPC field to match JSON output
  commands/debug/debug_info.go
  internal/cli/debug/debug.go
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
Labels: type: enhancement, topic: code

#2400 feat: added exit codes for CLI `daemon` command errors
  internal/cli/daemon/daemon.go
  internal/cli/feedback/errorcodes.go
Labels: type: imperfection, topic: CLI

#2389 Use feedback/result structs in cli commands instead of rpc ones
  internal/cli/board/details.go
  internal/cli/board/list.go
  internal/cli/board/listall.go
  internal/cli/board/search.go
  internal/cli/compile/compile.go
  internal/cli/core/list.go
  internal/cli/core/search.go
  internal/cli/feedback/result/rpc.go
  internal/cli/feedback/result/rpc_test.go
  internal/cli/lib/check_deps.go
  internal/cli/lib/examples.go
  internal/cli/lib/list.go
  internal/cli/lib/search.go
  internal/cli/monitor/monitor.go
  internal/cli/outdated/outdated.go
  internal/cli/sketch/new.go
  internal/cli/upload/upload.go
Labels: type: enhancement, topic: code

#2402 Added specific CLI return error-code if inventory can not be created
  internal/cli/cli.go
  internal/cli/feedback/errorcodes.go
Labels: type: imperfection, topic: CLI

#2408 [skip-changelog] remove `mysketchbook` folder committed by mistake
  mysketchbook/newsketch/newsketch.ino
Labels: topic: infrastructure

#2399 Replace `mitchellh/go` used for macOS notarization
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
Labels: type: enhancement, topic: infrastructure

#2182 Report compiler errors in machine readable format
  .prettierignore
  arduino/builder/builder.go
  arduino/builder/compilation.go
  arduino/builder/internal/diagnostics/compiler_detection.go
  arduino/builder/internal/diagnostics/compiler_detection_test.go
  arduino/builder/internal/diagnostics/parser.go
  arduino/builder/internal/diagnostics/parser_gcc.go
  arduino/builder/internal/diagnostics/parser_test.go
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test001.txt
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test001.txt.json
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test002.txt
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test002.txt.json
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test003.txt
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test003.txt.json
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test004.txt
  arduino/builder/internal/diagnostics/testdata/compiler_outputs/test004.txt.json
  commands/compile/compile.go
  internal/cli/compile/compile.go
  internal/cli/feedback/result/rpc.go
  internal/cli/feedback/result/rpc_test.go
  internal/integrationtest/compile_3/compile_test.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
Labels: type: enhancement, topic: gRPC

#2411 [breaking] Remove gRPC `settings` service
  Taskfile.yml
  client_example/main.go
  commands/daemon/settings.go
  commands/daemon/settings_test.go
  docs/UPGRADING.md
  internal/cli/config/delete.go
  internal/cli/daemon/daemon.go
  internal/integrationtest/arduino-cli.go
  mkdocs.yml
  rpc/buf.yaml
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/commands/v1/settings.pb.go
  rpc/cc/arduino/cli/commands/v1/settings.proto
  rpc/cc/arduino/cli/settings/v1/settings.pb.go
  rpc/cc/arduino/cli/settings/v1/settings_grpc.pb.go
Labels: type: enhancement, topic: gRPC

#2285 [BREAKING] Support only compatible platform versions
  arduino/cores/cores.go
  arduino/cores/packagemanager/download.go
  arduino/cores/packagemanager/install_uninstall.go
  arduino/cores/packagemanager/package_manager.go
  arduino/cores/packagemanager/package_manager_test.go
  commands/board/search.go
  commands/core.go
  commands/core/search.go
  commands/core/search_test.go
  docs/UPGRADING.md
  internal/cli/arguments/completion.go
  internal/cli/arguments/reference.go
  internal/cli/compile/compile.go
  internal/cli/core/list.go
  internal/cli/core/search.go
  internal/cli/core/upgrade.go
  internal/cli/feedback/result/rpc.go
  internal/cli/upload/upload.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/board/board_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/testdata/test_index.json
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/core.proto
Labels: type: enhancement, topic: code, topic: CLI, topic: gRPC

#2381 test: Fixed runners not running 'board' integration test
  .github/workflows/test-go-task.yml
  internal/integrationtest/board/board_test.go
  internal/integrationtest/board/hardware_loading_test.go
Labels: topic: infrastructure, type: imperfection

#2407 [breaking] cli: format json always start with a json object
  docs/UPGRADING.md
  internal/cli/board/list.go
  internal/cli/board/listall.go
  internal/cli/board/search.go
  internal/cli/config/add.go
  internal/cli/config/dump.go
  internal/cli/config/init.go
  internal/cli/config/set.go
  internal/cli/core/list.go
  internal/cli/core/search.go
  internal/cli/lib/check_deps.go
  internal/cli/lib/examples.go
  internal/cli/lib/list.go
  internal/integrationtest/board/board_test.go
  internal/integrationtest/board/hardware_loading_test.go
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/config/config_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/lib/lib_test.go
Labels: topic: code

#2378 Update golangci-lint
  .github/workflows/check-go-task.yml
  .golangci.yml
  arduino/cores/packagemanager/install_uninstall.go
  arduino/discovery/discovery.go
  arduino/errors.go
  client_example/main.go
  commands/board/details.go
  commands/board/list.go
  commands/board/list_test.go
  commands/board/listall.go
  commands/board/search.go
  commands/compile/compile.go
  commands/core/download.go
  commands/core/install.go
  commands/core/search.go
  commands/core/search_test.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  commands/daemon/daemon.go
  commands/daemon/settings.go
  commands/daemon/term_example/main.go
  commands/debug/debug.go
  commands/debug/debug_info.go
  commands/lib/install.go
  commands/lib/resolve_deps.go
  commands/lib/search.go
  commands/lib/search_test.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
  commands/monitor/monitor.go
  commands/sketch/archive.go
  commands/sketch/load.go
  commands/sketch/new.go
  commands/sketch/set_defaults.go
  commands/upload/upload.go
  commands/upload/upload_test.go
  internal/cli/arguments/completion.go
  internal/cli/arguments/port.go
  internal/cli/arguments/user_fields.go
  internal/cli/board/search.go
  internal/cli/compile/compile.go
  internal/cli/core/list.go
  internal/cli/core/upgrade.go
  internal/cli/debug/debug.go
  internal/cli/feedback/result/rpc.go
  internal/cli/instance/instance.go
  internal/cli/lib/examples.go
  internal/cli/lib/list.go
  internal/cli/monitor/monitor.go
  internal/cli/upload/upload.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_test.go
  internal/integrationtest/daemon/download_progress_test.go
  rpc/cc/arduino/cli/commands/v1/common.go
Labels: type: enhancement, topic: infrastructure

#2416 Added `programmer.default` directive to set a default programmer for a board.
  arduino/cores/board.go
  commands/board/details.go
  docs/platform-specification.md
  internal/cli/arguments/programmer.go
  internal/cli/board/details.go
  internal/cli/burnbootloader/burnbootloader.go
  internal/cli/compile/compile.go
  internal/cli/debug/debug.go
  internal/cli/feedback/result/rpc.go
  internal/cli/upload/upload.go
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
Labels: type: enhancement, topic: gRPC

#2418 Removed useless file-readable check while enumerating source code files
  arduino/builder/internal/utils/utils.go
Labels: type: imperfection, topic: build-process

#2417 Make yaml output consistent with the json one
  .licensed.yml
  .licenses/go/sigs.k8s.io/yaml.dep.yml
  .licenses/go/sigs.k8s.io/yaml/goyaml.v2.dep.yml
  go.mod
  go.sum
  internal/cli/feedback/feedback.go
Labels: type: enhancement

#2420 Remove no longer needed comment
  arduino/resources/install.go
Labels: type: enhancement

#2419 make boards details JSON output deterministic
  internal/cli/feedback/result/rpc.go
Labels: type: enhancement

#2425 Use mocked serial discovery in board integration tests that weren't running in CI
  internal/integrationtest/board/board_test.go
Labels: type: enhancement

#2414 Improved logging on GitHub Actions runners (using log folding commands)
  Taskfile.yml
  internal/integrationtest/arduino-cli.go
Labels: type: enhancement, topic: infrastructure

#2427 fix: Fixed regression in `compile_commands.json` generation
  arduino/builder/internal/detector/detector.go
  internal/integrationtest/compile_3/compile_commands_test.go
Labels: type: imperfection, topic: build-process

#2428 Added a compatibility trick in `debug -I` for `toolchain.prefix` key
  commands/debug/debug.go
  commands/debug/debug_info.go
  docs/UPGRADING.md
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
Labels: type: enhancement, topic: CLI

#2429 Added specific exit-code for "missing programmer" kind of errors.
  arduino/errors.go
  commands/daemon/debug.go
  internal/cli/burnbootloader/burnbootloader.go
  internal/cli/compile/compile.go
  internal/cli/debug/debug.go
  internal/cli/feedback/errorcodes.go
  internal/cli/upload/upload.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
Labels: type: enhancement, topic: CLI

#2426 Add completion support to `--profile`
  internal/cli/arguments/profiles.go
  internal/cli/arguments/sketch.go
  internal/integrationtest/completion/completion_test.go
  internal/integrationtest/completion/testdata/SketchWithProfiles/SketchWithProfiles.ino
  internal/integrationtest/completion/testdata/SketchWithProfiles/sketch.yaml
Labels: type: enhancement

#2435 Debugger now allows generic selection of sub-configurations
  commands/debug/debug_info.go
  docs/platform-specification.md
  internal/integrationtest/debug/debug_test.go
  internal/integrationtest/debug/testdata/hardware/my/samd/boards.txt
  internal/integrationtest/debug/testdata/hardware/my/samd/platform.txt
Labels: type: enhancement, topic: code

#2438 [BREAKING] Removed `debugging_supported` field from `BoardDetails` gRPC call
  commands/board/details.go
  docs/UPGRADING.md
  internal/cli/board/details.go
  internal/cli/feedback/result/rpc.go
  internal/integrationtest/board/board_test.go
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
Labels: type: enhancement, topic: code

#2433 [skip-changelog] Add documentation on the `network.proxy` configuration's field
  docs/configuration.md
Labels: type: enhancement, topic: documentation

#2431 Library update/install with `--no-overwrite` will perform the update if it's possible to keep already installed dependencies at their current version
  .licenses/go/go.bug.st/relaxed-semver.dep.yml
  arduino/libraries/librariesindex/index.go
  arduino/libraries/librariesindex/index_test.go
  arduino/libraries/librariesindex/json.go
  arduino/libraries/librariesmanager/librariesmanager.go
  commands/lib/install.go
  commands/lib/resolve_deps.go
  commands/lib/search.go
  go.mod
  go.sum
  internal/cli/lib/check_deps.go
  internal/integrationtest/lib/lib_test.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: type: enhancement, topic: code

#2444 Parallelize `upload_mock` integration tests
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/upload_mock/upload_mock_test.go
Labels: type: enhancement, topic: infrastructure
