Repository arduino/arduino-cli, pull requests merged in 2023-07, with the labels that each got.

#2233 feat: library folder name priority promotion for `-main` suffix
  arduino/libraries/librariesresolver/cpp.go
  arduino/libraries/librariesresolver/cpp_test.go
  docs/sketch-build-process.md
Labels: type: enhancement, topic: code, topic: build-process

#2238 When launching `core list` with no installed platforms show table headers
  internal/cli/core/list.go
  internal/integrationtest/core/core_test.go
Labels: type: enhancement, topic: code, topic: CLI

#2246 [skip-changelog] Add `output.no_color` to configuration docs
  configuration/configuration.schema.json
  docs/configuration.md
Labels: type: enhancement, topic: documentation

#2247 [skip-changelog] Add explanation on how to change the monitor configuration to FAQ
  docs/FAQ.md
Labels: type: enhancement, topic: documentation

#2249 Explain usage of `monitor --config` in command help
  internal/cli/monitor/monitor.go
Labels: type: enhancement, topic: documentation

#2250 [skip-changelog] Update `installed.json` file used in tests
  internal/integrationtest/testdata/installed.json
Labels: topic: code, type: imperfection
