Repository arduino/arduino-cli, pull requests merged in 2023-05, with the labels that each got.

#2163 fix: Allow build-path to be in a different drive than current sketch
  .licenses/go/github.com/arduino/go-paths-helper.dep.yml
  arduino/cores/packagemanager/install_uninstall.go
  arduino/sketch/sketch.go
  commands/compile/compile.go
  go.mod
  go.sum
Labels: topic: code, type: imperfection, topic: build-process

#2164 Fixed integration test
  internal/integrationtest/core/core_test.go
  internal/integrationtest/core/testdata/core_with_postinst.zip
  internal/integrationtest/core/testdata/package_with_postinstall_index.json
Labels: type: enhancement, topic: infrastructure

#2162 Ignore `__MACOSX` folder in tool archives when launching core install
  arduino/resources/install.go
  arduino/resources/install_test.go
  arduino/resources/testdata/invalid/platform_with_multiple_root_folders.tar.bz2
  arduino/resources/testdata/invalid/platform_without_root_folder.tar.bz2
  arduino/resources/testdata/valid/platform_with_root_and__MACOSX_folder.tar.bz2
Labels: type: imperfection, topic: CLI

#2171 Fix `Compile` gRPC call hangs when there is a lot of output
  commands/daemon/daemon.go
  commands/daemon/stream.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_concurrency_test.go
  internal/integrationtest/daemon/daemon_test.go
  internal/integrationtest/testdata/ManyWarningsSketch/ManyWarningsSketch.ino
Labels: type: imperfection, topic: gRPC

#2146 [skip-changelog] Avoid getting locked up in a perpetual symlink loop when loading a library
  arduino/libraries/libraries_test.go
  arduino/libraries/loader.go
  arduino/libraries/testdata/TestLibExamples/examples/MultipleFiles/MultipleFiles.ino
  arduino/libraries/testdata/TestLibExamples/examples/MultipleFiles/MultipleFiles.pde
  arduino/libraries/testdata/TestLibExamples/examples/WrongCasing/wrongCasing.ino
  arduino/libraries/testdata/TestLibExamples/examples/simple/simple.ino
  arduino/libraries/testdata/TestLibExamples/library.properties
  arduino/libraries/testdata/TestLibExamples/src/TestLib.h
Labels: topic: code, type: imperfection

#2168 [skip-changelog] Verify installation of builtin tools by checking that their executable is present
  arduino/cores/packagemanager/loader_test.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/cores/tools.go
  internal/integrationtest/board/board_test.go
Labels: topic: code, type: imperfection

#2178 [skip-changelog] Update `go-win32-utils` dependency
  .licenses/go/github.com/arduino/go-win32-utils.dep.yml
  go.mod
  go.sum
Labels: type: enhancement, topic: code

#2173 Easier recovery from soft bricked native USB boards
  arduino/serialutils/serialutils.go
  commands/upload/upload.go
  internal/integrationtest/upload_mock/upload_mock_test.go
Labels: topic: code, type: imperfection

#2181 Improved gRPC how-to in contributing guide
  docs/CONTRIBUTING.md
Labels: type: enhancement, topic: documentation

#2185 Fixed integration test
  internal/integrationtest/lib/lib_test.go
Labels: topic: infrastructure, type: imperfection

#2174 Identify managed platforms not tracked by a package index
  arduino/cores/cores.go
  arduino/cores/packageindex/index.go
  arduino/cores/packagemanager/install_uninstall.go
  commands/board/listall.go
  commands/board/search.go
  commands/core.go
  commands/core/search_test.go
  commands/core/upgrade.go
  commands/daemon/daemon.go
  commands/instances.go
  internal/cli/core/upgrade.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/daemon/daemon_test.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/core.proto
Labels: type: enhancement

#2186 [skip-changelog] legacy: Arduino preprocess subroutine refactorization (part 1)
  arduino/builder/cpp.go
  arduino/builder/cpp_test.go
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  legacy/builder/builder.go
  legacy/builder/container_add_prototypes.go
  legacy/builder/container_merge_copy_sketch_files.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/ctags/ctags_has_issues.go
  legacy/builder/ctags/ctags_parser.go
  legacy/builder/ctags/ctags_parser_test.go
  legacy/builder/ctags/ctags_to_prototypes_test.go
  legacy/builder/ctags_runner.go
  legacy/builder/ctags_target_file_saver.go
  legacy/builder/filter_sketch_source.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/prototypes_adder.go
  legacy/builder/read_file_and_store_in_context.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/ctags_runner_test.go
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/prototypes_adder_test.go
  legacy/builder/test/read_file_and_store_in_context_test.go
  legacy/builder/test/utils_test.go
  legacy/builder/types/context.go
  legacy/builder/types/types.go
  legacy/builder/utils/utils.go
Labels: type: enhancement, topic: code

#2177 [skip changelog] Automate license headers checks in CI
  .github/workflows/check-go-task.yml
  Taskfile.yml
  arduino/discovery/testdata/cat/main.go
  commands/lib/search_test.go
  commands/sketch/new_test.go
  configuration/configuration_schema_test.go
  executils/testdata/delay/main.go
  i18n/cmd/po/merge_test.go
  internal/cli/arguments/completion.go
  license_header.tpl
Labels: type: enhancement

#2189 Improve archive structure docs
  docs/package_index_json-specification.md
Labels: type: enhancement, topic: documentation

#2192 Avoid `lib install` command hanging indefinitely in dependencies resolution.
  .licenses/go/go.bug.st/relaxed-semver.dep.yml
  go.mod
  go.sum
  internal/integrationtest/lib/lib_test.go
Labels: topic: code, type: imperfection

#2190 [skip-changelog] Bump setup-protoc to v2
  .github/workflows/check-protobuf-task.yml
Labels: type: enhancement, topic: infrastructure

#2183 [skip-changelog] Handle errors that occur during reset
  arduino/serialutils/serialutils.go
  commands/upload/upload.go
Labels: topic: code, type: imperfection, topic: gRPC

#2194 [skip-changelog] legacy: Arduino preprocess subroutine refactorization (part 4)
  arduino/builder/preprocessor/gcc.go
  legacy/builder/container_add_prototypes.go
  legacy/builder/container_find_includes.go
  legacy/builder/ctags/ctags_has_issues.go
  legacy/builder/ctags/ctags_parser.go
  legacy/builder/ctags/ctags_parser_test.go
  legacy/builder/ctags/ctags_to_prototypes.go
  legacy/builder/ctags/ctags_to_prototypes_test.go
  legacy/builder/gcc_preproc_runner.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/prototypes_adder.go
Labels: type: enhancement, topic: code
