Repository arduino/arduino-cli, pull requests merged in 2023-12, with the labels that each got.

#2443 Added `debug check` command to check if a combination of board/programmer supports debugging.
  arduino/cores/fqbn.go
  commands/daemon/debug.go
  commands/debug/debug.go
  commands/debug/debug_info.go
  internal/cli/debug/debug.go
  internal/cli/debug/debug_check.go
  internal/cli/feedback/result/rpc.go
  internal/cli/feedback/result/rpc_test.go
  internal/integrationtest/debug/debug_test.go
  internal/integrationtest/debug/testdata/hardware/my/samd/boards.txt
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
Labels: type: enhancement, topic: code

#2470 Added backward compatibilty policy document
  docs/index.md
  docs/versioning.md
  mkdocs.yml
Labels: type: enhancement, topic: documentation

#2464 Reuse archiveCompiledFiles helper for long commandline shrink
  .licenses/go/github.com/arduino/go-paths-helper.dep.yml
  go.mod
  go.sum
  internal/arduino/builder/archive_compiled_files.go
  internal/arduino/builder/core.go
  internal/arduino/builder/libraries.go
  internal/arduino/builder/linker.go
  internal/integrationtest/compile_1/compile_test.go
Labels: type: enhancement, topic: build-process

#2472 [breaking] Some gRPC API improvements
  commands/compile/compile.go
  commands/daemon/daemon.go
  docs/UPGRADING.md
  internal/cli/compile/compile.go
  internal/cli/feedback/result/rpc.go
  internal/cli/feedback/result/rpc_test.go
  internal/integrationtest/compile_3/compile_show_properties_test.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
  rpc/cc/arduino/cli/commands/v1/upload.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.proto
Labels: type: enhancement, topic: gRPC

#2476 Return `error` instead of `nil` in package/library manager getters
  commands/board/details.go
  commands/board/list.go
  commands/board/listall.go
  commands/board/search.go
  commands/compile/compile.go
  commands/core/download.go
  commands/core/install.go
  commands/core/search.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  commands/debug/debug.go
  commands/debug/debug_info.go
  commands/instances.go
  commands/internal/instances/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/list.go
  commands/lib/resolve_deps.go
  commands/lib/search.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
  commands/monitor/monitor.go
  commands/monitor/settings.go
  commands/upload/burnbootloader.go
  commands/upload/programmers_list.go
  commands/upload/upload.go
Labels: type: enhancement, topic: code

#2477 Refactoring of LibraryManager libraries directory handling.
  commands/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/resolve_deps.go
  commands/lib/uninstall.go
  commands/lib/utils.go
  internal/arduino/builder/internal/detector/detector.go
  internal/arduino/globals/globals.go
  internal/arduino/libraries/librariesmanager/download.go
  internal/arduino/libraries/librariesmanager/librariesmanager.go
Labels: type: enhancement, topic: code
