Repository arduino/arduino-cli, pull requests merged in 2023-09, with the labels that each got.

#2290 Text output: removed trailing spaces for right-padding of tables
  table/table.go
Labels: type: enhancement, topic: CLI

#2295 Porting legacy tests to new integration-test infra (part 2...)
  internal/integrationtest/compile_4/compile_test.go
  internal/integrationtest/compile_4/testdata/SketchLibraryProvidesAllIncludes/SketchLibraryProvidesAllIncludes.ino
  internal/integrationtest/compile_4/testdata/libraries/ANewLibrary-master/anewlibrary.h
  internal/integrationtest/compile_4/testdata/libraries/SPI/SPI.cpp
  internal/integrationtest/compile_4/testdata/libraries/SPI/SPI.h
  internal/integrationtest/compile_4/testdata/libraries/SPI/keywords.txt
  internal/integrationtest/compile_4/testdata/libraries/SPI/library.properties
  internal/integrationtest/compile_4/testdata/user_hardware/arduino/avr/.gitkeep
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/boards.txt
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/bootloaders/stk500v2/stk500boot_v2_mega2560.hex
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/SPI.cpp
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/SPI.h
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/examples/BarometricPressureSensor/BarometricPressureSensor.ino
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/examples/DigitalPotControl/DigitalPotControl.ino
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/keywords.txt
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/library.properties
  internal/integrationtest/compile_4/testdata/user_hardware/my_avr_platform/avr/platform.txt
  internal/integrationtest/compile_4/testdata/user_hardware/my_symlinked_avr_platform
  legacy/builder/test/includes_to_include_folders_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
Labels: type: enhancement, topic: infrastructure

#2291 feature: Added raw terminal support in `monitor` command
  internal/cli/feedback/terminal.go
  internal/cli/monitor/monitor.go
  internal/cli/monitor/term.go
Labels: type: enhancement, topic: code, topic: CLI

#2292 [skip-changelog] Use gRPC function call to avoid accessing `arduino/cores` package directly
  internal/cli/arguments/completion.go
Labels: type: enhancement, topic: code

#2297 [skip-changelog] Use `LoadSketch` in upload function and return `rpc.Port` in `GetPort`
  internal/cli/arguments/fqbn.go
  internal/cli/arguments/port.go
  internal/cli/burnbootloader/burnbootloader.go
  internal/cli/upload/upload.go
Labels: type: enhancement, topic: code

#2286 legacy: Builder refactorization (part 1...)
  arduino/builder/builder.go
  arduino/builder/compilation_database.go
  arduino/builder/compilation_database_test.go
  arduino/builder/cpp/cpp.go
  arduino/builder/detector/detector.go
  arduino/builder/preprocessor/arduino_preprocessor.go
  arduino/builder/preprocessor/gcc.go
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  arduino/builder/utils/utils.go
  commands/compile/compile.go
  executils/process.go
  legacy/builder/add_additional_entries_to_context.go
  legacy/builder/builder.go
  legacy/builder/builder_utils/utils.go
  legacy/builder/container_find_includes.go
  legacy/builder/container_setup.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/libraries_loader.go
  legacy/builder/phases/core_builder.go
  legacy/builder/phases/libraries_builder.go
  legacy/builder/phases/linker.go
  legacy/builder/phases/sizer.go
  legacy/builder/phases/sketch_builder.go
  legacy/builder/preprocess_sketch.go
  legacy/builder/print_used_and_not_used_libraries.go
  legacy/builder/print_used_libraries_if_verbose.go
  legacy/builder/recipe_runner.go
  legacy/builder/test/add_additional_entries_to_context_test.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/builder_utils_test.go
  legacy/builder/test/hardware_loader_test.go
  legacy/builder/test/includes_finder_with_regexp_test.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/recipe_runner_test.go
  legacy/builder/test/setup_build_properties_test.go
  legacy/builder/test/tools_loader_test.go
  legacy/builder/test/unused_compiled_libraries_remover_test.go
  legacy/builder/types/accessories.go
  legacy/builder/types/context.go
  legacy/builder/types/types.go
  legacy/builder/unused_compiled_libraries_remover.go
  legacy/builder/utils/utils.go
  legacy/builder/warn_about_arch_incompatible_libraries.go
Labels: type: enhancement, topic: code

#2300 Porting `legacy` tests to new integration-test infra (part 3...)
  internal/integrationtest/board/hardware_loading_test.go
  internal/integrationtest/board/testdata/custom_local_txts/boards.local.txt
  internal/integrationtest/board/testdata/custom_local_txts/platform.local.txt
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/compile_4/compile_test.go
  internal/integrationtest/testdata/user_hardware/arduino/avr/.gitkeep
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/boards.txt
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/bootloaders/stk500v2/stk500boot_v2_mega2560.hex
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/SPI.cpp
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/SPI.h
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/examples/BarometricPressureSensor/BarometricPressureSensor.ino
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/examples/DigitalPotControl/DigitalPotControl.ino
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/keywords.txt
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/libraries/SPI/library.properties
  internal/integrationtest/testdata/user_hardware/my_avr_platform/avr/platform.txt
  internal/integrationtest/testdata/user_hardware/my_symlinked_avr_platform
  legacy/builder/test/builder_test.go
  legacy/builder/test/builder_utils_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/fail_if_buildpath_equals_sketchpath_test.go
  legacy/builder/test/hardware_loader_test.go
  legacy/builder/test/helper.go
  legacy/builder/test/helper_tools_downloader.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/test/load_previous_build_options_map_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/recipe_runner_test.go
  legacy/builder/test/setup_build_properties_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/test/unused_compiled_libraries_remover_test.go
  legacy/builder/test/wipeout_build_path_if_build_options_changed_test.go
Labels: type: enhancement, topic: infrastructure

#2298 [skip-changelog] legacy: Builder refactorization (part 2)
  arduino/builder/builder.go
  arduino/builder/core.go
  arduino/builder/progress/progress.go
  arduino/builder/progress/progress_test.go
  arduino/builder/sizer.go
  arduino/builder/sketch_test.go
  arduino/builder/utils/utils.go
  arduino/builder/utils/utils_test.go
  commands/compile/compile.go
  legacy/builder/builder.go
  legacy/builder/builder_utils/utils.go
  legacy/builder/constants/constants.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/ctags_target_file_saver.go
  legacy/builder/fail_if_buildpath_equals_sketchpath.go
  legacy/builder/phases/core_builder.go
  legacy/builder/phases/libraries_builder.go
  legacy/builder/phases/linker.go
  legacy/builder/phases/sizer.go
  legacy/builder/phases/sketch_builder.go
  legacy/builder/recipe_runner.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/helper.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/test/utils_test.go
  legacy/builder/types/context.go
  legacy/builder/utils/utils.go
  legacy/builder/wipeout_build_path_if_build_options_changed.go
Labels: type: enhancement, topic: code

#2303 legacy: refacored `makeSourceFile` / other minor code moved
  arduino/builder/builder.go
  arduino/builder/detector/detector.go
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  arduino/builder/utils/utils.go
  commands/compile/compile.go
  legacy/builder/constants/constants.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/merge_sketch_with_bootloader.go
  legacy/builder/phases/core_builder.go
  legacy/builder/phases/libraries_builder.go
  legacy/builder/phases/linker.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/helper_tools_downloader.go
  legacy/builder/wipeout_build_path_if_build_options_changed.go
Labels: type: enhancement, topic: code

#2305 regression: Import fix for `compile --input-dir .` regression found in #2304
  commands/compile/compile.go
  commands/upload/upload.go
  docs/sketch-project-file.md
  internal/cli/arguments/fqbn.go
  internal/cli/arguments/port.go
  internal/cli/burnbootloader/burnbootloader.go
  internal/cli/compile/compile.go
  internal/cli/upload/upload.go
  internal/integrationtest/profiles/profiles_test.go
  internal/integrationtest/testdata/sketch_with_default_profile/sketch.yaml
  internal/integrationtest/testdata/sketch_with_default_profile/sketch_with_default_profile.ino
  internal/integrationtest/testdata/sketch_without_default_profile/sketch.yaml
  internal/integrationtest/testdata/sketch_without_default_profile/sketch_without_default_profile.ino
Labels: type: imperfection, topic: CLI

#2302 [skip-changelog] legacy: refactor (part 3)
  arduino/builder/builder.go
  arduino/builder/detector/detector_test.go
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  commands/compile/compile.go
  legacy/builder/builder.go
  legacy/builder/container_build_options.go
  legacy/builder/create_build_options_map.go
  legacy/builder/create_cmake_rule.go
  legacy/builder/load_previous_build_options.go
  legacy/builder/merge_sketch_with_bootloader.go
  legacy/builder/print_used_libraries_if_verbose.go
  legacy/builder/recipe_runner.go
  legacy/builder/store_build_options_map.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/load_previous_build_options_map_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/recipe_runner_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/unused_compiled_libraries_remover_test.go
  legacy/builder/test/wipeout_build_path_if_build_options_changed_test.go
  legacy/builder/types/context.go
  legacy/builder/types/context_test.go
  legacy/builder/unused_compiled_libraries_remover.go
  legacy/builder/warn_about_arch_incompatible_libraries.go
  legacy/builder/wipeout_build_path_if_build_options_changed.go
Labels: topic: code

#2309 Fixed weird error message in `core install` if invalid platform is spcified
  arduino/errors.go
  internal/cli/arguments/reference.go
  internal/integrationtest/core/core_test.go
Labels: type: enhancement, topic: CLI

#2310 [skip-changelog] legacy: refactor (part 4)
  arduino/builder/compilation/database.go
  arduino/builder/compilation/database_test.go
  arduino/builder/core.go
  arduino/builder/detector/detector.go
  arduino/builder/libraries.go
  arduino/builder/linker.go
  arduino/builder/logger/logger.go
  arduino/builder/progress/progress.go
  arduino/builder/sizer.go
  arduino/builder/sizer/sizer.go
  arduino/builder/sizer/sizer_test.go
  arduino/builder/sketch.go
  arduino/builder/utils/utils.go
  arduino/builder/utils/utils_test.go
  commands/compile/compile.go
  legacy/builder/builder.go
  legacy/builder/merge_sketch_with_bootloader.go
  legacy/builder/phases/core_builder.go
  legacy/builder/phases/sketch_builder.go
  legacy/builder/recipe_runner.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/test/unused_compiled_libraries_remover_test.go
  legacy/builder/types/context.go
Labels: topic: code

#2314 feat: log `Required tool` with `debug` severity
  arduino/cores/packagemanager/package_manager.go
Labels: type: enhancement, topic: code

#2312 legacy: Builder refactorization (part 5...)
  arduino/builder/build_options_manager.go
  arduino/builder/builder.go
  arduino/builder/core.go
  arduino/builder/export_cmake.go
  arduino/builder/libraries.go
  arduino/builder/linker.go
  arduino/builder/preprocess_sketch.go
  arduino/builder/progress/progress.go
  arduino/builder/recipe.go
  arduino/builder/sizer.go
  arduino/builder/sizer_test.go
  arduino/builder/sketch.go
  arduino/builder/sketch_test.go
  arduino/builder/utils/utils.go
  arduino/builder/utils/utils_test.go
  commands/compile/compile.go
  internal/integrationtest/compile_4/compile_test.go
  legacy/builder/builder.go
  legacy/builder/constants/constants.go
  legacy/builder/container_build_options.go
  legacy/builder/create_build_options_map.go
  legacy/builder/merge_sketch_with_bootloader.go
  legacy/builder/print_used_libraries_if_verbose.go
  legacy/builder/store_build_options_map.go
  legacy/builder/test/builder_test.go
  legacy/builder/test/builder_utils_test.go
  legacy/builder/test/create_build_options_map_test.go
  legacy/builder/test/helper.go
  legacy/builder/test/helper_tools_downloader.go
  legacy/builder/test/libraries_loader_test.go
  legacy/builder/test/load_previous_build_options_map_test.go
  legacy/builder/test/merge_sketch_with_bootloader_test.go
  legacy/builder/test/setup_build_properties_test.go
  legacy/builder/test/store_build_options_map_test.go
  legacy/builder/test/tools_loader_test.go
  legacy/builder/test/try_build_of_problematic_sketch_test.go
  legacy/builder/test/unused_compiled_libraries_remover_test.go
  legacy/builder/test/wipeout_build_path_if_build_options_changed_test.go
  legacy/builder/types/context.go
  legacy/builder/unused_compiled_libraries_remover.go
  legacy/builder/warn_about_arch_incompatible_libraries.go
  legacy/builder/wipeout_build_path_if_build_options_changed.go
Labels: topic: code

#2317 [skip-changelog] bye bye legacy
  .github/workflows/test-go-task.yml
  Taskfile.yml
  arduino/builder/build_options_manager.go
  arduino/builder/builder.go
  arduino/builder/core.go
  arduino/builder/export_cmake.go
  arduino/builder/libraries.go
  arduino/builder/linker.go
  arduino/builder/preprocess_sketch.go
  arduino/builder/recipe.go
  arduino/builder/sizer.go
  arduino/builder/sketch.go
  commands/compile/compile.go
  internal/integrationtest/daemon/daemon_test.go
  legacy/builder/.gitignore
  legacy/builder/builder.go
  legacy/builder/types/context.go
  legacy/builder/types/types.go
Labels: topic: code

#2319 [skip-changelog] Update golang to `1.21.1`
  .github/workflows/check-easyjson.yml
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  .github/workflows/i18n-weekly-pull.yaml
  .github/workflows/test-go-task.yml
  .licenses/go/github.com/gofrs/uuid/v5.dep.yml
  .licenses/go/golang.org/x/exp/constraints.dep.yml
  .licenses/go/golang.org/x/exp/slices.dep.yml
  DistTasks.yml
  arduino/builder/cpp/cpp.go
  arduino/builder/detector/detector.go
  arduino/builder/export_cmake.go
  arduino/builder/libraries.go
  arduino/builder/preprocessor/ctags.go
  arduino/builder/preprocessor/internal/ctags/ctags_has_issues.go
  arduino/builder/preprocessor/internal/ctags/ctags_parser.go
  arduino/cores/packagemanager/package_manager_test.go
  arduino/libraries/loader.go
  commands/board/list_test.go
  commands/compile/compile.go
  commands/core/search_test.go
  commands/debug/debug_test.go
  configuration/configuration_schema_test.go
  docs/CONTRIBUTING.md
  go.mod
  go.sum
  i18n/convert.go
  internal/cli/arguments/post_install.go
  internal/cli/completion/completion.go
  internal/cli/lib/search.go
  internal/integrationtest/board/hardware_loading_test.go
  internal/integrationtest/compile_3/core_caching_test.go
  internal/integrationtest/compile_4/compile_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/outdated/outdated_test.go
  internal/integrationtest/upload/upload_test.go
  internal/inventory/inventory.go
Labels: topic: infrastructure, topic: code

#2311 Add support for pre_uninstall scripts
  arduino/cores/packagemanager/install_uninstall.go
  arduino/cores/packagemanager/package_manager_test.go
  commands/core/install.go
  commands/core/uninstall.go
  commands/core/upgrade.go
  docs/platform-specification.md
  internal/cli/arguments/pre_post_script.go
  internal/cli/core/install.go
  internal/cli/core/uninstall.go
  internal/cli/core/upgrade.go
  internal/cli/upgrade/upgrade.go
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/core.proto
Labels: type: enhancement, topic: code

#2326 Improve signature check on library_index.json
  arduino/resources/index.go
  commands/instances.go
Labels: topic: security, topic: code, type: imperfection

#2296 [skip-changelog] Remove most of the direct accesses to `arduino` package
  commands/sketch/warn_deprecated.go
  internal/cli/arguments/sketch.go
  internal/cli/compile/compile.go
  internal/cli/sketch/archive.go
  internal/cli/upload/upload.go
Labels: type: enhancement, topic: code

#2320 Fix empty copy of compiled binaries when `--build-path` equals to `--output-dir`
  commands/compile/compile.go
  internal/integrationtest/compile_1/compile_test.go
Labels: topic: code, type: imperfection

#2333 Replace deprecated openpgp library
  .licensed.yml
  .licenses/go/github.com/ProtonMail/go-crypto/bitcurves.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/brainpool.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/eax.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/internal/byteutil.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/ocb.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/aes/keywrap.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/armor.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/ecdh.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/ecdsa.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/eddsa.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/elgamal.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/errors.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/internal/algorithm.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/internal/ecc.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/internal/encoding.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/packet.dep.yml
  .licenses/go/github.com/ProtonMail/go-crypto/openpgp/s2k.dep.yml
  .licenses/go/github.com/cloudflare/circl/dh/x25519.dep.yml
  .licenses/go/github.com/cloudflare/circl/dh/x448.dep.yml
  .licenses/go/github.com/cloudflare/circl/ecc/goldilocks.dep.yml
  .licenses/go/github.com/cloudflare/circl/internal/conv.dep.yml
  .licenses/go/github.com/cloudflare/circl/internal/sha3.dep.yml
  .licenses/go/github.com/cloudflare/circl/math.dep.yml
  .licenses/go/github.com/cloudflare/circl/math/fp25519.dep.yml
  .licenses/go/github.com/cloudflare/circl/math/fp448.dep.yml
  .licenses/go/github.com/cloudflare/circl/math/mlsbset.dep.yml
  .licenses/go/github.com/cloudflare/circl/sign.dep.yml
  .licenses/go/github.com/cloudflare/circl/sign/ed25519.dep.yml
  .licenses/go/github.com/cloudflare/circl/sign/ed448.dep.yml
  .licenses/go/golang.org/x/crypto/argon2.dep.yml
  .licenses/go/golang.org/x/crypto/blake2b.dep.yml
  .licenses/go/golang.org/x/crypto/sha3.dep.yml
  arduino/security/signatures.go
  go.mod
  go.sum
Labels: type: enhancement, topic: security, topic: infrastructure

#2336 Added `--timestamp` option to monitor command.
  internal/cli/monitor/monitor.go
  internal/cli/monitor/monitor_test.go
Labels: topic: code

#2330 [breaking] Eliminate BoardListWatchRequest `Interrupt` from the grpc api and make it server streaming only
  client_example/main.go
  commands/board/list.go
  commands/daemon/daemon.go
  docs/UPGRADING.md
  internal/cli/board/list.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_test.go
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
Labels: topic: code

#2339 legacy: Fixed regression on `compile --preprocess` output
  arduino/builder/builder.go
  commands/compile/compile.go
Labels: topic: code, type: imperfection

#2342 bugfix: excessive CPU/Disk usage when multiple build-paths points in the sketch directory
  arduino/globals/globals.go
  arduino/sketch/sketch.go
  commands/upload/upload.go
  internal/integrationtest/compile_1/compile_test.go
Labels: topic: code, type: imperfection

#2338 [skip-changelog] Use golangci-lint
  .github/workflows/check-go-task.yml
  .golangci.yml
  Taskfile.yml
  arduino/builder/internal/preprocessor/internal/ctags/ctags_has_issues.go
  arduino/builder/internal/utils/utils.go
  arduino/builder/linker.go
  arduino/builder/sketch.go
  arduino/cores/packagemanager/package_manager.go
  arduino/discovery/discovery.go
  arduino/errors.go
  arduino/globals/globals.go
  arduino/libraries/libraries.go
  client_example/main.go
  commands/daemon/stream.go
  commands/daemon/term_example/main.go
  commands/debug/debug.go
  executils/process.go
  internal/cli/arguments/port.go
  internal/cli/cli_test.go
  internal/cli/feedback/feedback.go
  internal/cli/lib/check_deps.go
  internal/cli/updater/updater.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/compile_2/compile_propeties_test.go
  internal/integrationtest/compile_2/compile_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/daemon/daemon_concurrency_test.go
  internal/integrationtest/daemon/daemon_test.go
  internal/integrationtest/main/main_test.go
  internal/integrationtest/outdated/outdated_test.go
  internal/integrationtest/profiles/profiles_test.go
  internal/integrationtest/sketch/sketch_test.go
  internal/integrationtest/upload/upload_test.go
  internal/inventory/inventory.go
Labels: topic: infrastructure, topic: code
