Repository arduino/arduino-cli, pull requests merged in 2024-07, with the labels that each got.

#2619 install.sh to work with wget
  install.sh
Labels: status: on hold, topic: infrastructure, type: imperfection

#2664 grpc: fixed BoardListWatch streaming call
  commands/service_board_list.go
  internal/cli/arguments/port.go
  internal/cli/board/list.go
  internal/integrationtest/daemon/daemon_test.go
Labels: type: imperfection, topic: gRPC

#2669 regression: fixed `ARDUINO_USER_AGENT` pollution / resolve compile-sketch GH action failure on Teensy
  commands/instances.go
Labels: topic: code, type: imperfection

#2652 Improved `{build.*.platform.path}` vars enumeration.
  docs/platform-specification.md
  go.mod
  go.sum
  internal/arduino/cores/packagemanager/package_manager.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/core/testdata/sketchbook_with_extended_platform/hardware/test/avr/boards.txt
Labels: type: enhancement, topic: code, topic: build-process

#2676 Document breaking change to `config get` command output
  docs/UPGRADING.md
Labels: topic: documentation, type: imperfection

#2678 Fixed link in docs.
  docs/library-specification.md
Labels: topic: documentation, type: imperfection

#2679 Update artifact-related actions
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release-go-task.yml
  .github/workflows/sync-labels.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#2682 Another small gh-action workflow fix.
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure

#2681 regression: Ensure BoardListWatch gRPC call correctly release resources
  commands/service_board_list.go
Labels: type: imperfection, topic: gRPC
