Repository arduino/arduino-cli, pull requests merged in 2024-12, with the labels that each got.

#2770 settings: add `network.connection_timeout` and `network.cloud_api.skip_board_detection_calls`
  commands/service_board_list.go
  commands/service_board_list_test.go
  commands/service_settings_test.go
  docs/configuration.md
  internal/cli/configuration/configuration.schema.json
  internal/cli/configuration/defaults.go
  internal/cli/configuration/network.go
  internal/cli/configuration/network_test.go
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
Labels: type: enhancement, topic: code

#2788 compile: fix export when artifacts contains a folder
  commands/service_compile.go
  internal/integrationtest/compile_1/compile_test.go
Labels: topic: code, type: imperfection

#2793 Small improvements in Taskfile about protocol buffer generation
  Taskfile.yml
Labels: topic: infrastructure, type: imperfection
