Repository arduino/arduino-cli, pull requests merged in 2024-09, with the labels that each got.

#2699 [skip changelog] Configure actions/upload-artifact action to upload required hidden files
  .github/workflows/check-go-dependencies-task.yml
Labels: topic: infrastructure, type: imperfection

#2693 Added possibility to set custom properties on upload/burn-bootloader/debug commands.
  commands/service_debug_config.go
  commands/service_upload.go
  commands/service_upload_burnbootloader.go
  commands/service_upload_test.go
  internal/cli/burnbootloader/burnbootloader.go
  internal/cli/debug/debug.go
  internal/cli/debug/debug_check.go
  internal/cli/upload/upload.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
  rpc/cc/arduino/cli/commands/v1/upload.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.proto
Labels: type: enhancement, topic: CLI, topic: gRPC

#2700 Add riscv64 linux tools download support
  docs/package_index_json-specification.md
  internal/arduino/cores/tools.go
  internal/arduino/cores/tools_test.go
Labels: type: enhancement, os: linux, topic: code

#2673 Refined the definition of `build_cache.path` and the `--build-path` behaviour
  commands/service_compile.go
  commands/service_compile_test.go
  commands/service_debug.go
  commands/service_debug_config.go
  commands/service_debug_test.go
  commands/service_upload.go
  commands/service_upload_burnbootloader.go
  commands/service_upload_test.go
  docs/UPGRADING.md
  internal/arduino/sketch/sketch.go
  internal/arduino/sketch/sketch_test.go
  internal/cli/arguments/arguments.go
  internal/cli/compile/compile.go
  internal/cli/configuration/build_cache.go
  internal/cli/configuration/configuration.go
  internal/cli/configuration/defaults.go
  internal/cli/debug/debug.go
  internal/cli/upload/upload.go
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/compile_4/compile_test.go
  internal/integrationtest/compile_4/core_caching_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/upload_mock/upload_mock_test.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
Labels: type: enhancement, topic: code
