Repository arduino/arduino-cli, pull requests merged in 2024-01, with the labels that each got.

#2482 Removed `export_cmake` hack
  internal/arduino/builder/builder.go
  internal/arduino/builder/export_cmake.go
Labels: type: enhancement, topic: code

#2480 Fix concurrent access to libraries manager gRPC functions.
  commands/core/download.go
  commands/core/install.go
  commands/instances.go
  commands/internal/instances/instances.go
  commands/lib/download.go
  commands/lib/install.go
  commands/lib/list.go
  commands/lib/resolve_deps.go
  commands/lib/search.go
  commands/lib/search_test.go
  commands/lib/uninstall.go
  commands/lib/upgrade.go
  commands/lib/utils.go
  commands/version.go
  internal/arduino/builder/internal/detector/detector.go
  internal/arduino/libraries/librariesindex/index.go
  internal/arduino/libraries/librariesindex/index_test.go
  internal/arduino/libraries/librariesindex/reference.go
  internal/arduino/libraries/librariesmanager/install.go
  internal/arduino/libraries/librariesmanager/librariesmanager.go
  internal/arduino/libraries/librariesmanager/librariesmanager_test.go
  internal/arduino/libraries/librariesresolver/cpp.go
  internal/arduino/libraries/librariesresolver/cpp_test.go
  internal/integrationtest/completion/completion_test.go
Labels: type: enhancement, topic: code

#2424 Drop support of package_bundled_index.json and builtin_tools_versions.txt
  commands/compile/compile.go
  docs/UPGRADING.md
  docs/configuration.md
  internal/arduino/builder/build_options_manager.go
  internal/arduino/builder/builder.go
  internal/arduino/cores/cores.go
  internal/arduino/cores/packagemanager/loader.go
  internal/arduino/cores/packagemanager/package_manager.go
  internal/cli/configuration/directories.go
  internal/integrationtest/compile_4/compile_test.go
  internal/integrationtest/core/core_test.go
Labels: type: enhancement, topic: code, status: blocked

#2276 feature: Added gRPC `close` signal to `Monitor` call (allows graceful close of monitor)
  commands/daemon/daemon.go
  commands/daemon/term_example/main.go
  commands/monitor/monitor.go
  docs/UPGRADING.md
  internal/arduino/monitor/monitor.go
  internal/cli/monitor/monitor.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_concurrency_test.go
  internal/integrationtest/daemon/daemon_test.go
  internal/integrationtest/monitor/monitor_grpc_test.go
  internal/mock_serial_monitor/main.go
  rpc/cc/arduino/cli/commands/v1/monitor.pb.go
  rpc/cc/arduino/cli/commands/v1/monitor.proto
Labels: type: enhancement, topic: gRPC

#2485 Fix install.sh for versions targs with `v` prefixed
  install.sh
Labels: topic: infrastructure, type: imperfection

#2490 [breaking] Improved .pde warnings detection subroutines / gRPC LoadSketch API improvement
  commands/daemon/daemon.go
  commands/instances.go
  commands/sketch/load.go
  docs/UPGRADING.md
  internal/arduino/sketch/profiles.go
  internal/arduino/sketch/sketch.go
  internal/arduino/sketch/sketch_test.go
  internal/cli/arguments/sketch.go
  internal/cli/board/attach.go
  internal/cli/compile/compile.go
  internal/cli/debug/debug.go
  internal/cli/feedback/warn_deprecated.go
  internal/cli/monitor/monitor.go
  internal/cli/sketch/archive.go
  internal/cli/upload/upload.go
  internal/integrationtest/sketch/sketch_test.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/internal/client_example/main.go
Labels: type: enhancement, topic: CLI, topic: gRPC

#2492 test: add missing file close
  internal/integrationtest/config/config_test.go
Labels: type: enhancement, topic: code

#2491 refactoring: Added `LibrariesManager.Clone()` / Auto-scan libs on `LibrariesManager.Build()`
  commands/instances.go
  commands/internal/instances/instances.go
  internal/arduino/builder/internal/detector/detector.go
  internal/arduino/libraries/librariesmanager/librariesmanager.go
  internal/arduino/libraries/librariesmanager/librariesmanager_test.go
Labels: type: enhancement, topic: code

#2494 Docs changes for 0.36.0 release
  README.md
  docs/CONTRIBUTING.md
  docs/installation.md
Labels: type: enhancement, topic: documentation

#2432 Allow empty configuration merging
  commands/daemon/settings.go
  commands/daemon/settings_test.go
Labels: type: enhancement, topic: code, topic: gRPC

#2496 [skip-changelog] update the build container to use go 1.21.6
  DistTasks.yml
Labels: type: enhancement, topic: infrastructure

#2501 Fixed missing `ARDUINO_USER_AGENT` env var setting.
  commands/compile/compile.go
  internal/arduino/builder/builder.go
  internal/integrationtest/compile_3/compile_env_var_test.go
  internal/integrationtest/compile_3/testdata/printenv/.gitignore
  internal/integrationtest/compile_3/testdata/printenv/main.go
Labels: topic: code, type: imperfection, topic: build-process

#2497 Fixed sketch compile with broken symlink
  .licenses/go/github.com/arduino/go-paths-helper.dep.yml
  go.mod
  go.sum
  internal/arduino/libraries/libraries_test.go
  internal/arduino/sketch/sketch.go
  internal/arduino/sketch/sketch_test.go
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/compile_4/broken_symlink_test.go
  internal/integrationtest/compile_4/testdata/ValidSketchWithBrokenSketchFileSymlink/ValidSketchWithBrokenSketchFileSymlink.ino
  internal/integrationtest/compile_4/testdata/ValidSketchWithBrokenSketchFileSymlink/other_file.ino
  internal/integrationtest/compile_4/testdata/ValidSketchWithBrokenSymlink/ValidSketchWithBrokenSymlink.ino
  internal/integrationtest/compile_4/testdata/ValidSketchWithBrokenSymlink/other_file
  internal/integrationtest/compile_4/testdata/ValidSketchWithNonInoBrokenSketchFileSymlink/ValidSketchWithNonInoBrokenSketchFileSymlink.ino
  internal/integrationtest/compile_4/testdata/ValidSketchWithNonInoBrokenSketchFileSymlink/other_file.c
Labels: topic: code, type: imperfection, topic: build-process

#2506 bugfix: do not panic if a sketch profile has a syntax error
  commands/instances.go
  internal/arduino/sketch/profiles.go
Labels: type: enhancement, topic: code

#2507 [breaking] Removed `Profile` protoc message in favor of `SketchProfile`
  commands/instances.go
  docs/UPGRADING.md
  internal/cli/compile/compile.go
  internal/cli/instance/instance.go
  internal/cli/monitor/monitor.go
  internal/cli/upload/upload.go
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
Labels: type: enhancement, topic: gRPC

#2512 Fixed an extremely rare race-condition during `compile`
  internal/arduino/builder/internal/compilation/database.go
  internal/arduino/builder/internal/compilation/database_test.go
Labels: type: imperfection, topic: build-process
