Repository arduino/arduino-cli, pull requests merged in 2024-10, with the labels that each got.

#2717 Allow port, protocol and port settings to be specified in profiles.
  docs/sketch-project-file.md
  internal/arduino/sketch/profiles.go
  internal/arduino/sketch/sketch.go
  internal/cli/arguments/fqbn.go
  internal/cli/arguments/port.go
  internal/cli/board/attach.go
  internal/cli/burnbootloader/burnbootloader.go
  internal/cli/compile/compile.go
  internal/cli/debug/debug.go
  internal/cli/debug/debug_check.go
  internal/cli/monitor/monitor.go
  internal/cli/upload/upload.go
  internal/integrationtest/monitor/monitor_test.go
  internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndConfig/SketchWithDefaultPortAndConfig.ino
  internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndConfig/sketch.yaml
  internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndConfigAndProfile/SketchWithDefaultPortAndConfigAndProfile.ino
  internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndConfigAndProfile/sketch.yaml
  internal/integrationtest/monitor/testdata/SketchWithDefaultPortAndFQBN/sketch.yaml
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/cc/arduino/cli/commands/v1/monitor.pb.go
  rpc/cc/arduino/cli/commands/v1/monitor.proto
Labels: type: enhancement, topic: code

#2707 Updated pluggable-discovery-protocol-handler library
  .licenses/go/github.com/arduino/pluggable-discovery-protocol-handler/v2.dep.yml
  go.mod
  go.sum
Labels: topic: code, type: imperfection

#2722 Disable auto-rebase on dependabot PR
  .github/dependabot.yml
Labels: type: enhancement, topic: infrastructure

#2728 Fix monitor init handling
  commands/service_monitor.go
  internal/cli/daemon/daemon.go
  internal/integrationtest/daemon/daemon_concurrency_test.go
Labels: type: imperfection, topic: gRPC

#2729 Increased gRPC message size limit to 16MB / added CLI flag to set the value
  internal/cli/daemon/daemon.go
  internal/cli/daemon/interceptors.go
Labels: type: enhancement, topic: gRPC

#2730 Set installer tmp path to env var
  install.sh
Labels: type: enhancement, topic: infrastructure

#2733 Fixed compiler-cache on Windows when there are non-ASCII characters in file path
  go.mod
  internal/arduino/builder/internal/utils/ansi_others.go
  internal/arduino/builder/internal/utils/ansi_windows.go
  internal/arduino/builder/internal/utils/utils.go
  internal/integrationtest/compile_4/lib_caching_test.go
Labels: type: imperfection, topic: build-process

#2732 Fix collision between macOS workflow artifacts in release workflows
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
Labels: os: macos, topic: infrastructure, type: imperfection

#2726 gRPC: if an `Upload` request is canceled, immediately terminate the upload tool process.
  commands/service_upload.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/upload_test.go
  internal/mock_avrdude/.gitignore
  internal/mock_avrdude/main.go
Labels: type: imperfection, topic: gRPC

#2736 Use `buf.build` to manage our protobuf related activities
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  Taskfile.yml
  buf.doc.gen.yaml
  buf.gen.yaml
  buf.lock
  buf.yaml
  docs/CONTRIBUTING.md
  rpc/buf.yaml
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/core.proto
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
  rpc/cc/arduino/cli/commands/v1/monitor.pb.go
  rpc/cc/arduino/cli/commands/v1/monitor.proto
  rpc/cc/arduino/cli/commands/v1/port.pb.go
  rpc/cc/arduino/cli/commands/v1/port.proto
  rpc/cc/arduino/cli/commands/v1/settings.pb.go
  rpc/cc/arduino/cli/commands/v1/settings.proto
  rpc/cc/arduino/cli/commands/v1/upload.pb.go
  rpc/cc/arduino/cli/commands/v1/upload.proto
  rpc/google/rpc/status.proto
Labels: type: enhancement, topic: infrastructure

#2739 Do not fail if downloaded file has good checksum but incorrect size.
  internal/arduino/resources/checksums.go
  internal/arduino/resources/resources_test.go
  internal/integrationtest/core/core_test.go
Labels: type: enhancement, topic: code
