Repository arduino/arduino-cli, pull requests merged in 2024-02, with the labels that each got.

#2521 [skip-changelog] bump setup-protoc to v3
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
Labels: type: enhancement, topic: infrastructure

#2505 Add `programmer` field to sketch profile and `--profile` flag to `debug` command
  commands/sketch/set_defaults.go
  commands/upload/upload.go
  docs/sketch-project-file.md
  internal/arduino/sketch/profiles.go
  internal/arduino/sketch/sketch.go
  internal/arduino/sketch/testdata/SketchWithProfiles/sketch.yml
  internal/cli/arguments/programmer.go
  internal/cli/board/attach.go
  internal/cli/compile/compile.go
  internal/cli/debug/debug.go
  internal/cli/upload/upload.go
  internal/integrationtest/board/board_test.go
  internal/integrationtest/debug/debug_test.go
  internal/integrationtest/testdata/sketch_with_profile/sketch.yaml
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
Labels: type: enhancement, topic: infrastructure

#2526 Added `--jobs/-j` flag to `compile` command
  internal/cli/compile/compile.go
Labels: type: enhancement, topic: CLI

#2509 [skip-changelog] Improve the definition of FQBN and explicitly state which characters are allowed
  docs/FAQ.md
  internal/arduino/cores/fqbn.go
  internal/arduino/cores/fqbn_test.go
Labels: type: enhancement, topic: documentation

#2307 add "config get" command to print settings values
  internal/cli/config/config.go
  internal/cli/config/get.go
  internal/integrationtest/config/config_test.go
Labels: type: enhancement, topic: code, topic: CLI

#2541 [skip-changelog] use OIDC to retrieve the credentials
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
Labels: type: enhancement, topic: infrastructure

#2540 Allow empty programmer in `debug` command
  commands/debug/debug_info.go
  commands/debug/debug_test.go
  internal/integrationtest/debug/debug_test.go
Labels: type: enhancement, topic: code

#2544 Allow optional programmer in `debug` command
  commands/debug/debug_info.go
  commands/debug/debug_test.go
  internal/integrationtest/debug/debug_test.go
Labels: type: enhancement, topic: code

#2551 gRPC `Compile` will now fail if a platform core has been modified.
  commands/cmderrors/cmderrors.go
  commands/compile/compile.go
  internal/arduino/cores/cores.go
  internal/arduino/cores/packagemanager/loader.go
  internal/arduino/cores/packagemanager/package_manager.go
  internal/integrationtest/daemon/detect_core_changes_test.go
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
Labels: type: enhancement, topic: code, topic: gRPC
