Repository arduino/arduino-cli, pull requests merged in 2024-05, with the labels that each got.

#2587 Remove `yaml` output format from `--format` flag. / Deprecate `--format json` in favor of `--json`
  .licenses/go/sigs.k8s.io/yaml.dep.yml
  .licenses/go/sigs.k8s.io/yaml/goyaml.v2.dep.yml
  docs/UPGRADING.md
  docs/getting-started.md
  docs/versioning.md
  go.mod
  go.sum
  internal/cli/cli.go
  internal/cli/core/upgrade.go
  internal/cli/feedback/feedback.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/board/board_test.go
  internal/integrationtest/board/hardware_loading_test.go
  internal/integrationtest/compile_1/compile_test.go
  internal/integrationtest/compile_3/compile_commands_test.go
  internal/integrationtest/compile_3/compile_show_properties_test.go
  internal/integrationtest/compile_3/compile_test.go
  internal/integrationtest/compile_3/lib_selection_test.go
  internal/integrationtest/compile_4/compile_test.go
  internal/integrationtest/config/config_test.go
  internal/integrationtest/core/core_test.go
  internal/integrationtest/debug/debug_test.go
  internal/integrationtest/lib/lib_test.go
  internal/integrationtest/main/main_test.go
  internal/integrationtest/profiles/profiles_test.go
  internal/integrationtest/upload/upload_test.go
Labels: type: enhancement, topic: code, topic: CLI

#2589 Fixed extremely rare race condition in DiscoveryManager
  internal/arduino/discovery/discoverymanager/discoverymanager.go
Labels: topic: code, type: imperfection

#2594 Fixed broken link (failing `check-links` test)
  docs/sketch-build-process.md
Labels: topic: documentation, type: imperfection

#2590 [skip-changelog] Correct profile dependency version constraint format in demo sketch project file
  docs/sketch-project-file.md
Labels: topic: documentation, type: imperfection

#2586 Add [skip-changelog] prefix to dependabot commit
  .github/dependabot.yml
Labels: type: enhancement, topic: infrastructure

#2605 Updated documentation about `arduino-cli` integration options.
  docs/img/CLI_Go_library_interface_screenshot.png
  docs/img/CLI_JSON_output_screenshot.png
  docs/img/CLI_configuration_methods_screenshot.png
  docs/img/CLI_gRPC_interface_screenshot.png
  docs/integration-options.md
  rpc/internal/get_version_example/main.go
  rpc/internal/list_cores_example/main.go
Labels: type: enhancement, topic: documentation

#2599 use eToken for signing
  .github/workflows/check-certificates.yml
  .github/workflows/publish-go-nightly-task.yml
  .github/workflows/release-go-task.yml
Labels: type: enhancement, topic: infrastructure

#2608 [BREAKING] Add protoc `oneof` clause where appropriate.
  commands/service_debug.go
  commands/service_debug_run.go
  commands/service_library_download.go
  commands/service_library_install.go
  commands/service_library_uninstall.go
  commands/service_library_upgrade.go
  commands/service_monitor.go
  commands/service_platform_download.go
  commands/service_platform_install.go
  commands/service_platform_uninstall.go
  commands/service_platform_upgrade.go
  docs/UPGRADING.md
  internal/cli/core/upgrade.go
  internal/integrationtest/daemon/daemon_test.go
  rpc/cc/arduino/cli/commands/v1/core.pb.go
  rpc/cc/arduino/cli/commands/v1/core.proto
  rpc/cc/arduino/cli/commands/v1/debug.pb.go
  rpc/cc/arduino/cli/commands/v1/debug.proto
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
  rpc/cc/arduino/cli/commands/v1/monitor.pb.go
  rpc/cc/arduino/cli/commands/v1/monitor.proto
Labels: type: enhancement, topic: gRPC

#2553 Preparing docs for `1.0.0` release
  README.md
  docs/UPGRADING.md
  docs/getting-started.md
  docs/versioning.md
Labels: type: enhancement, topic: documentation

#2609 gRPC: allow cancellation of downloads
  .licenses/go/go.bug.st/downloader/v2.dep.yml
  commands/instances.go
  commands/service_library_download.go
  commands/service_platform_download.go
  commands/service_platform_install.go
  commands/service_platform_upgrade.go
  go.mod
  go.sum
  internal/arduino/cores/packagemanager/download.go
  internal/arduino/cores/packagemanager/install_uninstall.go
  internal/arduino/cores/packagemanager/profiles.go
  internal/arduino/httpclient/httpclient.go
  internal/arduino/resources/download.go
  internal/arduino/resources/helpers_test.go
  internal/arduino/resources/index.go
  internal/arduino/resources/resources_test.go
Labels: topic: code, type: imperfection, topic: gRPC

#2612 [breaking] Allow setting extra paths for build-cache
  commands/service_compile.go
  docs/UPGRADING.md
  docs/configuration.md
  internal/arduino/builder/builder.go
  internal/arduino/builder/core.go
  internal/cli/configuration/build_cache.go
  internal/cli/configuration/configuration.schema.json
  internal/cli/configuration/defaults.go
  internal/integrationtest/compile_4/core_caching_test.go
  internal/integrationtest/compile_4/testdata/BareMinimum/BareMinimum.ino
  rpc/cc/arduino/cli/commands/v1/compile.pb.go
  rpc/cc/arduino/cli/commands/v1/compile.proto
Labels: type: enhancement, topic: code

#2620 [breaking] Renamed gRPC field `cc.arduino.cli.commands.v1.PlatformRelease.type` to `types`
  commands/service_platform_search_test.go
  commands/utility_core.go
  docs/UPGRADING.md
  internal/cli/feedback/result/rpc.go
  rpc/cc/arduino/cli/commands/v1/common.pb.go
  rpc/cc/arduino/cli/commands/v1/common.proto
Labels: type: imperfection, topic: gRPC
