Repository arduino/arduino-cli, pull requests merged in 2025-01, with the labels that each got.

#2804 [skip-changelog] Updated python deps
  poetry.lock
  pyproject.toml
Labels: type: enhancement, topic: infrastructure

#2806 fix: Sketch preprocessing errors were displayed on stdout instead of stderr
  internal/arduino/builder/preprocess_sketch.go
  internal/integrationtest/compile_3/compile_test.go
  internal/integrationtest/compile_3/testdata/blink_with_error_directive/blink_with_error_directive.ino
Labels: type: imperfection, topic: build-process

#2794 Added `BoardIdentify` gRPC call.
  commands/service_board_identify.go
  commands/service_board_identify_test.go
  commands/service_board_list.go
  internal/arduino/cores/packagemanager/package_manager.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/board_identification_test.go
  rpc/cc/arduino/cli/commands/v1/board.pb.go
  rpc/cc/arduino/cli/commands/v1/board.proto
  rpc/cc/arduino/cli/commands/v1/commands.pb.go
  rpc/cc/arduino/cli/commands/v1/commands.proto
  rpc/cc/arduino/cli/commands/v1/commands_grpc.pb.go
Labels: type: enhancement, topic: gRPC

#2811 [skip-changelog] Bump to go 1.23
  .github/workflows/check-easyjson.yml
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/check-i18n-task.yml
  .github/workflows/check-markdown-task.yml
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/check-protobuf-task.yml
  .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
  .github/workflows/i18n-weekly-pull.yaml
  .github/workflows/test-go-task.yml
  .golangci.yml
  .licenses/go/fortio.org/safecast.dep.yml
  .licenses/go/golang.org/x/crypto/sha3.dep.yml
  DistTasks.yml
  commands/instances.go
  commands/service_debug_config.go
  go.mod
  go.sum
  internal/arduino/builder/recipe.go
  internal/arduino/builder/sketch.go
  internal/arduino/cores/cores.go
  internal/arduino/libraries/librariesindex/json.go
  internal/arduino/libraries/librariesmanager/librariesmanager.go
  internal/arduino/libraries/librariesresolver/cpp.go
  internal/cli/lib/examples.go
  internal/go-configmap/configuration.go
Labels: type: enhancement, topic: infrastructure, topic: code

#2740 Added option to disable integrity checks in `core install` (for development purposes)
  commands/instances.go
  commands/service_library_install.go
  commands/service_platform_install.go
  commands/service_platform_upgrade.go
  docs/configuration.md
  internal/arduino/cores/packageindex/index.go
  internal/arduino/cores/packagemanager/install_uninstall.go
  internal/arduino/cores/packagemanager/profiles.go
  internal/arduino/resources/install.go
  internal/arduino/resources/install_test.go
  internal/cli/configuration/board_manager.go
  internal/cli/configuration/configuration.schema.json
  internal/cli/configuration/defaults.go
  internal/integrationtest/core/core_test.go
Labels: type: enhancement, topic: code

#2819 Fixed URL http -> https in integration tests.
  internal/integrationtest/board/board_test.go
Labels: type: enhancement, topic: infrastructure

#2817 Fixed panic if malformed 3rd party url is specified
  commands/instances.go
  internal/integrationtest/config/config_test.go
Labels: topic: code, type: imperfection

#2821 Removed direct links to gnu.org because the site is often down
  README.md
  docs/FAQ.md
Labels: type: enhancement, topic: infrastructure

#2789 Add metadata retrieved from the `context` to the user agent when a new HTTP client is created
  commands/instances.go
  commands/service_board_identify.go
  commands/service_board_identify_test.go
  commands/service_check_for_updates.go
  commands/service_library_download.go
  internal/arduino/resources/helpers_test.go
  internal/cli/configuration/network.go
  internal/cli/configuration/network_test.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/daemon/daemon_test.go
  internal/integrationtest/http_server.go
Labels: topic: code, type: imperfection

#2820 Suppress compile summary stats if `--quiet` flag is set on `compile`.
  commands/service_compile.go
  internal/arduino/builder/archive_compiled_files.go
  internal/arduino/builder/builder.go
  internal/arduino/builder/compilation.go
  internal/arduino/builder/core.go
  internal/arduino/builder/internal/detector/detector.go
  internal/arduino/builder/internal/preprocessor/ctags.go
  internal/arduino/builder/libraries.go
  internal/arduino/builder/linker.go
  internal/arduino/builder/logger/logger.go
  internal/arduino/builder/preprocess_sketch.go
  internal/arduino/builder/recipe.go
  internal/arduino/builder/sizer.go
  internal/arduino/builder/sketch.go
  internal/cli/compile/compile.go
  internal/integrationtest/compile_3/compile_verbosity_test.go
Labels: type: enhancement, topic: code
