Repository arduino/arduino-cli, pull requests merged in 2025-04, with the labels that each got.

#2882 fix: allow lib-install from git using revision hash as a reference
  internal/arduino/libraries/librariesmanager/install.go
  internal/integrationtest/lib/lib_test.go
Labels: topic: code, type: imperfection, topic: CLI, phase: implementation, criticality: medium

#2889 Fix user network config being ignored in package manger operations
  internal/arduino/cores/packagemanager/package_manager.go
  internal/arduino/cores/packagemanager/package_manager_test.go
Labels: topic: code, type: imperfection, topic: package-management

#2892 Fix readme notice about CLI versioning
  docs/index.md
Labels: type: enhancement, topic: documentation

#2896 [skip changelog] Fixed release workflow build
  .github/workflows/release-go-task.yml
Labels: type: enhancement, topic: infrastructure

#2898 [skip changelog] Bump markdown-link-check from 3.10.3 to 3.13.7
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#2900 [skip changelog] Revert "Disable internal anchor checks by link checker tool (#1692)"
  .markdown-link-check.json
Labels: topic: infrastructure, type: imperfection
