Repository arduino/arduino-cli, pull requests merged in 2025-07, with the labels that each got.

#2943 Do not use crossbuild container when CGO=0
  DistTasks.yml
Labels: type: enhancement, topic: infrastructure

#2940 Allow platforms without fixed version in profiles.
  commands/instances.go
  docs/sketch-project-file.md
  internal/arduino/cores/packagemanager/profiles.go
  internal/arduino/sketch/profiles.go
  internal/arduino/sketch/profiles_test.go
  internal/arduino/sketch/testdata/profiles/bad_profile_1.yml
  internal/arduino/sketch/testdata/profiles/profile_1.yml
Labels: type: enhancement, topic: CLI, topic: build-process

#2928 [skip changelog] Update golang to 1.24.4
  DistTasks.yml
  go.mod
Labels: topic: infrastructure

#2950 ci: push proto files to buf registry
  .github/workflows/release-proto-files.yml
  buf.yaml
Labels: type: enhancement, topic: infrastructure

#2951 Auto-import libraries based on sketch profile.
  commands/instances.go
  commands/service_compile.go
  internal/arduino/builder/internal/detector/cache.go
  internal/arduino/builder/internal/detector/detector.go
  internal/arduino/builder/internal/detector/source_file.go
  internal/arduino/builder/internal/preprocessor/arduino_preprocessor.go
  internal/arduino/builder/internal/preprocessor/ctags.go
  internal/arduino/builder/internal/preprocessor/gcc.go
  internal/arduino/builder/internal/runner/task.go
  internal/arduino/builder/preprocess_sketch.go
  internal/arduino/libraries/libraries_location.go
  internal/cli/feedback/result/rpc.go
  rpc/cc/arduino/cli/commands/v1/lib.pb.go
  rpc/cc/arduino/cli/commands/v1/lib.proto
Labels: type: enhancement, topic: code, topic: build-process

#2954 linker: allow multi-step link recipe (`c.combine`)
  docs/platform-specification.md
  internal/arduino/builder/builder.go
  internal/arduino/builder/linker.go
  internal/arduino/builder/recipe.go
  internal/arduino/builder/recipe_test.go
Labels: type: enhancement, topic: code, topic: build-process

#2963 Removed race condition in CI tests
  internal/integrationtest/arduino-cli.go
Labels: topic: infrastructure, type: imperfection
