Repository arduino/arduino-cli, pull requests merged in 2025-06, with the labels that each got.

#2926 Build and distribuite deb packages
  DistTasks.yml
  debian/Dockerfile
  debian/arduino-cli/DEBIAN/control
  debian/arduino-cli/DEBIAN/copyright
Labels: type: enhancement, os: linux, topic: infrastructure, topic: packaging

#2933 Improve error code when platform not available for OS
  commands/cmderrors/cmderrors.go
  commands/service_platform_install.go
  internal/arduino/cores/packagemanager/download.go
Labels: type: enhancement, topic: code

#2941 Updated formatting to new prettier standard
  docs/UPGRADING.md
  docs/configuration.md
  docs/package_index_json-specification.md
Labels: type: enhancement, topic: infrastructure
