Repository arduino/arduino-cli, pull requests merged in 2025-05, with the labels that each got.

#2903 [skip changelog] Correct configuration key name in documentation
  docs/configuration.md
Labels: topic: documentation, type: imperfection

#2904 [skip changelog] Add missing pages to website navigation panel
  mkdocs.yml
Labels: topic: documentation, topic: infrastructure, type: imperfection

#2902 Move information re: allowed characters for FQBN component to specifications
  docs/FAQ.md
  docs/package_index_json-specification.md
  docs/platform-specification.md
Labels: type: enhancement, topic: documentation

#2883 bugfix: Kill compile processes that generates too much output
  internal/arduino/builder/internal/preprocessor/gcc.go
  internal/integrationtest/arduino-cli.go
  internal/integrationtest/compile_5/recusive_include_test.go
  internal/integrationtest/compile_5/testdata/SketchWithRecursiveIncludes/SketchWithRecursiveIncludes.ino
  internal/integrationtest/compile_5/testdata/SketchWithRecursiveIncludes/a.h
Labels: type: enhancement, topic: CLI
